//! Create DTO for PostingInstructions.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::CountryCodeList;

/// Request body for creating a new PostingInstructions.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePostingInstructionsRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application_close_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application_instructions: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distribution_channel: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posting_end_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posting_start_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application_contact: Option<CreatePostingInstructionsAddressTypeArrayRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub application_location: Option<CreatePostingInstructionsPlaceRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePostingInstructionsAddressTypeArrayRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo_location: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo_location_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_office_box: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    #[garde(skip)]
    #[serde(default)]
    pub country_sub_divisions: Vec<CreatePostingInstructionsAddressTypeArrayAddressComponentRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePostingInstructionsAddressTypeArrayAddressComponentRequest {
    #[garde(skip)]
    pub r#type: String,
    #[garde(skip)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePostingInstructionsPlaceRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fax_number: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub job_opening_number: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub telephone: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<CreatePostingInstructionsPlaceAddressRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePostingInstructionsPlaceAddressRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo_location: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo_location_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_office_box: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    #[garde(skip)]
    #[serde(default)]
    pub country_sub_divisions: Vec<CreatePostingInstructionsPlaceAddressAddressComponentRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePostingInstructionsPlaceAddressAddressComponentRequest {
    #[garde(skip)]
    pub r#type: String,
    #[garde(skip)]
    pub value: String,
}
