//! Domain events for Code.
//! Generated by codegraph. DO NOT EDIT.

use chrono::{DateTime, Utc};
use serde::Serialize;
use uuid::Uuid;

/// Event payload carrying metadata for Code domain events.
#[derive(Debug, Clone, Serialize)]
#[allow(dead_code)]
pub struct CodeEventPayload {
    pub id: Uuid,
    pub correlation_id: Uuid,
    pub occurred_at: DateTime<Utc>,
    pub platform_organization_id: Uuid,
}

#[derive(Debug, Clone, Serialize)]
#[allow(dead_code)]
pub enum CodeEvent {


    Created(Box<CodeEventPayload>),





    Updated {
        payload: Box<CodeEventPayload>,
        changed_fields: Vec<String>,
    },



    Deleted(Box<CodeEventPayload>),







}
