//! Response DTO for Action.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Actiontypevalues;

/// Response body for Action.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct ActionResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_type: Option<Actiontypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_action_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_date_time_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_location_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_validity_period_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_value_id: Option<uuid::Uuid>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
