// Generated by codegraph. DO NOT EDIT.
// E2E tests for Application

import { test, expect } from '@playwright/test';
import { ApplicationFixture } from '../../fixtures/recruiting/recruiting_application';


const authToken = process.env.TEST_AUTH_TOKEN || '';


test.describe('Application — Create', () => {
  test('POST /api/v1/recruiting/application creates a Application', async ({ request }) => {
    const payload = ApplicationFixture.valid();
    const response = await request.post('/api/v1/recruiting/application', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
      data: payload,
    });
    expect(response.status()).toBe(201);
    const { data } = await response.json();
    expect(data).toHaveProperty('id');



    expect(data.applicationId).toBe(payload.applicationId);









  });

  test('POST without auth rejects with 401', async ({ request }) => {
    const data = ApplicationFixture.valid();
    const response = await request.post('/api/v1/recruiting/application', { data });
    expect(response.status()).toBe(401);
  });


  test('POST with missing required fields rejects with 422', async ({ request }) => {
    const data = ApplicationFixture.missingRequired();
    const response = await request.post('/api/v1/recruiting/application', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
      data,
    });
    expect(response.status()).toBe(422);
  });

});



test.describe('Application — Read', () => {
  test('GET /api/v1/recruiting/application returns paginated list', async ({ request }) => {
    const response = await request.get('/api/v1/recruiting/application', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body).toHaveProperty('data');
    expect(Array.isArray(body.data)).toBe(true);
  });

  test('GET /api/v1/recruiting/application/:id returns 404 for nonexistent', async ({ request }) => {
    const response = await request.get('/api/v1/recruiting/application/00000000-0000-0000-0000-000000000000', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
        expect(response.status()).toBe(404);
  });
});



test.describe('Application — Delete', () => {
  test('DELETE /api/v1/recruiting/application/:id removes a Application', async ({ request }) => {
    const created = await request.post('/api/v1/recruiting/application', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
      data: ApplicationFixture.valid(),
    });
    expect(created.status()).toBe(201);
    const { data } = await created.json();
    const id = data.id;

    const response = await request.delete(`/api/v1/recruiting/application/${id}`, {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
    expect(response.status()).toBe(204);

    const check = await request.get(`/api/v1/recruiting/application/${id}`, {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
        expect(check.status()).toBe(404);
  });
});



test.describe('Application — Pagination', () => {
  test('list supports page_size', async ({ request }) => {
    const response = await request.get('/api/v1/recruiting/application?page=0&page_size=5', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.data.length).toBeLessThanOrEqual(5);
  });
});

