//! Router for recruiting domain.
//! Generated by codegraph. DO NOT EDIT.

use axum::Router;

use crate::app_state::AppState;

pub fn router() -> Router<AppState> {
    Router::new()


        .nest("/application", application_routes())



        .nest("/candidate", candidate_routes())


}


fn application_routes() -> Router<AppState> {
    use super::application_handler;



    Router::new()

        .route("/", axum::routing::get(application_handler::list).post(application_handler::create))


        .route("/{application_id}", axum::routing::get(application_handler::get_by_id).put(application_handler::update).delete(application_handler::delete))






}


fn candidate_routes() -> Router<AppState> {
    use super::candidate_handler;

    use super::candidate_workflow;



    Router::new()

        .route("/", axum::routing::get(candidate_handler::list).post(candidate_handler::create))


        .route("/{candidate_id}", axum::routing::get(candidate_handler::get_by_id).put(candidate_handler::update))




        .route("/{candidate_id}/actions/transition", axum::routing::post(candidate_workflow::transition))

        .route("/{candidate_id}/actions/delegate", axum::routing::post(candidate_workflow::delegate))
        .route("/{candidate_id}/workflow", axum::routing::get(candidate_workflow::get_workflow_state))
        .route("/{candidate_id}/workflow/history", axum::routing::get(candidate_workflow::get_process_history))



}

