//! Domain errors for Events.
//! Generated by codegraph. DO NOT EDIT.

use axum::http::StatusCode;

#[derive(Debug, thiserror::Error)]
pub enum EventsError {

    #[error("{0}")]
    InternalError(String),
}

impl EventsError {
    pub fn code(&self) -> &'static str {
        match self {

            Self::InternalError(_) => "INTERNAL_ERROR",
        }
    }

    pub fn http_status(&self) -> StatusCode {
        match self {

            Self::InternalError(_) => StatusCode::INTERNAL_SERVER_ERROR,
        }
    }
}

impl From<sea_orm::DbErr> for EventsError {
    fn from(e: sea_orm::DbErr) -> Self {
        Self::InternalError(e.to_string())
    }
}

