//! Response DTO for PaymentInstructions.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::CountryCodeList;
pub use crate::codelist::CurrencyCodeList;

/// Response body for PaymentInstructions.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct PaymentInstructionsResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deployment_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_distribution: Option<PaymentInstructionsPaymentDistributionResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<PaymentInstructionsPaymentMethodResponse>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct PaymentInstructionsPaymentDistributionResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub percentage: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remaining_balance_indicator: Option<bool>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct PaymentInstructionsPaymentMethodResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_id: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bank_id: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub method_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name_on_account: Option<String>,
}
