//! Codelist enum for CommonOrganizationResponsibilityCode.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Inline enum values for OrganizationType.responsibilityCode
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[allow(clippy::enum_variant_names)]
pub enum CommonOrganizationResponsibilityCode {

    #[default]
    Unit,

    Department,

    Division,

    Parent,

    Group,

    Plant,

    Subsidiary,

    #[serde(rename = "Joint Venture")]
    JointVenture,

    Branch,

    #[serde(rename = "Holding Affiliate")]
    HoldingAffiliate,

}

impl std::fmt::Display for CommonOrganizationResponsibilityCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {

            Self::Unit => write!(f, "Unit"),

            Self::Department => write!(f, "Department"),

            Self::Division => write!(f, "Division"),

            Self::Parent => write!(f, "Parent"),

            Self::Group => write!(f, "Group"),

            Self::Plant => write!(f, "Plant"),

            Self::Subsidiary => write!(f, "Subsidiary"),

            Self::JointVenture => write!(f, "Joint Venture"),

            Self::Branch => write!(f, "Branch"),

            Self::HoldingAffiliate => write!(f, "Holding Affiliate"),

        }
    }
}

impl std::str::FromStr for CommonOrganizationResponsibilityCode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {

            "Unit" => Ok(Self::Unit),

            "Department" => Ok(Self::Department),

            "Division" => Ok(Self::Division),

            "Parent" => Ok(Self::Parent),

            "Group" => Ok(Self::Group),

            "Plant" => Ok(Self::Plant),

            "Subsidiary" => Ok(Self::Subsidiary),

            "Joint Venture" => Ok(Self::JointVenture),

            "Branch" => Ok(Self::Branch),

            "Holding Affiliate" => Ok(Self::HoldingAffiliate),

            _ => Err(format!("unknown CommonOrganizationResponsibilityCode value: {}", s)),
        }
    }
}
