//! Codelist enum for RateUnitCodeList.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// The unit of the given rate.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[allow(clippy::enum_variant_names)]
pub enum RateUnitCodeList {

    #[default]
    Dollars,

    DollarsPer1000CoveredVolume,

    DollarsPer100MonthlyBenefit,

    DollarsPer100MonthlyCoveredPayroll,

    DollarsPer10WeeklyBenefit,

    DollarsPer10WeeklyWeekly,

    PercentageOfSalary,

}

impl std::fmt::Display for RateUnitCodeList {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {

            Self::Dollars => write!(f, "Dollars"),

            Self::DollarsPer1000CoveredVolume => write!(f, "DollarsPer1000CoveredVolume"),

            Self::DollarsPer100MonthlyBenefit => write!(f, "DollarsPer100MonthlyBenefit"),

            Self::DollarsPer100MonthlyCoveredPayroll => write!(f, "DollarsPer100MonthlyCoveredPayroll"),

            Self::DollarsPer10WeeklyBenefit => write!(f, "DollarsPer10WeeklyBenefit"),

            Self::DollarsPer10WeeklyWeekly => write!(f, "DollarsPer10WeeklyWeekly"),

            Self::PercentageOfSalary => write!(f, "PercentageOfSalary"),

        }
    }
}

impl std::str::FromStr for RateUnitCodeList {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {

            "Dollars" => Ok(Self::Dollars),

            "DollarsPer1000CoveredVolume" => Ok(Self::DollarsPer1000CoveredVolume),

            "DollarsPer100MonthlyBenefit" => Ok(Self::DollarsPer100MonthlyBenefit),

            "DollarsPer100MonthlyCoveredPayroll" => Ok(Self::DollarsPer100MonthlyCoveredPayroll),

            "DollarsPer10WeeklyBenefit" => Ok(Self::DollarsPer10WeeklyBenefit),

            "DollarsPer10WeeklyWeekly" => Ok(Self::DollarsPer10WeeklyWeekly),

            "PercentageOfSalary" => Ok(Self::PercentageOfSalary),

            _ => Err(format!("unknown RateUnitCodeList value: {}", s)),
        }
    }
}
