//! Codelist enum for RecruitingRemoteWorkRestrictionCodes.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Inline enum values for RemoteWorkType.restrictionCodes
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[allow(clippy::enum_variant_names)]
pub enum RecruitingRemoteWorkRestrictionCodes {

    #[default]
    Local,

    Regional,

    Timezone,

    Country,

    Territory,

    Other,

}

impl std::fmt::Display for RecruitingRemoteWorkRestrictionCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {

            Self::Local => write!(f, "Local"),

            Self::Regional => write!(f, "Regional"),

            Self::Timezone => write!(f, "Timezone"),

            Self::Country => write!(f, "Country"),

            Self::Territory => write!(f, "Territory"),

            Self::Other => write!(f, "Other"),

        }
    }
}

impl std::str::FromStr for RecruitingRemoteWorkRestrictionCodes {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {

            "Local" => Ok(Self::Local),

            "Regional" => Ok(Self::Regional),

            "Timezone" => Ok(Self::Timezone),

            "Country" => Ok(Self::Country),

            "Territory" => Ok(Self::Territory),

            "Other" => Ok(Self::Other),

            _ => Err(format!("unknown RecruitingRemoteWorkRestrictionCodes value: {}", s)),
        }
    }
}
