//! Codelist enum for RecruitingCandidateStatus.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Inline enum values for CandidateType.status
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[allow(clippy::enum_variant_names)]
pub enum RecruitingCandidateStatus {

    #[default]
    #[serde(rename = "active")]
    Active,

    #[serde(rename = "inactive")]
    Inactive,

    #[serde(rename = "withdrawn")]
    Withdrawn,

}

impl std::fmt::Display for RecruitingCandidateStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {

            Self::Active => write!(f, "active"),

            Self::Inactive => write!(f, "inactive"),

            Self::Withdrawn => write!(f, "withdrawn"),

        }
    }
}

impl std::str::FromStr for RecruitingCandidateStatus {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {

            "active" => Ok(Self::Active),

            "inactive" => Ok(Self::Inactive),

            "withdrawn" => Ok(Self::Withdrawn),

            _ => Err(format!("unknown RecruitingCandidateStatus value: {}", s)),
        }
    }
}
