//! Response DTO for Modification.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Response body for Modification.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct ModificationResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_recovery_case_restructuring_task_record_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_recovery_restructuring_schedule_id: Option<uuid::Uuid>,
    pub modification_id: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
