//! Response DTO for RuleSet.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Rulesettypevalues;

/// Response body for RuleSet.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RuleSetResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_set_definition: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_set_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_set_interpretation: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_set_lifecycle_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_set_name_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_set_type: Option<Rulesettypevalues>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
