//! Update DTO for PayRun.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::CurrencyCodeList;
pub use crate::codelist::LanguageCodeList;
pub use crate::codelist::PayrollPayRunPayRunStatus;
pub use crate::codelist::PayrollPayRunPayRunType;

/// Request body for updating an existing PayRun.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct UpdatePayRunRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pay_run_type: Option<PayrollPayRunPayRunType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payroll_calendar_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub period_end_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub period_start_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posted_date_time: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_cost: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_cost_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_pay: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_pay_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alternate_ids: Option<Vec<IdentifierType>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
}
