//! Query service for PayRun. Generated by hr-graph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::PayRunResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait PayRunQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<PayRunResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<PayRunResponse>, QueryError>;
}
