//! Query service for Interestarrangement. Generated by codegraph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::InterestarrangementResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait InterestarrangementQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<InterestarrangementResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<InterestarrangementResponse>, QueryError>;
}
