//! Response DTO for Rate.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Response body for Rate.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RateResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate_capital_unit: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate_period_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate_unit: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate_value_id: Option<uuid::Uuid>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
