//! Query service for Involvedparty. Generated by codegraph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::InvolvedpartyResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait InvolvedpartyQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<InvolvedpartyResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<InvolvedpartyResponse>, QueryError>;
}
