//! Router for events domain.
//! Generated by codegraph. DO NOT EDIT.

use axum::Router;

use crate::app_state::AppState;
use crate::middleware::permission::PermissionGuard as _;

// Handwritten extensions — create this file to add custom routes.
// #[path = "handwritten_routes.rs"]
// mod handwritten_routes;

pub fn router() -> Router<AppState> {
    Router::new()


        .nest("/public-event", public_event_routes())


}


fn public_event_routes() -> Router<AppState> {
    use super::public_event_handler;



    Router::new()

        .route(
            "/",
            axum::routing::get(public_event_handler::list).guard("events:public-event", "list")
                .merge(axum::routing::post(public_event_handler::create).guard("events:public-event", "create")),
        )


        .route(
            "/{public_event_id}",
            axum::routing::get(public_event_handler::get_by_id).guard("events:public-event", "read")
                .merge(axum::routing::put(public_event_handler::update).guard("events:public-event", "update"))
                .merge(axum::routing::delete(public_event_handler::delete).guard("events:public-event", "delete")),
        )








        // API-key scope enforcement is DB-level (#169): RESTRICTIVE
        // scope_enforced_* RLS policies raise P0403 INSUFFICIENT_SCOPE for
        // out-of-scope keys, mapped to HTTP 403 by the generated error
        // mapper. No per-router scope middleware.
}


