<!-- Generated by codegraph. DO NOT EDIT. -->
<!-- Form component for CurrencyCodeList. -->
<script lang="ts">
	import * as Field from '$lib/components/ui/field/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import * as NativeSelect from '$lib/components/ui/native-select/index.js';
	import { Switch } from '$lib/components/ui/switch/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Spinner } from '$lib/components/ui/spinner/index.js';
	import { DateRangeField } from '$lib/components/ui/date-range-field/index.js';
	import { ArrayField } from '$lib/components/ui/array-field/index.js';
	import { StructuredWrapperField } from '$lib/components/ui/structured-wrapper-field/index.js';
	import * as m from '$lib/paraglide/messages.js';
	import type { CreateCurrencyCodeListRequest, UpdateCurrencyCodeListRequest } from '$lib/api/types';

	type FormData = CreateCurrencyCodeListRequest | UpdateCurrencyCodeListRequest;

	interface Props {
		mode: 'create' | 'edit';
		initialData?: Record<string, unknown>;
		onSubmit: (data: FormData) => void;
		submitting?: boolean;
	}

	let { mode, initialData = {}, onSubmit, submitting = false }: Props = $props();

	// Form state


	let code = $state(String(initialData['code'] ?? ''));



	let display_name = $state(String(initialData['display_name'] ?? ''));



	let sort_order = $state<number | undefined>(initialData['sort_order'] != null ? Number(initialData['sort_order']) : undefined);



	function handleSubmit(e: Event) {
		e.preventDefault();
		const data: Record<string, unknown> = {};

		if (mode === 'create') {


			data['code'] = code;



			data['display_name'] = display_name;



			if (sort_order !== undefined && sort_order !== null) data['sort_order'] = sort_order;


		} else {
			// Edit mode: only send changed fields


			if (code !== String(initialData['code'] ?? '')) data['code'] = code;



			if (display_name !== String(initialData['display_name'] ?? '')) data['display_name'] = display_name;



			if (sort_order !== Number(initialData['sort_order'])) data['sort_order'] = sort_order;


		}

		onSubmit(data as FormData);
	}
</script>

<form onsubmit={handleSubmit} class="space-y-6" aria-label={mode === 'create' ? m.common_currency_code_list_new() : m.common_edit() + ' ' + m.common_currency_code_list_title()} data-testid="currency_code_list-form">
	<Field.Group>


		<Field.Field>
			<Field.Label for="code">{m.common_currency_code_list_field_code()} <span class="text-destructive">*</span></Field.Label>
			<Input
				id="code"
				type="text"
				bind:value={code}
				required aria-required="true"
				
				disabled={mode === 'edit' && false}
			/>

		</Field.Field>



		<Field.Field>
			<Field.Label for="display_name">{m.common_currency_code_list_field_display_name()} <span class="text-destructive">*</span></Field.Label>
			<Input
				id="display_name"
				type="text"
				bind:value={display_name}
				required aria-required="true"
				
				disabled={mode === 'edit' && false}
			/>

		</Field.Field>



		<Field.Field>
			<Field.Label for="sort_order">{m.common_currency_code_list_field_sort_order()}</Field.Label>
			<Input
				id="sort_order"
				type="number"
				bind:value={sort_order}
				
				step="any"
				disabled={mode === 'edit' && false}
			/>

		</Field.Field>


	</Field.Group>



	<div class="flex flex-col-reverse gap-3 pt-4 sm:flex-row sm:justify-end">

		<Button variant="outline" type="button" onclick={() => history.back()} data-testid="currency_code_list-cancel-btn">
			{m.common_cancel()}
		</Button>
		<Button type="submit" disabled={submitting} data-testid="currency_code_list-submit-btn">
			{#if submitting}
				<Spinner class="mr-2 h-4 w-4" />
				{m.common_saving()}
			{:else}
				{mode === 'create' ? m.common_create() : m.common_save()}
			{/if}
		</Button>

	</div>
</form>
