//! Response DTO for Deviceidentification.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Deviceidentificationtypevalues;

/// Response body for Deviceidentification.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct DeviceidentificationResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_identification_type: Option<Deviceidentificationtypevalues>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
