//! Response DTO for Sessiontype.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Sessiontypevalues;

/// Response body for Sessiontype.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SessiontypeResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_type: Option<Sessiontypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_type_name_id: Option<uuid::Uuid>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
