//! Create DTO for Cardpaymentarrangement.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Arrangementtypevalues;
pub use crate::codelist::Contactpointtypevalues;
pub use crate::codelist::Partylocationtypevalues;
pub use crate::codelist::Paymentamountandcurrencytypevalues;
pub use crate::codelist::Paymentdatetimetypevalues;
pub use crate::codelist::Paymentidentificationtypevalues;
pub use crate::codelist::Paymentmethodtypevalues;
pub use crate::codelist::Paymentpurposevalues;
pub use crate::codelist::Paymentservicetypevalues;
pub use crate::codelist::Paymenttimevalues;
pub use crate::codelist::Paymenttypevalues;
pub use crate::codelist::Remittancedeliverymethodtypevalues;

/// Request body for creating a new Cardpaymentarrangement.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateCardpaymentarrangementRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub card_payment_arrangement_type: Option<Arrangementtypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_card_arrangement_identifier: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_frequency_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<Paymentmethodtypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_period_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_purpose: Option<Paymentpurposevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_schedule_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_time: Option<Paymenttimevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_type: Option<Paymenttypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remittance_delivery_method: Option<Remittancedeliverymethodtypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_type: Option<Paymentservicetypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_amount_and_currency: Option<CreateCardpaymentarrangementPaymentamountandcurrencyRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_date: Option<CreateCardpaymentarrangementPaymentdatetimeRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_identification: Option<CreateCardpaymentarrangementPaymentidentificationRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remittance_location: Option<CreateCardpaymentarrangementContactpointRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateCardpaymentarrangementPaymentamountandcurrencyRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_amount_and_currency: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_amount_and_currency_type: Option<Paymentamountandcurrencytypevalues>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateCardpaymentarrangementPaymentdatetimeRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_date_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_date_type: Option<Paymentdatetimetypevalues>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateCardpaymentarrangementPaymentidentificationRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_identification: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_identification_type: Option<Paymentidentificationtypevalues>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateCardpaymentarrangementContactpointRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact_point_type: Option<Contactpointtypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location_reference_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub party_location_type: Option<Partylocationtypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub party_reference_id: Option<uuid::Uuid>,
}
