//! Update DTO for Organization.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::CommonOrganizationGeographicResponsibilityCode;
pub use crate::codelist::CommonOrganizationOwnershipType;
pub use crate::codelist::CommonOrganizationResponsibilityCode;
pub use crate::codelist::CurrencyCodeList;
use super::dto_create::CreateOrganizationSpecifiedPersonRequest;
use super::dto_create::CreateOrganizationSpecifiedPersonCommunicationRequest;
use super::dto_create::CreateOrganizationSpecifiedPersonCommunicationAddressTypeArrayRequest;
use super::dto_create::CreateOrganizationSpecifiedPersonCommunicationAddressTypeArrayAddressComponentRequest;
use super::dto_create::CreateOrganizationSpecifiedPersonCommunicationEmailTypeArrayRequest;
use super::dto_create::CreateOrganizationSpecifiedPersonCommunicationPhoneTypeArrayRequest;
use super::dto_create::CreateOrganizationSpecifiedPersonCommunicationSocialTypeArrayRequest;
use super::dto_create::CreateOrganizationSpecifiedPersonCommunicationWebTypeArrayRequest;
use super::dto_create::CreateOrganizationSpecifiedPersonPersonNameRequest;
use super::dto_create::CreateOrganizationEstablishmentActivityRequest;
use super::dto_create::CreateOrganizationStatusRequest;
use super::dto_create::CreateOrganizationCommunicationRequest;
use super::dto_create::CreateOrganizationCommunicationAddressTypeArrayRequest;
use super::dto_create::CreateOrganizationCommunicationAddressTypeArrayAddressComponentRequest;
use super::dto_create::CreateOrganizationCommunicationEmailTypeArrayRequest;
use super::dto_create::CreateOrganizationCommunicationPhoneTypeArrayRequest;
use super::dto_create::CreateOrganizationCommunicationSocialTypeArrayRequest;
use super::dto_create::CreateOrganizationCommunicationWebTypeArrayRequest;

/// Request body for updating an existing Organization.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct UpdateOrganizationRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub former_tax_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geographic_responsibility: Option<CommonOrganizationGeographicResponsibilityCode>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub head_count: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub industry_codes: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub industry_identifiers: Option<Vec<IdentifierType>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub legal_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ownership_type: Option<CommonOrganizationOwnershipType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_company_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_company_tax_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revenue: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revenue_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stock_symbol: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trade_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub work_environment_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub responsibility: Option<CommonOrganizationResponsibilityCode>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_organization_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contacts: Option<Vec<CreateOrganizationSpecifiedPersonRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub organization_activity: Option<Vec<CreateOrganizationEstablishmentActivityRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_history: Option<Vec<CreateOrganizationStatusRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub communication: Option<CreateOrganizationCommunicationRequest>,
}
