// Generated by codegraph. DO NOT EDIT.
// Typed API client for PublicEvent

import type { APIRequestContext } from '@playwright/test';

export class PublicEventApi {
  constructor(private request: APIRequestContext, private baseUrl: string = '') {}


  async create(data: any): Promise<{ status: number; body: any }> {
    const response = await this.request.post(`${this.baseUrl}/api/v1/events/public-event`, { data });
    return { status: response.status(), body: await response.json().catch(() => ({})) };
  }


  async get(id: string): Promise<{ status: number; body: any }> {
    const response = await this.request.get(`${this.baseUrl}/api/v1/events/public-event/${id}`);
    return { status: response.status(), body: await response.json().catch(() => ({})) };
  }


  async list(params?: Record<string, string>): Promise<{ status: number; body: any }> {
    const qs = params ? '?' + new URLSearchParams(params).toString() : '';
    const response = await this.request.get(`${this.baseUrl}/api/v1/events/public-event${qs}`);
    return { status: response.status(), body: await response.json().catch(() => ({})) };
  }


  async update(id: string, data: any): Promise<{ status: number; body: any }> {
    const response = await this.request.patch(`${this.baseUrl}/api/v1/events/public-event/${id}`, { data });
    return { status: response.status(), body: await response.json().catch(() => ({})) };
  }


  async delete(id: string): Promise<{ status: number }> {
    const response = await this.request.delete(`${this.baseUrl}/api/v1/events/public-event/${id}`);
    return { status: response.status() };
  }

}
