<!-- Generated by codegraph. DO NOT EDIT. -->
<!-- Create page for Date. -->
<script lang="ts">
	import { goto } from '$app/navigation';

	import DateForm from '$lib/components/forms/DateForm.svelte';
	import { createDate } from '$lib/stores/common_date';
	import { toast } from 'svelte-sonner';
	import * as Card from '$lib/components/ui/card/index.js';
	import * as m from '$lib/paraglide/messages.js';
	import type { CreateDateRequest } from '$lib/api/types';


	const basePath = '/common/date';


	let submitting = $state(false);
	let error = $state('');

	async function handleSubmit(formData: CreateDateRequest) {
		submitting = true;
		error = '';
		try {

			const result = await createDate(formData);

			toast.success(m.common_entity_created({ entity: 'Date' }));
			goto(`${basePath}/${result.id}`);
		} catch (e) {
			error = (e as Error).message;
			toast.error(m.common_create_failed({ entity: 'Date' }));
		} finally {
			submitting = false;
		}
	}
</script>

<div class="space-y-6">
	<div>
		<a href={basePath} class="text-sm text-muted-foreground hover:text-foreground hover:underline">
			&larr; {m.common_back_to_list()}
		</a>
		<h2 class="mt-1 text-xl font-semibold">{m.common_date_new()}</h2>
	</div>


	{#if error}
		<div class="rounded-md bg-destructive/10 border border-destructive/20 p-4 text-sm text-destructive" role="alert">{error}</div>
	{/if}


	<Card.Root>
		<Card.Content class="p-4 sm:p-6">
			<DateForm mode="create" onSubmit={handleSubmit} {submitting} />
		</Card.Content>
	</Card.Root>
</div>
