//! Create DTO for PlanSetup.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::AgeCalculationRuleCodeList;
pub use crate::codelist::AgeFreezingCodeList;
pub use crate::codelist::AgeLimitCodeList;
pub use crate::codelist::BenefitEarningsTypeCodeList;
pub use crate::codelist::BenefitProductCodeList;
pub use crate::codelist::BenefitsOutOfPocketMaximumServiceApplicability;
pub use crate::codelist::BenefitsOutOfPocketMaximumUnitTime;
pub use crate::codelist::CommonOrganizationReferenceResponsibilityCode;
pub use crate::codelist::ContributionTaxTypeCodeList;
pub use crate::codelist::ContributorCodeList;
pub use crate::codelist::CountryCodeList;
pub use crate::codelist::CoverageDependencyCodeList;
pub use crate::codelist::CoverageLevelTierTypeCodeList;
pub use crate::codelist::CurrencyCodeList;
pub use crate::codelist::ElectionFrequencyCodeList;
pub use crate::codelist::EliminationCodeList;
pub use crate::codelist::EmployerContributionCodeList;
pub use crate::codelist::EvidenceOfInsurabilityCodeList;
pub use crate::codelist::FinalFilingRuleCodeList;
pub use crate::codelist::FinalFilingRuleTypeCodeList;
pub use crate::codelist::GenderCodeList;
pub use crate::codelist::GuaranteedIssueApprovalTypeCodeList;
pub use crate::codelist::GuaranteedIssueRuleTypeCodeList;
pub use crate::codelist::LTDDurationTypeCodeList;
pub use crate::codelist::ParticipantCodeList;
pub use crate::codelist::RateDifferentiatorTypeCodeList;
pub use crate::codelist::RateUnitCodeList;
pub use crate::codelist::RoundingRuleCodeList;
pub use crate::codelist::SurchargeCodeList;
pub use crate::codelist::TerminationRuleTypeCodeList;
pub use crate::codelist::WaitingRuleEventCodeList;
pub use crate::codelist::WaitingRuleTypeCodeList;

/// Request body for creating a new PlanSetup.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cobra_eligible_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cobra_enrollment_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alternate_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub billing_cutoff: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub carry_over_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub carry_over_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<CountryCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub debit_card_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub direct_bill_eligible_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_plan_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_period: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub grace_period: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_number_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub high_deductible_health_plan_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub legal_plan_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limited_purpose_conversion_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_effective_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_anniversary: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product: Option<BenefitProductCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retroactive_change_limit_months: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state_continuation_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub termination_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_based_plan_setup_type: Option<CreatePlanSetupAccountBasedPlanSetupRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub carrier_organization: Option<CreatePlanSetupOrganizationReferenceRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub final_filing_rule: Vec<CreatePlanSetupFinalFilingRuleRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub plan_eligibility_groups: Vec<CreatePlanSetupPlanEligibilityGroupRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub question_answers: Vec<CreatePlanSetupQuestionAnswerRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub waiting_rule_type: Vec<CreatePlanSetupWaitingRuleRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupAccountBasedPlanSetupRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_frequency_code: Option<ElectionFrequencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_tax_type_code: Option<ContributionTaxTypeCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_type_code: Option<ContributorCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum_contribution: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum_contribution_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum_contribution: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum_contribution_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employer_contribution_type: Option<CreatePlanSetupAccountBasedPlanSetupEmployerContributionRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupAccountBasedPlanSetupEmployerContributionRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_type: Option<EmployerContributionCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupOrganizationReferenceRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub responsibility_code: Option<CommonOrganizationReferenceResponsibilityCode>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub communication: Option<CreatePlanSetupOrganizationReferenceCommunicationRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupOrganizationReferenceCommunicationRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<CreatePlanSetupOrganizationReferenceCommunicationAddressTypeArrayRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<CreatePlanSetupOrganizationReferenceCommunicationEmailTypeArrayRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<CreatePlanSetupOrganizationReferenceCommunicationPhoneTypeArrayRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub social: Option<CreatePlanSetupOrganizationReferenceCommunicationSocialTypeArrayRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub web: Option<CreatePlanSetupOrganizationReferenceCommunicationWebTypeArrayRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupOrganizationReferenceCommunicationAddressTypeArrayRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo_location: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo_location_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_office_box: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    #[garde(skip)]
    #[serde(default)]
    pub country_sub_divisions: Vec<CreatePlanSetupOrganizationReferenceCommunicationAddressTypeArrayAddressComponentRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupOrganizationReferenceCommunicationAddressTypeArrayAddressComponentRequest {
    #[garde(skip)]
    pub r#type: String,
    #[garde(skip)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupOrganizationReferenceCommunicationEmailTypeArrayRequest {
    #[garde(skip)]
    pub address: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupOrganizationReferenceCommunicationPhoneTypeArrayRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub access: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub area_dialing_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_dialing_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dial_number: Option<String>,
    #[garde(skip)]
    pub formatted_number: String,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone_extension: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupOrganizationReferenceCommunicationSocialTypeArrayRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    #[garde(skip)]
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupOrganizationReferenceCommunicationWebTypeArrayRequest {
    #[garde(skip)]
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupFinalFilingRuleRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub final_filing_rule_code: Option<FinalFilingRuleCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub final_filing_rule_type_code: Option<FinalFilingRuleTypeCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub final_filing_rule_value: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_period: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub eligibility_group_name: Option<String>,
    #[garde(skip)]
    #[serde(default)]
    pub benefit_earnings: Vec<CreatePlanSetupPlanEligibilityGroupBenefitEarningsRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub coverage_tiers: Vec<CreatePlanSetupPlanEligibilityGroupCoverageTierRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dependency: Option<CreatePlanSetupPlanEligibilityGroupDependencyRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dependent_child_age_limit: Option<CreatePlanSetupPlanEligibilityGroupDependentChildAgeLimitRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub service_based_costs: Vec<CreatePlanSetupPlanEligibilityGroupServiceBasedCostRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub termination_rule: Option<CreatePlanSetupPlanEligibilityGroupTerminationRuleRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub waiting_rules: Vec<CreatePlanSetupPlanEligibilityGroupPlanEligibilityWaitingRuleRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupBenefitEarningsRequest {
    #[garde(skip)]
    pub code: BenefitEarningsTypeCodeList,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coverage_level_tier_type_code: Option<CoverageLevelTierTypeCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coverage_level_tier_type_value: Option<i64>,
    #[garde(skip)]
    #[serde(default)]
    pub account_details: Vec<CreatePlanSetupPlanEligibilityGroupCoverageTierAccountBasedPlanSetupRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub carry_over_amount: Option<CreatePlanSetupPlanEligibilityGroupCoverageTierCarryOverAmountRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_detail: Option<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub surcharges: Vec<CreatePlanSetupPlanEligibilityGroupCoverageTierSurchargeRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierAccountBasedPlanSetupRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_frequency_code: Option<ElectionFrequencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_tax_type_code: Option<ContributionTaxTypeCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_type_code: Option<ContributorCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum_contribution: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum_contribution_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum_contribution: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum_contribution_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employer_contribution_type: Option<CreatePlanSetupPlanEligibilityGroupCoverageTierAccountBasedPlanSetupEmployerContributionRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierAccountBasedPlanSetupEmployerContributionRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contribution_type: Option<EmployerContributionCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierCarryOverAmountRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum_dollar_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum_dollar_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum_dollar_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum_dollar_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percentage: Option<rust_decimal::Decimal>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub age_band_participant_type_code: Option<ParticipantCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub age_calculation_rule_code: Option<AgeCalculationRuleCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub age_freezing_code: Option<AgeFreezingCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub evidence_of_insurability_code: Option<EvidenceOfInsurabilityCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rounding_rule_code: Option<RoundingRuleCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tobacco_use_participant_type_code: Option<ParticipantCodeList>,
    #[garde(skip)]
    #[serde(default)]
    pub age_reduction_type: Vec<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupAgeReductionRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub rate_type: Vec<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupAgeReductionRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub age_threshold: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percent_reduction: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub frequency: Option<ElectionFrequencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_paid_by_employee: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_paid_by_employee_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_paid_by_employer: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_paid_by_employer_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_unit: Option<RateUnitCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub critical_illness_detail_type: Option<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateCriticalIllnessDetailRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub disability_detail_type: Vec<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateDisabilityDetailRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guaranteed_issue_type: Option<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateGuaranteedIssueRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub insurance_detail_type: Option<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateInsuranceDetailRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub rate_differentiator_type: Vec<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateRateDifferentiatorRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateCriticalIllnessDetailRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_maximum: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_maximum_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_minimum: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_minimum_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_incremental_dollar_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_incremental_dollar_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub specific_coverage_dollar_amounts: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub specific_coverage_dollar_amounts_currency: Option<CurrencyCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateDisabilityDetailRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub std_duration_weeks: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_weekly_maximum_dollar_benefit: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_weekly_maximum_dollar_benefit_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_weekly_percentage_of_earnings: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ltd_duration_type: Option<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateDisabilityDetailLTDDurationRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub buyup_option_type: Vec<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateDisabilityDetailBuyupOptionRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub elimination_period_type: Option<CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateDisabilityDetailEliminationPeriodRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateDisabilityDetailLTDDurationRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ltd_duration_maximum_age: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ltd_duration_reduction_age: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ltd_duration_type_code: Option<LTDDurationTypeCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ltd_duration_years: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateDisabilityDetailBuyupOptionRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_weekly_maximum_dollar_benefit: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_weekly_maximum_dollar_benefit_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_weekly_percentage_increase: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateDisabilityDetailEliminationPeriodRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub elimination_code: Option<EliminationCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub elimination_days: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateGuaranteedIssueRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guaranteed_issue_approval_type_code: Option<GuaranteedIssueApprovalTypeCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guaranteed_issue_dollar_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guaranteed_issue_dollar_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guaranteed_issue_multiple_of_earnings: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guaranteed_issue_multiple_of_earnings_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guaranteed_issue_rule_type_code: Option<GuaranteedIssueRuleTypeCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateInsuranceDetailRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_dollar_adjustment: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_dollar_adjustment_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_dollar_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_dollar_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_dollar_maximum: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_dollar_maximum_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_dollar_minimum: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_dollar_minimum_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_multiple_of_earnings: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_increment: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_increment_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_maximum: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_maximum_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_minimum: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_dollar_minimum_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_multiple_increment: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_multiple_of_earnings_maximum: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buyup_multiple_of_earnings_minimum: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierRateBasedPlanSetupPlanRateRateDifferentiatorRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub critical_illness_specific_amount_ordinal: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gender: Option<GenderCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lower_age_range_value: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_differentiator_type_code: Option<RateDifferentiatorTypeCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tobacco_user: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upper_age_range_value: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupCoverageTierSurchargeRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub surcharge_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub surcharge_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub surcharge_code: Option<SurchargeCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupDependencyRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coverage_dependency_code: Option<CoverageDependencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coverage_dependency_percent: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coverage_dependency_percent_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default)]
    pub must_enroll_in_all_of: Vec<CreatePlanSetupPlanEligibilityGroupDependencyDependencyItemRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupDependencyDependencyItemRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dependent_eligibility_group_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dependent_eligibility_group_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dependent_plan_alternate_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dependent_plan_identifier: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dependent_product_code: Option<BenefitProductCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupDependentChildAgeLimitRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub age_limit: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub age_limit_code: Option<AgeLimitCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub student_age_limt: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupServiceBasedCostRequest {
    #[garde(skip)]
    #[serde(default)]
    pub coinsurance: Vec<CreatePlanSetupPlanEligibilityGroupServiceBasedCostCoinsuranceRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub copays: Vec<CreatePlanSetupPlanEligibilityGroupServiceBasedCostCopayRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub deductibles: Vec<CreatePlanSetupPlanEligibilityGroupServiceBasedCostDeductibleRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub out_of_pocket_maximums: Vec<CreatePlanSetupPlanEligibilityGroupServiceBasedCostOutOfPocketMaximumRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupServiceBasedCostCoinsuranceRequest {
    #[garde(skip)]
    pub coinsurance_amount: rust_decimal::Decimal,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupServiceBasedCostCopayRequest {
    #[garde(skip)]
    pub copay_amount: rust_decimal::Decimal,
    #[garde(skip)]
    pub copay_amount_currency: CurrencyCodeList,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupServiceBasedCostDeductibleRequest {
    #[garde(skip)]
    pub deductible_amount: rust_decimal::Decimal,
    #[garde(skip)]
    pub deductible_amount_currency: CurrencyCodeList,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupServiceBasedCostOutOfPocketMaximumRequest {
    #[garde(skip)]
    pub out_of_pocket_maximum_amount: rust_decimal::Decimal,
    #[garde(skip)]
    pub out_of_pocket_maximum_amount_currency: CurrencyCodeList,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_applicability: Option<BenefitsOutOfPocketMaximumServiceApplicability>,
    #[garde(skip)]
    pub unit_time: BenefitsOutOfPocketMaximumUnitTime,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupTerminationRuleRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub termination_rule_type_code: Option<TerminationRuleTypeCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub termination_rule_value: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupPlanEligibilityGroupPlanEligibilityWaitingRuleRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub roll_forward_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rule_value: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub waiting_rule_event_code: Option<WaitingRuleEventCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub waiting_rule_type_code: Option<WaitingRuleTypeCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupQuestionAnswerRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub question: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub question_set_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePlanSetupWaitingRuleRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub roll_forward_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rule_value: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub waiting_rule_event_code: Option<WaitingRuleEventCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub waiting_rule_type_code: Option<WaitingRuleTypeCodeList>,
}
