//! Response DTO for AccountReconciliationProcedure.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Accountdatetimetypevalues;
pub use crate::codelist::Accountidentificationtypevalues;
pub use crate::codelist::Accountstatustypevalues;
pub use crate::codelist::Accounttypevalues;
pub use crate::codelist::Actiontypevalues;
pub use crate::codelist::Agreementtypevalues;
pub use crate::codelist::Arrangementtypevalues;
pub use crate::codelist::Assetclassificationtypevalues;
pub use crate::codelist::Assetsubclassificationtypevalues;
pub use crate::codelist::Assettypevalues;
pub use crate::codelist::Balancecounterpartytypevalues;
pub use crate::codelist::Balancesubtypevalues;
pub use crate::codelist::Balancetypevalues;
pub use crate::codelist::Bankingproducttypevalues;
pub use crate::codelist::Contactpointtypevalues;
pub use crate::codelist::Currencytypevalues;
pub use crate::codelist::Debitcreditindicatortvalues;
pub use crate::codelist::Featuretypevalues;
pub use crate::codelist::Financialinstrumenttypevalues;
pub use crate::codelist::Instructiontypevalues;
pub use crate::codelist::Partylocationtypevalues;
pub use crate::codelist::Paymentamountandcurrencytypevalues;
pub use crate::codelist::Paymentdatetimetypevalues;
pub use crate::codelist::Paymentidentificationtypevalues;
pub use crate::codelist::Paymentmethodtypevalues;
pub use crate::codelist::Paymentpurposevalues;
pub use crate::codelist::Paymentservicetypevalues;
pub use crate::codelist::Paymenttimevalues;
pub use crate::codelist::Paymenttypevalues;
pub use crate::codelist::Proceduretypevalues;
pub use crate::codelist::Remittancedeliverymethodtypevalues;
pub use crate::codelist::Servicetypevalues;
pub use crate::codelist::Systemidentificationtypevalues;
pub use crate::codelist::Systemstatustypevalues;
pub use crate::codelist::Transactiontotalstypevalues;
pub use crate::codelist::Transactiontypevalues;

/// Response body for AccountReconciliationProcedure.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_associated_party_reference_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_business_unit_reference_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_customer_reference_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_document_reference_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_employee_reference_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_financial_transaction_arrangement_id: Option<uuid::Uuid>,
    pub account_reconciliation_procedure_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_parameter_type: Option<Featuretypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_reference_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_request_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_schedule_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_selected_option_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_service_provider_reference_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_service_provider_schedule_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_transaction_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_account_reference: Option<AccountReconciliationProcedureAccountResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_customer_agreement_reference: Option<AccountReconciliationProcedureAgreementResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_financial_facility_reference: Option<AccountReconciliationProcedureFinancialFacilityResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_productand_service_instance: Option<AccountReconciliationProcedureProductResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_productand_service_type: Option<AccountReconciliationProcedureBankingproducttypeResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_service_type: Option<AccountReconciliationProcedureServicetypeResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_system_reference: Option<AccountReconciliationProcedureSystemResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_transaction_type: Option<AccountReconciliationProcedureTransactiontypeResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_reconciliation_procedure_type: Option<AccountReconciliationProcedureProceduretypeResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reconciliation_arrangement_reference: Option<AccountReconciliationProcedureTransactionReconciliationArrangementResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reconciliation_request_reference: Option<AccountReconciliationProcedureReconciliationInstructionResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reconciliation_transaction_reference: Option<AccountReconciliationProcedureReconciliationTransactionResponse>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureAccountResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_name_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_purpose: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_type: Option<Accounttypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub log_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub log_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub log_period_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub log_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_balance: Option<AccountReconciliationProcedureAccountAccountbalanceResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_currency: Option<AccountReconciliationProcedureAccountAccountcurrencyResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_date: Option<AccountReconciliationProcedureAccountAccountdatetimeResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_identification: Option<AccountReconciliationProcedureAccountAccountidentificationResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_status: Option<AccountReconciliationProcedureAccountAccountstatusResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureAccountAccountbalanceResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub balance_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub balance_calculation_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub balance_counterparty_type: Option<Balancecounterpartytypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub balance_indicator: Option<Debitcreditindicatortvalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub balance_sub_type: Option<Balancesubtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub balance_type: Option<Balancetypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub balance_value_date_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureAccountAccountcurrencyResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_currency_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_currency_type: Option<Currencytypevalues>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureAccountAccountdatetimeResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_date_type: Option<Accountdatetimetypevalues>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureAccountAccountidentificationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_identification_type: Option<Accountidentificationtypevalues>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureAccountAccountstatusResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_status_type: Option<Accountstatustypevalues>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureAgreementResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agreement_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agreement_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agreement_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agreement_signed_date: Option<chrono::NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agreement_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agreement_subject_matter: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agreement_type: Option<Agreementtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agreement_validity_period_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agreement_version: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureFinancialFacilityResponse {
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureProductResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_classification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_classification_type: Option<Assetclassificationtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_sub_classification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_sub_classification_type: Option<Assetsubclassificationtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_type: Option<Assettypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub financial_instrument_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub financial_instrument_identification_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub financial_instrument_name_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub financial_instrument_type: Option<Financialinstrumenttypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_identification_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_lifecycle_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_name_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_priority: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_type: Option<Bankingproducttypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_version: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureBankingproducttypeResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_classification_issuing_authority: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_type: Option<Bankingproducttypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_type_definition: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureServicetypeResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_type: Option<Servicetypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_type_name_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureSystemResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_access_schedule_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_date_time_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_identification_type: Option<Systemidentificationtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_status_type: Option<Systemstatustypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_type: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureTransactiontypeResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<Transactiontypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_type_name_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureProceduretypeResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub procedure_type: Option<Proceduretypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub procedure_type_name_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureTransactionReconciliationArrangementResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrangement_action_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrangement_end_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrangement_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrangement_start_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrangement_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrangement_subject_matter_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrangementtype: Option<Arrangementtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub close_period_indicator: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reconciliation_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_number: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<Transactiontotalstypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_payment: Option<AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_payment_arrangement_type: Option<Arrangementtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_card_arrangement_identifier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_frequency_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<Paymentmethodtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_period_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_purpose: Option<Paymentpurposevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_schedule_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_time: Option<Paymenttimevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_type: Option<Paymenttypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remittance_delivery_method: Option<Remittancedeliverymethodtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_type: Option<Paymentservicetypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_amount_and_currency: Option<AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementPaymentamountandcurrencyResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_date: Option<AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementPaymentdatetimeResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_identification: Option<AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementPaymentidentificationResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remittance_location: Option<AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementContactpointResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementPaymentamountandcurrencyResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_amount_and_currency: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_amount_and_currency_type: Option<Paymentamountandcurrencytypevalues>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementPaymentdatetimeResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_date_type: Option<Paymentdatetimetypevalues>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementPaymentidentificationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_identification_type: Option<Paymentidentificationtypevalues>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureTransactionReconciliationArrangementCardpaymentarrangementContactpointResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_point_type: Option<Contactpointtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_reference_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_location_type: Option<Partylocationtypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_reference_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureReconciliationInstructionResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instruction_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instruction_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instruction_identification_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instruction_log_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instruction_purpose: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instruction_result: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instruction_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instruction_type: Option<Instructiontypevalues>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct AccountReconciliationProcedureReconciliationTransactionResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_type: Option<Actiontypevalues>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cumulative_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_action_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_date_time_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_location_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_validity_period_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_value_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reconciliation_transaction_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_date_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_name_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_status_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<Transactiontypevalues>,
}
