//! Update DTO for Instructionstatus.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Instructionstatustypevalues;

/// Request body for updating an existing Instructionstatus.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct UpdateInstructionstatusRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instruction_status_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instruction_status_type: Option<Instructionstatustypevalues>,
}
