//! Create DTO for PaySlip.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::CurrencyCodeList;
pub use crate::codelist::LanguageCodeList;
pub use crate::codelist::PayTypeCodeList;
pub use crate::codelist::PayrollPaySlipPaymentMethod;
pub use crate::codelist::TimeOffTypeCodeList;
pub use crate::codelist::USBenefitTypeCodeList;
pub use crate::codelist::VoluntaryBenefitTypeCodeList;

/// Request body for creating a new PaySlip.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gross_earnings: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gross_earnings_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<PayrollPaySlipPaymentMethod>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_earnings: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_earnings_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_pay: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_pay_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    pub worker_id: IdentifierType,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alternate_ids: Option<Vec<IdentifierType>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub direct_compensation: Option<CreatePaySlipDirectCompensationRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub indirect_compensation: Option<CreatePaySlipIndirectCompensationRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub taxable_compensation: Vec<CreatePaySlipTaxableCompensationRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub worker_withholding: Option<CreatePaySlipWorkerWithholdingRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipDirectCompensationRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub salary_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub salary_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_holiday_paid_time_off_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_holiday_paid_time_off_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_hourly_wage_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_hourly_wage_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_other_compensation_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_other_compensation_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_paid_timeoff_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_paid_timeoff_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_premium_hourly_wage_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_premium_hourly_wage_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default)]
    pub other_compensation_amount: Vec<CreatePaySlipDirectCompensationWorkedCompensationAmountRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub paid_time_off_amount: Vec<CreatePaySlipDirectCompensationTimeOffCompensationAmountRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipDirectCompensationWorkedCompensationAmountRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub worked_pay_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub worked_pay_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub worked_pay_type_code: Option<PayTypeCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipDirectCompensationTimeOffCompensationAmountRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_off_pay_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_off_pay_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_off_pay_type: Option<TimeOffTypeCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipIndirectCompensationRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_non_voluntary_benefit_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_non_voluntary_benefit_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_voluntary_benefit_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_voluntary_benefit_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default)]
    pub non_voluntary_benefit_amount: Vec<CreatePaySlipIndirectCompensationNonVoluntaryBenefitAmountRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub voluntary_benefit_amount: Vec<CreatePaySlipIndirectCompensationVoluntaryBenefitAmountRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipIndirectCompensationNonVoluntaryBenefitAmountRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub type_code: Option<USBenefitTypeCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipIndirectCompensationVoluntaryBenefitAmountRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub type_code: Option<VoluntaryBenefitTypeCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipTaxableCompensationRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipWorkerWithholdingRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_insurance_premiums_withholding_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_insurance_premiums_withholding_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_other_withholding_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_other_withholding_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_retirement_withholding_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_retirement_withholding_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_tax_withholding_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_tax_withholding_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default)]
    pub insurance_premiums_withholding_amount: Vec<CreatePaySlipWorkerWithholdingWithholdingAmountRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePaySlipWorkerWithholdingWithholdingAmountRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub type_code: Option<String>,
}
