//! Query service for PaySlip. Generated by hr-graph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::PaySlipResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait PaySlipQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<PaySlipResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<PaySlipResponse>, QueryError>;
}
