//! Shared OpenAPI security modifier.
//! Generated by codegraph. DO NOT EDIT.

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::Modify;

/// Adds API key security scheme to the OpenAPI spec.
pub struct ApiKeySecurity;

impl Modify for ApiKeySecurity {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "ApiKeyAuth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("API Key")
                    .description(Some("API key obtained from create_api_key(). Format: sk_..."))
                    .build(),
            ),
        );
    }
}
