// Generated by codegraph. DO NOT EDIT.
// Svelte store for StringTypeArray CRUD operations.

import { writable } from 'svelte/store';
import { apiGet, apiPost, apiPut, apiDelete } from '$lib/api/client';
import type {
	StringTypeArrayResponse,

	CreateStringTypeArrayRequest,


	UpdateStringTypeArrayRequest,


} from '$lib/api/types';


const API_PATH = '/common/string-type-array';


export interface StringTypeArrayListState {
	items: StringTypeArrayResponse[];
	loading: boolean;
	error: string | null;
}

export const string_type_arrayList = writable<StringTypeArrayListState>({
	items: [],
	loading: false,
	error: null
});



export async function listStringTypeArray(page = 0, pageSize = 20): Promise<StringTypeArrayResponse[]> {

	string_type_arrayList.update(s => ({ ...s, loading: true, error: null }));
	try {

		const items = await apiGet<StringTypeArrayResponse[]>(API_PATH, { page, page_size: pageSize });

		string_type_arrayList.set({ items, loading: false, error: null });
		return items;
	} catch (e) {
		const msg = (e as Error).message;
		string_type_arrayList.update(s => ({ ...s, loading: false, error: msg }));
		throw e;
	}
}




export async function getStringTypeArray(id: string): Promise<StringTypeArrayResponse> {
	return apiGet<StringTypeArrayResponse>(`${API_PATH}/${id}`);

}




export async function createStringTypeArray(data: CreateStringTypeArrayRequest): Promise<StringTypeArrayResponse> {
	const result = await apiPost<StringTypeArrayResponse>(API_PATH, data);

	string_type_arrayList.update(s => ({ ...s, items: [...s.items, result] }));
	return result;
}




export async function updateStringTypeArray(id: string, data: UpdateStringTypeArrayRequest): Promise<StringTypeArrayResponse> {
	const result = await apiPut<StringTypeArrayResponse>(`${API_PATH}/${id}`, data);

	string_type_arrayList.update(s => ({
		...s,
		items: s.items.map(item => item.id === id ? result : item)
	}));
	return result;
}




export async function deleteStringTypeArray(id: string): Promise<void> {
	await apiDelete(`${API_PATH}/${id}`);

	string_type_arrayList.update(s => ({
		...s,
		items: s.items.filter(item => item.id !== id)
	}));
}


