//! SeaORM entity for Candidate.
//! Generated by hr-graph. DO NOT EDIT.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, Default, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "recruiting", table_name = "candidate")]
pub struct Model {


    #[sea_orm(primary_key, auto_increment = false)]

    pub id: Uuid,


    pub platform_organization_id: Uuid,


    pub birth_date: Option<chrono::NaiveDate>,


    pub family_name: String,


    pub given_name: String,


    pub candidate_id: String,


    pub compensation_expectation: Option<rust_decimal::Decimal>,


    pub compensation_expectation_currency: Option<String>,


    pub gender: Option<String>,


    pub position_titles: Option<Vec<String>>,


    pub referred_by_application_id: Option<Uuid>,


    pub status: Option<String>,


    pub uri: Option<String>,


    pub created_at: chrono::DateTime<chrono::Utc>,


    pub updated_at: chrono::DateTime<chrono::Utc>,


    pub deleted_at: Option<DateTimeWithTimeZone>,


    pub deleted_by: Option<Uuid>,


    pub updated_by: Option<Uuid>,


    pub is_demo_data: bool,

}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {

}

impl ActiveModelBehavior for ActiveModel {}
