//! Byte-exact expected outputs for the spec-less IFML svelte fixture.
//! Captured from the pre-change generator; the templates must reproduce
//! these files verbatim when no component specs are present.

pub const SPECLESS_CUSTOMERLIST_PAGE: &str = r##"<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<title>Customer Management</title>
</svelte:head>



<h1>Customer Management</h1>
<table>
	<thead>
		<tr>
		
			<th>name</th>
		
			<th>email</th>
		
			<th>phone</th>
		
			<th>status</th>
		
		</tr>
	</thead>
	<tbody>
		{#each data.items as item}
			<tr>
			
				<td>{item.name</td>
			
				<td>{item.email</td>
			
				<td>{item.phone</td>
			
				<td>{item.status</td>
			
			</tr>
		{/each}
	</tbody>
</table>



"##;

pub const SPECLESS_CUSTOMERLIST_LOAD: &str = r##"import type { PageLoad } from './$types';

export const load: PageLoad = async ({ params, fetch }) => {


	const response = await fetch('/api/v1/customer');
	const items = await response.json();

	return { items };




	return {};
};
"##;

pub const SPECLESS_CUSTOMERDETAIL_PAGE: &str = r##"<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<title>CustomerDetail</title>
</svelte:head>



<dl>
	
	<dt>name</dt>
	<dd>{data.name</dd>
	
	<dt>email</dt>
	<dd>{data.email</dd>
	
	<dt>phone</dt>
	<dd>{data.phone</dd>
	
</dl>



"##;

pub const SPECLESS_CUSTOMERDETAIL_LOAD: &str = r##"import type { PageLoad } from './$types';

export const load: PageLoad = async ({ params, fetch }) => {


	const response = await fetch(`/api/v1/customer/${params.id}`);
	const item = await response.json();

	return { item };




	return {};
};
"##;

pub const SPECLESS_ROUTES_TS: &str = r##"// Generated by codegraph IFML generator.
// DO NOT EDIT.

export interface RouteDefinition {
	name: string;
	route: string;
	label: string;
	isLandmark: boolean;
	isModal: boolean;
	params: string[];
}

export const routeMap: Record<string, RouteDefinition> = {

	'CustomerDetail': {
		name: 'CustomerDetail',
		route: '/customer-detail',
		label: 'CustomerDetail',
		isLandmark: false,
		isModal: false,
		params: [],
	},

	'CustomerList': {
		name: 'CustomerList',
		route: '/customer-list',
		label: 'Customer Management',
		isLandmark: true,
		isModal: false,
		params: [],
	},

};

export interface NavLink {
	from: string;
	to: string;
	event: string;
	label: string;
}

export const navigationLinks: NavLink[] = [

	{ from: 'grid', to: 'CustomerDetail', event: 'comp_grid_select', label: 'comp_grid_select' },

];

export function resolveRoute(routeName: string, params?: Record<string, string>): string {
	const def = routeMap[routeName];
	if (!def) throw new Error(`Unknown route: ${routeName}`);
	let path = def.route;
	if (params) {
		for (const [key, value] of Object.entries(params)) {
			path = path.replace(`:${key}`, encodeURIComponent(value));
		}
	}
	return path;
}
"##;

pub const SPECLESS_ROUTE_HELPERS: &str = r##"// Generated by codegraph IFML generator.
// DO NOT EDIT.

import { resolveRoute } from './routes';

/**
 * Type-safe navigation helper.
 * Call with route name and optional path params.
 */
export function navigate(routeName: string, params?: Record<string, string>): string {
  return resolveRoute(routeName, params);
}

/**
 * Build a URL path with query string.
 */
export function buildUrl(routeName: string, params?: Record<string, string>, query?: Record<string, string>): string {
  let path = resolveRoute(routeName, params);
  if (query) {
    const qs = new URLSearchParams(query).toString();
    if (qs) path += '?' + qs;
  }
  return path;
}
"##;
