//! Byte-exact expected outputs for the spec-less IFML svelte fixture.
//! Captured from the behavior-wired templates: events render as goto
//! handlers, load functions resolve API paths from the ingested API model
//! (pagination + error handling included), and the malformed `{item.x`
//! markup is fixed. The templates must reproduce these files verbatim when
//! no component specs or mappings are present.

pub const SPECLESS_CUSTOMERLIST_PAGE: &str = r##"<script lang="ts">
	import type { PageData } from './$types';
	import { goto } from '$app/navigation';

	let { data, params }: { data: PageData; params: Record<string, string> } = $props();

	function comp_grid_select(row: Record<string, unknown>) {
		goto(`/customerdetail?customerId=${row.id}`);
	}
</script>

<svelte:head>
	<title>Customer Management</title>
</svelte:head>

<h1>Customer Management</h1>
<table>
	<thead>
		<tr>
		
			<th>name</th>
		
			<th>email</th>
		
			<th>phone</th>
		
			<th>status</th>
		
		</tr>
	</thead>
	<tbody>
		{#each data.items as item}
			<tr onclick={() => comp_grid_select(item)}>
			
				<td>{item.name}</td>
			
				<td>{item.email}</td>
			
				<td>{item.phone}</td>
			
				<td>{item.status}</td>
			
			</tr>
		{/each}
	</tbody>
</table>



"##;

pub const SPECLESS_CUSTOMERLIST_LOAD: &str = r##"import type { PageLoad } from './$types';

import { error } from '@sveltejs/kit';

export const load: PageLoad = async ({ params, url, fetch }) => {
	const result: Record<string, unknown> = {};

	const gridResponse = await fetch(`/api/v1/sales/customer?page=${url.searchParams.get('page') ?? '0'}&page_size=${url.searchParams.get('page_size') ?? '20'}`);
	if (!gridResponse.ok) {
		error(gridResponse.status, 'Failed to load customer');
	}
	const gridData = await gridResponse.json();
	result.items = Array.isArray(gridData) ? gridData : gridData.data ?? [];

	return result;
};
"##;

pub const SPECLESS_CUSTOMERDETAIL_PAGE: &str = r##"<script lang="ts">
	import type { PageData } from './$types';

	let { data, params }: { data: PageData; params: Record<string, string> } = $props();
</script>

<svelte:head>
	<title>CustomerDetail</title>
</svelte:head>

<dl>
	
	<dt>name</dt>
	<dd>{data.name}</dd>
	
	<dt>email</dt>
	<dd>{data.email}</dd>
	
	<dt>phone</dt>
	<dd>{data.phone}</dd>
	
</dl>



"##;

pub const SPECLESS_CUSTOMERDETAIL_LOAD: &str = r##"import type { PageLoad } from './$types';

import { error } from '@sveltejs/kit';

export const load: PageLoad = async ({ params, url, fetch }) => {
	const result: Record<string, unknown> = {};

	const customerId = url.searchParams.get('customerId') ?? params.customerId;
	if (customerId) {
		const infoResponse = await fetch(`/api/v1/sales/customer/${ customerId }`);
		if (!infoResponse.ok) {
			error(infoResponse.status, 'Failed to load customer');
		}
		result.item = await infoResponse.json();
	}

	return result;
};
"##;

pub const SPECLESS_ROUTES_TS: &str = r##"// Generated by codegraph IFML generator.
// DO NOT EDIT.

export interface RouteDefinition {
	name: string;
	route: string;
	label: string;
	isLandmark: boolean;
	isModal: boolean;
	params: string[];
}

export const routeMap: Record<string, RouteDefinition> = {

	'CustomerDetail': {
		name: 'CustomerDetail',
		route: '/customerdetail',
		label: 'CustomerDetail',
		isLandmark: false,
		isModal: false,
		params: ['customerId'],
	},

	'CustomerList': {
		name: 'CustomerList',
		route: '/customerlist',
		label: 'Customer Management',
		isLandmark: true,
		isModal: false,
		params: [],
	},

};

export interface NavLink {
	from: string;
	to: string;
	event: string;
	label: string;
}

export const navigationLinks: NavLink[] = [

	{ from: 'CustomerList', to: 'CustomerDetail', event: 'comp_grid_select', label: 'comp_grid_select' },

];

export function resolveRoute(routeName: string, params?: Record<string, string>): string {
	const def = routeMap[routeName];
	if (!def) throw new Error(`Unknown route: ${routeName}`);
	let path = def.route;
	if (params) {
		for (const [key, value] of Object.entries(params)) {
			path = path.replace(`:${key}`, encodeURIComponent(value));
		}
	}
	return path;
}
"##;

pub const SPECLESS_ROUTE_HELPERS: &str = r##"// Generated by codegraph IFML generator.
// DO NOT EDIT.

import { resolveRoute } from './routes';

/**
 * Type-safe navigation helper.
 * Call with route name and optional path params.
 */
export function navigate(routeName: string, params?: Record<string, string>): string {
  return resolveRoute(routeName, params);
}

/**
 * Build a URL path with query string.
 */
export function buildUrl(routeName: string, params?: Record<string, string>, query?: Record<string, string>): string {
  let path = resolveRoute(routeName, params);
  if (query) {
    const qs = new URLSearchParams(query).toString();
    if (qs) path += '?' + qs;
  }
  return path;
}
"##;
