//! Response DTO for DistributionBase.
//! Re-exports from domain_types — single source of truth for DTO definitions.
//! Generated by codegraph. DO NOT EDIT.

pub use domain_types::common::distribution_base::DistributionBaseResponse;


/// Response wrapper that includes HAL-style `_links` for HATEOAS discoverability.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
pub struct DistributionBaseLinkedResponse {
    /// The entity data.
    #[serde(flatten)]
    pub data: DistributionBaseResponse,

    /// HAL-style hypermedia links.
    #[serde(rename = "_links")]
    pub links: crate::api::links::Links,
}

impl DistributionBaseLinkedResponse {
    /// Wrap a response with self-link for a root entity.
    pub fn root(data: DistributionBaseResponse, domain: &str, path_segment: &str) -> Self {
        let self_link = format!("/api/{}/{}/{}", domain, path_segment, data.id);
        Self {
            data,
            links: crate::api::links::Links::root(self_link),
        }
    }

    pub fn with_child(mut self, rel: &str, href: String) -> Self {
        self.links = self.links.with_child(rel, href);
        self
    }

    pub fn with_related(mut self, rel: &str, href: String) -> Self {
        self.links = self.links.with_related(rel, href);
        self
    }

    /// Wrap a response with self-link and parent-link for a child entity.
    pub fn child(
        data: DistributionBaseResponse,
        domain: &str,
        parent_path_segment: &str,
        parent_id: uuid::Uuid,
        path_segment: &str,
    ) -> Self {
        let self_link = format!(
            "/api/{}/{}/{}/{}/{}",
            domain, parent_path_segment, parent_id, path_segment, data.id,
        );
        let parent_link = format!("/api/{}/{}/{}", domain, parent_path_segment, parent_id);
        Self {
            data,
            links: crate::api::links::Links::child(self_link, parent_link),
        }
    }
}
