//! CQRS command handlers for PublicEvent.
//! Generated by codegraph. DO NOT EDIT.

use std::sync::Arc;


use sea_orm::{ConnectionTrait, DatabaseBackend, DatabaseConnection, Statement, TransactionTrait};

use uuid::Uuid;

use super::repository::PublicEventRepository;

use super::dto_create::CreatePublicEventRequest;


use super::dto_update::UpdatePublicEventRequest;


use super::super::errors::EventsError;

/// Set API key + org session variables within a transaction so Postgres RLS policies
/// can enforce tenant isolation and scope checks. Uses `set_config(..., true)` which
/// is equivalent to `SET LOCAL` but supports parameterised values (no SQL injection).

async fn set_rls_session_vars(
    tx: &impl ConnectionTrait,
    api_key_id: Uuid,
    organization_id: Uuid,
    correlation_id: Uuid,
    user_id: Uuid,
) -> Result<(), EventsError> {
    tx.execute(Statement::from_sql_and_values(
        DatabaseBackend::Postgres,
        "SELECT set_config('app.current_api_key', $1, true), \
                set_config('app.organization_id', $2, true), \
                set_config('app.correlation_id', $3, true), \
                set_config('app.user_id', $4, true)",
        [
            api_key_id.to_string().into(),
            organization_id.to_string().into(),
            correlation_id.to_string().into(),
            user_id.to_string().into(),
        ],
    )).await?;
    tx.execute(Statement::from_string(
        DatabaseBackend::Postgres,
        "SET LOCAL ROLE app_user".to_string(),
    )).await?;
    Ok(())
}


#[derive(Clone)]
pub struct PublicEventCommandHandler {

    repo: Arc<dyn PublicEventRepository<sea_orm::DatabaseTransaction>>,

    db: DatabaseConnection,

}

impl PublicEventCommandHandler {
    pub fn new(

        repo: Arc<dyn PublicEventRepository<sea_orm::DatabaseTransaction>>,

        db: DatabaseConnection,

    ) -> Self {
        Self { repo, db }
    }



    pub async fn create(&self, cmd: CreatePublicEventRequest, source: domain_types::SourceContext, correlation_id: Uuid, api_key_id: Uuid, organization_id: Uuid, user_id: Uuid) -> Result<Uuid, EventsError> {
        self.create_single_in_tx(cmd, &source, correlation_id, api_key_id, organization_id, user_id).await
    }


    /// Bulk-create multiple PublicEvent records with partial-success semantics.
    /// Each item is processed in its own transaction. Returns per-item results.
    pub async fn bulk_create(
        &self,
        items: Vec<CreatePublicEventRequest>,

        source: domain_types::SourceContext,
        correlation_id: Uuid,
        api_key_id: Uuid,
        organization_id: Uuid,
        user_id: Uuid,
    ) -> Vec<Result<Uuid, crate::error::BulkItemError>> {
        

        let mut results: Vec<Result<Uuid, crate::error::BulkItemError>> = Vec::with_capacity(items.len());

        for (idx, item) in items.into_iter().enumerate() {
            // Validate each item with garde
            if let Err(report) = garde::Validate::validate(&item) {
                let msg = report.into_inner()
                    .into_iter()
                    .map(|(path, error)| format!("{}: {}", path, error.message()))
                    .collect::<Vec<_>>()
                    .join("; ");
                results.push(Err(crate::error::BulkItemError {
                    index: idx,
                    error: format!("Validation failed: {msg}"),
                }));
                continue;
            }


            match self.create_single_in_tx(item, &source, correlation_id, api_key_id, organization_id, user_id).await {

                Ok(id) => results.push(Ok(id)),
                Err(e) => results.push(Err(crate::error::BulkItemError {
                    index: idx,
                    error: e.to_string(),
                })),
            }
        }

        

        results
    }

    /// Internal: create a single entity in its own transaction.
    /// Used by `bulk_create` to isolate per-item failures.
    async fn create_single_in_tx(
        &self,
        cmd: CreatePublicEventRequest,

        source: &domain_types::SourceContext,
        correlation_id: Uuid,
        api_key_id: Uuid,
        organization_id: Uuid,
        user_id: Uuid,
    ) -> Result<Uuid, EventsError> {

        let tx = self.db.begin().await?;

        set_rls_session_vars(&tx, api_key_id, organization_id, correlation_id, user_id).await?;

        


        let id = self.repo.create(&tx, cmd).await
            .map_err(|e| {
                if e.to_string().contains("duplicate key") || e.to_string().contains("UNIQUE constraint") {
                    EventsError::Conflict
                } else if e.to_string().contains("not found") {
                    EventsError::NotFound
                } else {
                    EventsError::InternalError(e.to_string())
                }
            })?;


        

        tx.commit().await?;
        tracing::info!(entity_id = %id, event = "created", "PublicEvent");

        

        Ok(id)
    }



    pub async fn update(&self, id: Uuid, cmd: UpdatePublicEventRequest, source: domain_types::SourceContext, correlation_id: Uuid, api_key_id: Uuid, organization_id: Uuid, user_id: Uuid) -> Result<(), EventsError> {

        let tx = self.db.begin().await?;

        set_rls_session_vars(&tx, api_key_id, organization_id, correlation_id, user_id).await?;

        

        self.repo.update(&tx, id, cmd).await
            .map_err(|e| {
                if e.to_string().contains("not found") {
                    EventsError::NotFound
                } else {
                    EventsError::InternalError(e.to_string())
                }
            })?;

        

        tx.commit().await?;
        tracing::info!(entity_id = %id, event = "updated", "PublicEvent");

        

        Ok(())
    }



    pub async fn delete(&self, id: Uuid, source: domain_types::SourceContext, correlation_id: Uuid, api_key_id: Uuid, organization_id: Uuid, user_id: Uuid) -> Result<(), EventsError> {

        let tx = self.db.begin().await?;

        set_rls_session_vars(&tx, api_key_id, organization_id, correlation_id, user_id).await?;

        

        self.repo.delete(&tx, id).await
            .map_err(|e| {
                if e.to_string().contains("not found") {
                    EventsError::NotFound
                } else {
                    EventsError::InternalError(e.to_string())
                }
            })?;

        

        tx.commit().await?;
        tracing::info!(entity_id = %id, event = "deleted", "PublicEvent");

        

        Ok(())
    }

}
