//! Query service for AdvancedVoiceServicesOperationsOutcome. Generated by codegraph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::AdvancedVoiceServicesOperationsOutcomeResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait AdvancedVoiceServicesOperationsOutcomeQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<AdvancedVoiceServicesOperationsOutcomeResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<AdvancedVoiceServicesOperationsOutcomeResponse>, QueryError>;
}
