// Generated by codegraph — DO NOT EDIT.
// Test data factory for EffectiveDate.

use std::collections::HashMap;
use serde_json::{json, Value};

pub struct EffectiveDateFactory;

impl EffectiveDateFactory {
    pub fn default_data() -> HashMap<&'static str, Value> {
        let mut m: HashMap<&'static str, Value> = HashMap::new();


        m.insert("valid_from", json!("2025-01-15"));



        m.insert("valid_to", json!("2025-01-15"));


        m
    }
}
