// Generated by codegraph — DO NOT EDIT.
// Test data factory for GenderCodeList.

use std::collections::HashMap;
use serde_json::{json, Value};

pub struct GenderCodeListFactory;

impl GenderCodeListFactory {
    pub fn default_data() -> HashMap<&'static str, Value> {
        let mut m: HashMap<&'static str, Value> = HashMap::new();

        m
    }
}
