//! Response DTO for Branch.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Addresstypevalues;

/// Response body for Branch.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct BranchResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub branch_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub branch_legal_entity_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub branch_name_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub branch_address: Option<BranchAddressResponse>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct BranchAddressResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_type: Option<Addresstypevalues>,
}
