// Generated by hr-graph. DO NOT EDIT.
// Auth guard for (app) route group — redirects unauthenticated users to /login.

import { redirect } from '@sveltejs/kit';
import type { LayoutServerLoad } from './$types';
import { createSupabaseClient } from '$lib/supabase';

export const load: LayoutServerLoad = async ({ fetch, cookies }) => {
	const supabase = createSupabaseClient({
		fetch,
		cookies: {
			getAll() {
				return cookies.getAll().map(({ name, value }) => ({ name, value }));
			},
			setAll(cookiesToSet) {
				for (const { name, value, options } of cookiesToSet) {
					cookies.set(name, value, { path: '/', ...options });
				}
			},
		},
	});
	const { data: { session } } = await supabase.auth.getSession();

	if (!session) {
		redirect(303, '/login');
	}

	// Resolve org membership via Basejump (best-effort — don't 500 if RPC is slow under load)
	let accounts: { personal_account: boolean; account_id: string; name: string; slug: string; account_role: 'owner' | 'member' }[] | null = null;
	try {
		const { data, error } = await supabase.rpc('get_accounts');
		if (error) {
			console.error('[layout] get_accounts failed:', (error as { message?: string }).message ?? String(error));
		} else {
			accounts = data;
		}
	} catch (e) {
		console.error('[layout] get_accounts threw:', e);
	}
	const org = accounts?.find((a: { personal_account: boolean }) => !a.personal_account);

	return {
		session,
		organization: org ? { id: org.account_id, name: org.name, slug: org.slug, role: org.account_role } : null,
	};
};
