//! Application entry point.
//! Generated by codegraph. DO NOT EDIT.

use std::net::SocketAddr;
use std::sync::Arc;

use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::EnvFilter;
use utoipa::OpenApi;
use utoipa_swagger_ui::{SwaggerUi, Url};
use tower_http::cors::{Any, CorsLayer};
use tower_http::limit::RequestBodyLimitLayer;
use tower_http::set_header::SetResponseHeaderLayer;
use axum::http::HeaderValue;
use shadow_rs::shadow;
shadow!(build);

mod api;
mod app_state;
mod codelist;
mod domain;
mod entity;
mod error;
mod integrations;
mod metrics_middleware;
mod middleware;
mod qs_query;

mod webhook_api;
mod webhook_dispatch;
mod webhook_router;



static START_TIME: std::sync::OnceLock<std::time::Instant> = std::sync::OnceLock::new();

/// Build and version metadata exposed at `GET /version`.
#[derive(serde::Serialize, utoipa::ToSchema)]
pub struct VersionInfo {
    pub version: &'static str,
    pub git_commit: &'static str,
    pub git_branch: &'static str,
    pub git_dirty: bool,
    pub build_time: &'static str,
    pub rust_version: &'static str,
    pub rust_channel: &'static str,
    pub cargo_version: &'static str,
    pub build_os: &'static str,
}

// Type imports inlined in AppState construction to avoid cross-domain name collisions.

fn init_tracing() -> Option<opentelemetry_sdk::trace::SdkTracerProvider> {
    let fmt_layer = tracing_subscriber::fmt::layer().json();
    let filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::new("info"));

    let registry = tracing_subscriber::registry()
        .with(filter)
        .with(fmt_layer);

    if std::env::var("OTEL_EXPORTER_OTLP_ENDPOINT").is_ok() {
        use opentelemetry::trace::TracerProvider;
        match opentelemetry_otlp::SpanExporter::builder()
            .with_tonic()
            .build()
        {
            Ok(exporter) => {
                let provider = opentelemetry_sdk::trace::SdkTracerProvider::builder()
                    .with_batch_exporter(exporter)
                    .build();
                let tracer = provider.tracer("app");
                opentelemetry::global::set_tracer_provider(provider.clone());
                let otel_layer = tracing_opentelemetry::layer().with_tracer(tracer);
                registry.with(otel_layer).init();
                Some(provider)
            }
            Err(e) => {
                eprintln!("Failed to initialize OTel exporter (OTEL_EXPORTER_OTLP_ENDPOINT is set but exporter creation failed): {e}");
                registry.init();
                None
            }
        }
    } else {
        registry.init();
        None
    }
}

#[utoipa::path(
    get,
    path = "/version",
    tag = "System",
    responses(
        (status = 200, description = "Build and version information", body = VersionInfo)
    )
)]
async fn version() -> axum::Json<VersionInfo> {
    axum::Json(VersionInfo {
        version: build::PKG_VERSION,
        git_commit: build::SHORT_COMMIT,
        git_branch: build::BRANCH,
        git_dirty: !build::GIT_CLEAN,
        build_time: build::BUILD_TIME_3339,
        rust_version: build::RUST_VERSION,
        rust_channel: build::RUST_CHANNEL,
        cargo_version: build::CARGO_VERSION,
        build_os: build::BUILD_OS,
    })
}

async fn health(
    axum::extract::State(state): axum::extract::State<app_state::AppState>,
) -> axum::Json<serde_json::Value> {
    let db_ok = sea_orm::ConnectionTrait::execute(
        &state.db,
        sea_orm::Statement::from_string(
            sea_orm::DatabaseBackend::Postgres,
            "SELECT 1",
        ),
    )
    .await
    .is_ok();
    axum::Json(serde_json::json!({
        "status": if db_ok { "ok" } else { "degraded" },
        "db": if db_ok { "connected" } else { "unreachable" },
    }))
}

async fn health_ready(
    axum::extract::State(state): axum::extract::State<app_state::AppState>,
) -> axum::Json<serde_json::Value> {
    let db_ok = sea_orm::ConnectionTrait::execute(
        &state.db,
        sea_orm::Statement::from_string(
            sea_orm::DatabaseBackend::Postgres,
            "SELECT 1",
        ),
    )
    .await
    .is_ok();

    // Check workflow definitions exist (informational, not a failure)
    let workflow_status = async {
        use sea_orm::{FromQueryResult, JsonValue};
        let result = JsonValue::find_by_statement(sea_orm::Statement::from_string(
            sea_orm::DatabaseBackend::Postgres,
            "SELECT count(*)::int AS cnt FROM platform.workflow_definition",
        ))
        .one(&state.db)
        .await
        .ok()
        .flatten();
        match result {
            Some(val) => {
                let cnt = val.get("cnt").and_then(|v| v.as_i64()).unwrap_or(0);
                if cnt > 0 { "ok" } else { "no_definitions" }
            }
            None => "no_definitions",
        }
    }.await;

    // Check RLS session vars can be set and read back within a transaction
    let rls_ok = async {
        use sea_orm::TransactionTrait;
        let tx = state.db.begin().await.ok()?;
        sea_orm::ConnectionTrait::execute(
            &tx,
            sea_orm::Statement::from_string(
                sea_orm::DatabaseBackend::Postgres,
                "SELECT set_config('app.current_api_key', 'health-check', true)",
            ),
        ).await.ok()?;
        // Read back to verify round-trip
        let readback = sea_orm::ConnectionTrait::query_one(
            &tx,
            sea_orm::Statement::from_string(
                sea_orm::DatabaseBackend::Postgres,
                "SELECT current_setting('app.current_api_key') AS val",
            ),
        ).await.ok()?;
        let val: String = readback?.try_get("", "val").ok()?;
        tx.commit().await.ok()?;
        if val == "health-check" { Some(()) } else { None }
    }.await.is_some();

    let uptime_secs = START_TIME.get().map(|s| s.elapsed().as_secs()).unwrap_or(0);

    axum::Json(serde_json::json!({
        "status": if db_ok && rls_ok { "ok" } else { "degraded" },
        "db": if db_ok { "connected" } else { "unreachable" },
        "workflow": workflow_status,
        "rls": if rls_ok { "ok" } else { "error" },
        "uptime_seconds": uptime_secs,
    }))
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let otel_provider = init_tracing();
    START_TIME.get_or_init(std::time::Instant::now);

    let metrics_handle = metrics_exporter_prometheus::PrometheusBuilder::new()
        .install_recorder()
        .map_err(|e| format!("Failed to install Prometheus metrics recorder: {e}"))?;

    let app_name = std::env::var("APP_NAME").unwrap_or_else(|_| "app".to_string());

    let db_url = std::env::var("DATABASE_URL").map_err(|_| {
        "DATABASE_URL environment variable is required. Set it to your Postgres connection string, e.g. postgres://user:pass@host:5432/dbname"
    })?;

    let db = sea_orm::Database::connect(&db_url).await?;

    let state = app_state::AppState {


        common_code_commands: crate::domain::common::code::command::CodeCommandHandler::new(
            Arc::new(crate::domain::common::code::repository_impl::CodeRepositoryImpl),
            db.clone(),
        ),
        common_code_queries: crate::domain::common::code::query::CodeQueryHandler::new(
            Arc::new(crate::domain::common::code::repository_impl::CodeRepositoryImpl),
            db.clone(),
        ),

        common_currency_code_list_commands: crate::domain::common::currency_code_list::command::CurrencyCodeListCommandHandler::new(
            Arc::new(crate::domain::common::currency_code_list::repository_impl::CurrencyCodeListRepositoryImpl),
            db.clone(),
        ),
        common_currency_code_list_queries: crate::domain::common::currency_code_list::query::CurrencyCodeListQueryHandler::new(
            Arc::new(crate::domain::common::currency_code_list::repository_impl::CurrencyCodeListRepositoryImpl),
            db.clone(),
        ),

        common_date_commands: crate::domain::common::date::command::DateCommandHandler::new(
            Arc::new(crate::domain::common::date::repository_impl::DateRepositoryImpl),
            db.clone(),
        ),
        common_date_queries: crate::domain::common::date::query::DateQueryHandler::new(
            Arc::new(crate::domain::common::date::repository_impl::DateRepositoryImpl),
            db.clone(),
        ),

        common_distribution_base_commands: crate::domain::common::distribution_base::command::DistributionBaseCommandHandler::new(
            Arc::new(crate::domain::common::distribution_base::repository_impl::DistributionBaseRepositoryImpl),
            db.clone(),
        ),
        common_distribution_base_queries: crate::domain::common::distribution_base::query::DistributionBaseQueryHandler::new(
            Arc::new(crate::domain::common::distribution_base::repository_impl::DistributionBaseRepositoryImpl),
            db.clone(),
        ),

        common_effective_date_commands: crate::domain::common::effective_date::command::EffectiveDateCommandHandler::new(
            Arc::new(crate::domain::common::effective_date::repository_impl::EffectiveDateRepositoryImpl),
            db.clone(),
        ),
        common_effective_date_queries: crate::domain::common::effective_date::query::EffectiveDateQueryHandler::new(
            Arc::new(crate::domain::common::effective_date::repository_impl::EffectiveDateRepositoryImpl),
            db.clone(),
        ),

        common_formatted_date_time_commands: crate::domain::common::formatted_date_time::command::FormattedDateTimeCommandHandler::new(
            Arc::new(crate::domain::common::formatted_date_time::repository_impl::FormattedDateTimeRepositoryImpl),
            db.clone(),
        ),
        common_formatted_date_time_queries: crate::domain::common::formatted_date_time::query::FormattedDateTimeQueryHandler::new(
            Arc::new(crate::domain::common::formatted_date_time::repository_impl::FormattedDateTimeRepositoryImpl),
            db.clone(),
        ),

        common_gender_code_list_commands: crate::domain::common::gender_code_list::command::GenderCodeListCommandHandler::new(
            Arc::new(crate::domain::common::gender_code_list::repository_impl::GenderCodeListRepositoryImpl),
            db.clone(),
        ),
        common_gender_code_list_queries: crate::domain::common::gender_code_list::query::GenderCodeListQueryHandler::new(
            Arc::new(crate::domain::common::gender_code_list::repository_impl::GenderCodeListRepositoryImpl),
            db.clone(),
        ),

        common_identifier_commands: crate::domain::common::identifier::command::IdentifierCommandHandler::new(
            Arc::new(crate::domain::common::identifier::repository_impl::IdentifierRepositoryImpl),
            db.clone(),
        ),
        common_identifier_queries: crate::domain::common::identifier::query::IdentifierQueryHandler::new(
            Arc::new(crate::domain::common::identifier::repository_impl::IdentifierRepositoryImpl),
            db.clone(),
        ),

        common_name_commands: crate::domain::common::name::command::NameCommandHandler::new(
            Arc::new(crate::domain::common::name::repository_impl::NameRepositoryImpl),
            db.clone(),
        ),
        common_name_queries: crate::domain::common::name::query::NameQueryHandler::new(
            Arc::new(crate::domain::common::name::repository_impl::NameRepositoryImpl),
            db.clone(),
        ),

        common_person_base_commands: crate::domain::common::person_base::command::PersonBaseCommandHandler::new(
            Arc::new(crate::domain::common::person_base::repository_impl::PersonBaseRepositoryImpl),
            db.clone(),
        ),
        common_person_base_queries: crate::domain::common::person_base::query::PersonBaseQueryHandler::new(
            Arc::new(crate::domain::common::person_base::repository_impl::PersonBaseRepositoryImpl),
            db.clone(),
        ),

        common_position_schedule_type_code_list_commands: crate::domain::common::position_schedule_type_code_list::command::PositionScheduleTypeCodeListCommandHandler::new(
            Arc::new(crate::domain::common::position_schedule_type_code_list::repository_impl::PositionScheduleTypeCodeListRepositoryImpl),
            db.clone(),
        ),
        common_position_schedule_type_code_list_queries: crate::domain::common::position_schedule_type_code_list::query::PositionScheduleTypeCodeListQueryHandler::new(
            Arc::new(crate::domain::common::position_schedule_type_code_list::repository_impl::PositionScheduleTypeCodeListRepositoryImpl),
            db.clone(),
        ),

        common_string_type_array_commands: crate::domain::common::string_type_array::command::StringTypeArrayCommandHandler::new(
            Arc::new(crate::domain::common::string_type_array::repository_impl::StringTypeArrayRepositoryImpl),
            db.clone(),
        ),
        common_string_type_array_queries: crate::domain::common::string_type_array::query::StringTypeArrayQueryHandler::new(
            Arc::new(crate::domain::common::string_type_array::repository_impl::StringTypeArrayRepositoryImpl),
            db.clone(),
        ),

        common_amount_commands: crate::domain::common::amount::command::AmountCommandHandler::new(
            Arc::new(crate::domain::common::amount::repository_impl::AmountRepositoryImpl),
            db.clone(),
        ),
        common_amount_queries: crate::domain::common::amount::query::AmountQueryHandler::new(
            Arc::new(crate::domain::common::amount::repository_impl::AmountRepositoryImpl),
            db.clone(),
        ),

        common_process_history_item_commands: crate::domain::common::process_history_item::command::ProcessHistoryItemCommandHandler::new(
            Arc::new(crate::domain::common::process_history_item::repository_impl::ProcessHistoryItemRepositoryImpl),
            db.clone(),
        ),
        common_process_history_item_queries: crate::domain::common::process_history_item::query::ProcessHistoryItemQueryHandler::new(
            Arc::new(crate::domain::common::process_history_item::repository_impl::ProcessHistoryItemRepositoryImpl),
            db.clone(),
        ),

        common_process_history_commands: crate::domain::common::process_history::command::ProcessHistoryCommandHandler::new(
            Arc::new(crate::domain::common::process_history::repository_impl::ProcessHistoryRepositoryImpl),
            db.clone(),
        ),
        common_process_history_queries: crate::domain::common::process_history::query::ProcessHistoryQueryHandler::new(
            Arc::new(crate::domain::common::process_history::repository_impl::ProcessHistoryRepositoryImpl),
            db.clone(),
        ),



        compensation_pay_run_commands: crate::domain::compensation::pay_run::command::PayRunCommandHandler::new(
            Arc::new(crate::domain::compensation::pay_run::repository_impl::PayRunRepositoryImpl),
            db.clone(),
        ),
        compensation_pay_run_queries: crate::domain::compensation::pay_run::query::PayRunQueryHandler::new(
            Arc::new(crate::domain::compensation::pay_run::repository_impl::PayRunRepositoryImpl),
            db.clone(),
        ),



        recruiting_application_commands: crate::domain::recruiting::application::command::ApplicationCommandHandler::new(
            Arc::new(crate::domain::recruiting::application::repository_impl::ApplicationRepositoryImpl),
            db.clone(),
        ),
        recruiting_application_queries: crate::domain::recruiting::application::query::ApplicationQueryHandler::new(
            Arc::new(crate::domain::recruiting::application::repository_impl::ApplicationRepositoryImpl),
            db.clone(),
        ),

        recruiting_candidate_commands: crate::domain::recruiting::candidate::command::CandidateCommandHandler::new(
            Arc::new(crate::domain::recruiting::candidate::repository_impl::CandidateRepositoryImpl),
            db.clone(),
        ),
        recruiting_candidate_queries: crate::domain::recruiting::candidate::query::CandidateQueryHandler::new(
            Arc::new(crate::domain::recruiting::candidate::repository_impl::CandidateRepositoryImpl),
            db.clone(),
        ),


        db: db.clone(),
        jwt_secret: std::env::var("SUPABASE_JWT_SECRET").map_err(|_| {
            "SUPABASE_JWT_SECRET environment variable is required. Set it to your Supabase project JWT secret"
        })?,
        workflow_service: {
            let svc = std::sync::Arc::new(
                codegraph_workflow::engine::SeaOrmWorkflowService::new(db.clone())
            );
            svc
        },
    };

    // Timer service with graceful shutdown
    let (shutdown_tx, shutdown_rx) = tokio::sync::watch::channel(());
    let timer_service = codegraph_workflow::timer::TimerService::new(
        db.clone(),
        state.workflow_service.clone(),
        std::time::Duration::from_secs(30),
    );
    tokio::spawn(async move { timer_service.run(shutdown_rx).await });


    // Webhook dispatch worker
    let webhook_dispatcher = crate::webhook_dispatch::WebhookDispatcher::new(db.clone())?;
    tokio::spawn(async move { webhook_dispatcher.run().await });


    let shutdown_signal = async move {
        tokio::signal::ctrl_c().await.ok();
        tracing::info!("Shutdown signal received");
        let _ = shutdown_tx.send(());
    };

    // CORS configuration
    let cors = match std::env::var("CORS_ALLOWED_ORIGINS").as_deref() {
        Ok("*") => CorsLayer::very_permissive(),
        Ok(origins) => {
            let origins: Vec<HeaderValue> = origins
                .split(',')
                .filter_map(|o| o.trim().parse().ok())
                .collect();
            CorsLayer::new()
                .allow_origin(origins)
                .allow_methods(Any)
                .allow_headers(Any)
        }
        Err(_) => {
            tracing::warn!("CORS_ORIGINS not set — CORS disabled (no cross-origin requests allowed). Set CORS_ORIGINS=* to allow all.");
            CorsLayer::new()
        }
    };

    let api_routes = axum::Router::new()


        .nest("/common", api::common::router::router())



        .nest("/compensation", api::compensation::router::router())



        .nest("/recruiting", api::recruiting::router::router())


        .route("/integrations", axum::routing::get(integrations::get_integrations))


        .nest("/webhooks", crate::webhook_router::webhook_routes())

        .layer(axum::middleware::from_fn_with_state(state.clone(), crate::middleware::auth_middleware));

    let app = axum::Router::new()
        .route("/version", axum::routing::get(version))
        .route("/health", axum::routing::get(health))
        .route("/health/ready", axum::routing::get(health_ready))
        .route("/metrics", axum::routing::get(move || std::future::ready(metrics_handle.render())))
        .nest("/api", api_routes)
        .route("/api-catalog.json", axum::routing::get(api::openapi::catalog::api_catalog))
        .merge(
            SwaggerUi::new("/swagger-ui")
                .urls(vec![
                    (Url::new("All", "/api-docs/openapi.json"), api::openapi::all::AllApiDoc::openapi()),


                    (Url::new("Common", "/api-docs/common/openapi.json"), api::openapi::common::CommonApiDoc::openapi()),



                    (Url::new("Compensation", "/api-docs/compensation/openapi.json"), api::openapi::compensation::CompensationApiDoc::openapi()),



                    (Url::new("Recruiting", "/api-docs/recruiting/openapi.json"), api::openapi::recruiting::RecruitingApiDoc::openapi()),


                ])
        )
        .with_state(state);

    // Merge custom extension routes (Router<()>) after .with_state()


    let app = app
        .layer(axum::middleware::from_fn(metrics_middleware::track_metrics))
        .layer(cors)
        .layer(RequestBodyLimitLayer::new(10 * 1024 * 1024)) // 10MB
        .layer(SetResponseHeaderLayer::overriding(
            axum::http::header::HeaderName::from_static("x-content-type-options"),
            HeaderValue::from_static("nosniff"),
        ))
        .layer(SetResponseHeaderLayer::overriding(
            axum::http::header::HeaderName::from_static("x-frame-options"),
            HeaderValue::from_static("DENY"),
        ));

    // HSTS — only when explicitly enabled (production with TLS termination)
    let app = if std::env::var("HSTS_ENABLED").as_deref() == Ok("true") {
        app.layer(SetResponseHeaderLayer::overriding(
            axum::http::header::HeaderName::from_static("strict-transport-security"),
            HeaderValue::from_static("max-age=31536000; includeSubDomains"),
        ))
    } else {
        app
    };

    let addr = SocketAddr::from(([0, 0, 0, 0], 3000));
    tracing::info!(app_name = %app_name, "Swagger UI: http://0.0.0.0:3000/swagger-ui/  |  API Catalog: http://0.0.0.0:3000/api-catalog.json");
    tracing::info!("Listening on {}", addr);
    let listener = tokio::net::TcpListener::bind(addr).await?;
    axum::serve(listener, app)
        .with_graceful_shutdown(shutdown_signal)
        .await?;

    // Flush OTel traces before exit
    if let Some(provider) = otel_provider {
        if let Err(e) = provider.shutdown() {
            eprintln!("OTel shutdown error: {e}");
        }
    }

    Ok(())
}
