//! Create DTO for Servicetype.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Servicetypevalues;

/// Request body for creating a new Servicetype.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateServicetypeRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_type: Option<Servicetypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_type_name_id: Option<uuid::Uuid>,
}
