//! Create DTO for Identifier.
//! Generated by codegraph-review-gate. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Request body for creating a new Identifier.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]

pub struct CreateIdentifierRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheme_agency_id: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheme_id: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheme_version_id: Option<String>,
    #[garde(skip)]
    pub value: String,
}
