-- RLS policies for common.event_base
-- Generated by codegraph. DO NOT EDIT.
--
-- Uses get_current_org_id() which reads app.organization_id session var.
-- This is set by the Axum middleware for BOTH API key and JWT auth,
-- so one policy set works for all auth modes.

ALTER TABLE common.event_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE common.event_base FORCE ROW LEVEL SECURITY;

-- Drop all existing policies (clean slate on regeneration)
DO $$ DECLARE pol RECORD; BEGIN
  FOR pol IN SELECT policyname FROM pg_policies
    WHERE schemaname = 'common' AND tablename = 'event_base'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON common.event_base', pol.policyname);
  END LOOP;
END $$;

-- Org isolation: SELECT
CREATE POLICY "org_isolation_select" ON common.event_base
  FOR SELECT
  USING ((platform_organization_id = public.get_current_org_id()
    OR platform_organization_id = '00000000-0000-0000-0000-000000000000'::uuid));

-- Org isolation: INSERT
CREATE POLICY "org_isolation_insert" ON common.event_base
  FOR INSERT
  WITH CHECK ((platform_organization_id = public.get_current_org_id()
    OR platform_organization_id = '00000000-0000-0000-0000-000000000000'::uuid));

-- Org isolation: UPDATE
CREATE POLICY "org_isolation_update" ON common.event_base
  FOR UPDATE
  USING ((platform_organization_id = public.get_current_org_id()
    OR platform_organization_id = '00000000-0000-0000-0000-000000000000'::uuid))
  WITH CHECK ((platform_organization_id = public.get_current_org_id()
    OR platform_organization_id = '00000000-0000-0000-0000-000000000000'::uuid));

-- Org isolation: DELETE
CREATE POLICY "org_isolation_delete" ON common.event_base
  FOR DELETE
  USING ((platform_organization_id = public.get_current_org_id()
    OR platform_organization_id = '00000000-0000-0000-0000-000000000000'::uuid));


-- API key scope-aware policies
CREATE POLICY "api_key_scoped_select" ON common.event_base
  FOR SELECT TO api_key
  USING (
    public.get_api_key_org_id() IS NOT NULL
    AND ((platform_organization_id IS NULL OR platform_organization_id = public.get_api_key_org_id()))
    AND public.check_api_key_scope('event-base', id::text, 'read')
  );

CREATE POLICY "api_key_scoped_insert" ON common.event_base
  FOR INSERT TO api_key
  WITH CHECK (
    public.get_api_key_org_id() IS NOT NULL
    AND ((platform_organization_id IS NULL OR platform_organization_id = public.get_api_key_org_id()))
    AND public.check_api_key_scope('event-base', '*', 'create')
  );

CREATE POLICY "api_key_scoped_update" ON common.event_base
  FOR UPDATE TO api_key
  USING (
    public.get_api_key_org_id() IS NOT NULL
    AND ((platform_organization_id IS NULL OR platform_organization_id = public.get_api_key_org_id()))
    AND public.check_api_key_scope('event-base', id::text, 'update')
  )
  WITH CHECK (
    public.get_api_key_org_id() IS NOT NULL
    AND ((platform_organization_id IS NULL OR platform_organization_id = public.get_api_key_org_id()))
    AND public.check_api_key_scope('event-base', id::text, 'update')
  );

CREATE POLICY "api_key_scoped_delete" ON common.event_base
  FOR DELETE TO api_key
  USING (
    public.get_api_key_org_id() IS NOT NULL
    AND ((platform_organization_id IS NULL OR platform_organization_id = public.get_api_key_org_id()))
    AND public.check_api_key_scope('event-base', id::text, 'delete')
  );


-- Schema + table privileges for app_user and api_key (RLS policies only
-- filter rows; these grants enable access). Idempotent, so it's safe to
-- emit from every entity migration in a domain.
-- ALL TABLES covers child tables (created by the entity migration before
-- this file runs); ALTER DEFAULT PRIVILEGES covers tables created later.
GRANT USAGE ON SCHEMA common TO app_user, api_key;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA common TO app_user, api_key;
ALTER DEFAULT PRIVILEGES IN SCHEMA common
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user, api_key;

