-- Generated by codegraph. DO NOT EDIT.
-- Table: events.public_event

CREATE SCHEMA IF NOT EXISTS extensions;



CREATE SCHEMA IF NOT EXISTS events;

CREATE TABLE IF NOT EXISTS events.public_event (

    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,


    platform_organization_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::UUID,


    is_published BOOLEAN,


    capacity BIGINT,


    title TEXT NOT NULL,


    birth_date DATE,


    family_name TEXT NOT NULL,


    given_name TEXT NOT NULL,


    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),


    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),




    deleted_at TIMESTAMPTZ NULL,
    deleted_by UUID NULL,
    updated_by UUID NULL,
    is_demo_data BOOLEAN NOT NULL DEFAULT false

);

-- App role DML (RLS policies gate rows; this grants base table access)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE events.public_event TO app_user;




-- Child table: events.public_event_eventbasetype
CREATE TABLE IF NOT EXISTS events.public_event_eventbasetype (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    public_event_id UUID NOT NULL,

    platform_organization_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::UUID,

    capacity BIGINT,

    title TEXT NOT NULL,

    birth_date DATE,

    family_name TEXT NOT NULL,

    given_name TEXT NOT NULL,


    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE events.public_event_eventbasetype TO app_user;

ALTER TABLE events.public_event_eventbasetype ADD CONSTRAINT fk_public_event_eventbasetype_parent FOREIGN KEY (public_event_id) REFERENCES events.public_event(id) ON DELETE CASCADE;

CREATE INDEX idx_public_event_eventbasetype_parent ON events.public_event_eventbasetype(public_event_id);



COMMENT ON COLUMN events.public_event_eventbasetype.title IS $$Event title$$;


COMMENT ON COLUMN events.public_event_eventbasetype.family_name IS $$Last name$$;


COMMENT ON COLUMN events.public_event_eventbasetype.given_name IS $$First name$$;



-- Child table: events.public_event_eventbasetype_personbasetype
CREATE TABLE IF NOT EXISTS events.public_event_eventbasetype_personbasetype (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    public_event_eventbasetype_id UUID NOT NULL,

    platform_organization_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::UUID,

    birth_date DATE,

    family_name TEXT NOT NULL,

    given_name TEXT NOT NULL,


    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE events.public_event_eventbasetype_personbasetype TO app_user;

ALTER TABLE events.public_event_eventbasetype_personbasetype ADD CONSTRAINT fk_public_event_eventbasetype_personbasetype_parent FOREIGN KEY (public_event_eventbasetype_id) REFERENCES events.public_event_eventbasetype(id) ON DELETE CASCADE;

CREATE INDEX idx_public_event_eventbasetype_personbasetype_parent ON events.public_event_eventbasetype_personbasetype(public_event_eventbasetype_id);



COMMENT ON COLUMN events.public_event_eventbasetype_personbasetype.family_name IS $$Last name$$;


COMMENT ON COLUMN events.public_event_eventbasetype_personbasetype.given_name IS $$First name$$;




COMMENT ON COLUMN events.public_event.title IS $$Event title$$;


COMMENT ON COLUMN events.public_event.family_name IS $$Last name$$;


COMMENT ON COLUMN events.public_event.given_name IS $$First name$$;

