-- Domain event trigger for recruiting.application
-- Emits domain events to pgmq on INSERT/UPDATE/DELETE.
-- Generated by hr-graph. DO NOT EDIT.

DROP TRIGGER IF EXISTS trg_application_domain_event ON recruiting.application;
CREATE TRIGGER trg_application_domain_event
    AFTER INSERT OR UPDATE OR DELETE ON recruiting.application
    FOR EACH ROW
    EXECUTE FUNCTION emit_domain_event('recruiting', 'application');

