-- Domain event trigger for common.currency_code_list
-- Emits domain events to pgmq on INSERT/UPDATE/DELETE.
-- Generated by codegraph. DO NOT EDIT.

DROP TRIGGER IF EXISTS trg_currency_code_list_domain_event ON common.currency_code_list;
CREATE TRIGGER trg_currency_code_list_domain_event
    AFTER INSERT OR UPDATE OR DELETE ON common.currency_code_list
    FOR EACH ROW
    EXECUTE FUNCTION emit_domain_event('common', 'currency_code_list');

