-- Generated by codegraph. DO NOT EDIT.
-- Table: common.identifier



CREATE SCHEMA IF NOT EXISTS common;

CREATE TABLE IF NOT EXISTS common.identifier (

    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,


    platform_organization_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::UUID,


    scheme_agency_id TEXT,


    scheme_id TEXT,


    scheme_version_id TEXT,


    "value" TEXT NOT NULL,


    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),


    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),




    deleted_at TIMESTAMPTZ NULL,
    deleted_by UUID NULL,
    updated_by UUID NULL,
    is_demo_data BOOLEAN NOT NULL DEFAULT false

);




