-- Full-text search infrastructure for common.name
-- Generated by codegraph. DO NOT EDIT.


-- Add tsvector column for full-text search
ALTER TABLE common.name
    ADD COLUMN IF NOT EXISTS search_tsv TSVECTOR;

-- GIN index for fast tsquery matching
CREATE INDEX IF NOT EXISTS idx_name_search_tsv
    ON common.name
    USING GIN (search_tsv);

-- Trigger function: maintains tsvector from source columns with weights
CREATE OR REPLACE FUNCTION common.update_name_search_tsv()
RETURNS TRIGGER AS $$
BEGIN
    NEW.search_tsv :=

        setweight(to_tsvector('english', COALESCE(NEW.family_name, '')), 'D') ||


        setweight(to_tsvector('english', COALESCE(NEW.formatted_name, '')), 'D') ||


        setweight(to_tsvector('english', COALESCE(NEW.given_name, '')), 'D')

    ;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_name_search_tsv
    BEFORE INSERT OR UPDATE ON common.name
    FOR EACH ROW
    EXECUTE FUNCTION common.update_name_search_tsv();

-- Backfill existing rows (safe no-op on empty tables)
UPDATE common.name
SET search_tsv =

    setweight(to_tsvector('english', COALESCE(family_name, '')), 'D') ||


    setweight(to_tsvector('english', COALESCE(formatted_name, '')), 'D') ||


    setweight(to_tsvector('english', COALESCE(given_name, '')), 'D')

;

