//! Query service for CandidateProfile. Generated by hr-graph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::CandidateProfileResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait CandidateProfileQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<CandidateProfileResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<CandidateProfileResponse>, QueryError>;
}
