//! Update DTO for Allowance.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::ActionCodeList;
use super::dto_create::CreateAllowancePayRateRequest;
use super::dto_create::CreateAllowanceCommentRequest;
use super::dto_create::CreateAllowanceResponsibleRequest;
use super::dto_create::CreateAllowanceResponsibleCommentRequest;
use super::dto_create::CreateAllowanceResponsibleSpecifiedPersonRequest;
use super::dto_create::CreateAllowanceResponsibleSpecifiedPersonCommunicationRequest;
use super::dto_create::CreateAllowanceResponsibleSpecifiedPersonCommunicationAddressTypeArrayRequest;
use super::dto_create::CreateAllowanceResponsibleSpecifiedPersonCommunicationAddressTypeArrayAddressComponentRequest;
use super::dto_create::CreateAllowanceResponsibleSpecifiedPersonCommunicationEmailTypeArrayRequest;
use super::dto_create::CreateAllowanceResponsibleSpecifiedPersonCommunicationPhoneTypeArrayRequest;
use super::dto_create::CreateAllowanceResponsibleSpecifiedPersonCommunicationSocialTypeArrayRequest;
use super::dto_create::CreateAllowanceResponsibleSpecifiedPersonCommunicationWebTypeArrayRequest;
use super::dto_create::CreateAllowanceResponsibleSpecifiedPersonPersonNameRequest;

/// Request body for updating an existing Allowance.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct UpdateAllowanceRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub billable: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payable: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<ActionCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pay_rates: Option<Vec<CreateAllowancePayRateRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<CreateAllowanceCommentRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approvers: Option<Vec<CreateAllowanceResponsibleRequest>>,
}
