//! Create DTO for DaySchedule.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::WeekdayCodeList;

/// Request body for creating a new DaySchedule.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateDayScheduleRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hours: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub weekday: Option<WeekdayCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date: Option<CreateDayScheduleTimeRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shift: Option<CreateDayScheduleEntityRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateDayScheduleTimeRequest {
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateDayScheduleEntityRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}
