//! Response DTO for Financialinstrumentidentification.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Financialinstrumentidentificationtypevalues;

/// Response body for Financialinstrumentidentification.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct FinancialinstrumentidentificationResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub financial_instrument_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub financial_instrument_identification_type: Option<Financialinstrumentidentificationtypevalues>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
