//! Repository trait for GenderCodeList.
//! Generated by codegraph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::GenderCodeListResponse;

use super::dto_create::CreateGenderCodeListRequest;


use super::dto_update::UpdateGenderCodeListRequest;


/// Repository contract for GenderCodeList, generic over the client/transaction
/// type `C` so a single trait serves every persistence backend:
/// - SeaORM: `C = sea_orm::DatabaseTransaction`
/// - Cornucopia: `C: cornucopia_queries::client::GenericClient` (tokio-postgres
///   clients and transactions)
#[async_trait]
pub trait GenderCodeListRepository<C>: Send + Sync {

    async fn create(
        &self,
        tx: &C,
        cmd: CreateGenderCodeListRequest,

    ) -> Result<Uuid, Box<dyn std::error::Error>>;



    async fn find_by_id(
        &self,
        db: &C,
        id: Uuid,

        include_deleted: bool,

    ) -> Result<Option<GenderCodeListResponse>, Box<dyn std::error::Error>>;






    async fn update(
        &self,
        tx: &C,
        id: Uuid,
        cmd: UpdateGenderCodeListRequest,
    ) -> Result<(), Box<dyn std::error::Error>>;



    async fn delete(
        &self,
        tx: &C,
        id: Uuid,
    ) -> Result<(), Box<dyn std::error::Error>>;



    async fn list(
        &self,
        db: &C,
        page: u64,
        page_size: u64,
        filters: &std::collections::HashMap<String, String>,

        include_deleted: bool,

    ) -> Result<(Vec<GenderCodeListResponse>, u64), Box<dyn std::error::Error>>;




}
