// Generated by codegraph. DO NOT EDIT.
// E2E tests for PayRun

import { test, expect } from '@playwright/test';
import { PayRunFixture } from '../../fixtures/compensation/compensation_pay_run';


const authToken = process.env.TEST_AUTH_TOKEN || '';


test.describe('PayRun — Create', () => {
  test('POST /api/v1/compensation/pay-run creates a PayRun', async ({ request }) => {
    const payload = PayRunFixture.valid();
    const response = await request.post('/api/v1/compensation/pay-run', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
      data: payload,
    });
    expect(response.status()).toBe(201);
    const { data } = await response.json();
    expect(data).toHaveProperty('id');



    expect(data.payRunId).toBe(payload.payRunId);









  });

  test('POST without auth rejects with 401', async ({ request }) => {
    const data = PayRunFixture.valid();
    const response = await request.post('/api/v1/compensation/pay-run', { data });
    expect(response.status()).toBe(401);
  });


  test('POST with missing required fields rejects with 422', async ({ request }) => {
    const data = PayRunFixture.missingRequired();
    const response = await request.post('/api/v1/compensation/pay-run', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
      data,
    });
    expect(response.status()).toBe(422);
  });

});



test.describe('PayRun — Read', () => {
  test('GET /api/v1/compensation/pay-run returns paginated list', async ({ request }) => {
    const response = await request.get('/api/v1/compensation/pay-run', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body).toHaveProperty('data');
    expect(Array.isArray(body.data)).toBe(true);
  });

  test('GET /api/v1/compensation/pay-run/:id returns 404 for nonexistent', async ({ request }) => {
    const response = await request.get('/api/v1/compensation/pay-run/00000000-0000-0000-0000-000000000000', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
    expect(response.status()).toBe(404);
  });
});



test.describe('PayRun — Delete', () => {
  test('DELETE /api/v1/compensation/pay-run/:id removes a PayRun', async ({ request }) => {
    const created = await request.post('/api/v1/compensation/pay-run', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
      data: PayRunFixture.valid(),
    });
    expect(created.status()).toBe(201);
    const { data } = await created.json();
    const id = data.id;

    const response = await request.delete(`/api/v1/compensation/pay-run/${id}`, {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
    expect(response.status()).toBe(204);

    const check = await request.get(`/api/v1/compensation/pay-run/${id}`, {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
    expect(check.status()).toBe(404);
  });
});



test.describe('PayRun — Pagination', () => {
  test('list supports page_size', async ({ request }) => {
    const response = await request.get('/api/v1/compensation/pay-run?page=0&page_size=5', {
      headers: authToken ? { Authorization: `Bearer ${authToken}` } : {},
    });
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.data.length).toBeLessThanOrEqual(5);
  });
});

