//! Response DTO for RatedBasedBeneficiary.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::CountryCodeList;
pub use crate::codelist::CurrencyCodeList;
pub use crate::codelist::FamilyRelationshipCodeList;
pub use crate::codelist::GenderCodeList;
pub use crate::codelist::LanguageCodeList;

/// Response body for RatedBasedBeneficiary.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub designation_sequence: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub family_relationship: Option<FamilyRelationshipCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inheritance_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inheritance_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avatar_mime_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub birth_date: Option<chrono::NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ethnicity: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gender: Option<GenderCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legal_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub military_status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_legal_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profile_photo_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profile_photo_mime_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub primary_language: Option<LanguageCodeList>,
    pub citizenship: Vec<RatedBasedBeneficiaryCitizenshipResponse>,
    pub residence_country: Vec<RatedBasedBeneficiaryResidenceCountryResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub communication: Option<RatedBasedBeneficiaryCommunicationResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<RatedBasedBeneficiaryPersonNameResponse>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryCitizenshipResponse {
    pub code: CountryCodeList,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryResidenceCountryResponse {
    pub code: CountryCodeList,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryCommunicationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<RatedBasedBeneficiaryCommunicationAddressTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<RatedBasedBeneficiaryCommunicationEmailTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<RatedBasedBeneficiaryCommunicationPhoneTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub social: Option<RatedBasedBeneficiaryCommunicationSocialTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub web: Option<RatedBasedBeneficiaryCommunicationWebTypeArrayResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryCommunicationAddressTypeArrayResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub post_office_box: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    pub country_sub_divisions: Vec<RatedBasedBeneficiaryCommunicationAddressTypeArrayAddressComponentResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryCommunicationAddressTypeArrayAddressComponentResponse {
    pub r#type: String,
    pub value: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryCommunicationEmailTypeArrayResponse {
    pub address: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryCommunicationPhoneTypeArrayResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub access: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub area_dialing_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_dialing_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dial_number: Option<String>,
    pub formatted_number: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone_extension: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryCommunicationSocialTypeArrayResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    pub url: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryCommunicationWebTypeArrayResponse {
    pub url: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct RatedBasedBeneficiaryPersonNameResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub family: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub family_prefix: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub formatted_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub former_family: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub former_family_prefix: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generation_affix_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub given: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub initials: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legal: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub middle: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preferred: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preferred_salutation_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qualification_affix_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub script: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title_affix_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
}
