//! Domain module for recruiting. Generated by hr-graph. DO NOT EDIT.

pub mod candidate_profile;

pub mod candidate;

pub mod hr_open_certification_internal;

pub mod hr_open_education_attendance_internal;

pub mod hr_open_employment_history_internal;

pub mod hr_open_license_internal;

pub mod hr_open_skill_internal;

pub mod job_description;

pub mod job_posting;

pub mod position_opening;

pub mod position_profile;

pub mod posting_instructions;

pub mod provisional_verifiable_credential_lerrs;

