use std::path::{Path, PathBuf};

use async_trait::async_trait;
use codegraph_core::traits::GraphQuerier;
use codegraph_core::types::{PersistenceColumn, PersistenceColumnRole};

use crate::error::Result;
use crate::generate::persistence::build_persistence_entity;
use crate::generate::traits::{EntityGenerator, GeneratedFile};
use crate::generate::ProjectConfig;
use codegraph_config::DomainConfig;

/// Generates annotated Cornucopia SQL files for an entity's CRUD surface.
///
/// One file per entity at `queries/{domain}/{table}.sql`. Each annotated query
/// block (`--! name (params) : (returns)`) becomes a typed Rust function in the
/// generated `cornucopia-queries` crate.
///
/// Tenant isolation is NOT expressed in the SQL: the DDL trigger fills the
/// tenant column from `app.organization_id` on INSERT and Postgres RLS
/// (`SET LOCAL ROLE app_user` in the query/command layers) filters reads —
/// exactly like the SeaORM backend.
pub struct CornucopiaQueryGenerator {
    output_dir: PathBuf,
    parent_candidates: Vec<codegraph_core::types::ParentCandidate>,
}

impl CornucopiaQueryGenerator {
    pub fn new(output_dir: &Path) -> Self {
        Self {
            output_dir: output_dir.to_path_buf(),
            parent_candidates: Vec::new(),
        }
    }

    pub fn with_parent_candidates(
        mut self,
        candidates: Vec<codegraph_core::types::ParentCandidate>,
    ) -> Self {
        self.parent_candidates = candidates;
        self
    }
}

#[async_trait]
impl EntityGenerator for CornucopiaQueryGenerator {
    fn name(&self) -> &str {
        "cornucopia_queries"
    }

    fn supported_targets(&self) -> Option<Vec<crate::generate::db::dialect::DatabaseTarget>> {
        None
    }

    async fn generate(
        &self,
        db: &dyn GraphQuerier,
        schema_title: &str,
        domain: &str,
        config: &DomainConfig,
        _tera: &tera::Tera,
        _project: &ProjectConfig,
    ) -> Result<Vec<GeneratedFile>> {
        let entity = build_persistence_entity(
            db,
            schema_title,
            domain,
            config,
            &self.parent_candidates,
        )
        .await?;

        if entity.table_name.is_empty() {
            return Ok(Vec::new());
        }

        let entity_name = codegraph_naming::to_snake_case(&codegraph_naming::strip_suffix(
            &entity.rust_type_name,
            &config.defaults.type_suffix,
        ));

        let sql = render_entity_sql(schema_title, domain, config, &entity, &entity_name);

        let rel_path = format!("queries/{}/{}.sql", domain, entity.table_name);
        Ok(vec![GeneratedFile {
            path: self.output_dir.join(&rel_path),
            content: sql,
        }])
    }
}

/// Render the full SQL file for one entity.
fn render_entity_sql(
    schema_title: &str,
    domain: &str,
    config: &DomainConfig,
    entity: &codegraph_core::types::PersistenceEntity,
    entity_name: &str,
) -> String {
    let mut sql = String::with_capacity(16 * 1024);

    let table = format!("\"{}\".\"{}\"", entity.schema_name, entity.table_name);
    let soft_delete_col = entity
        .policies
        .soft_delete
        .as_ref()
        .map(|e| e.marker_column.as_str());
    let is_auditable = soft_delete_col.is_some();

    let return_cols: Vec<&PersistenceColumn> = entity
        .columns
        .iter()
        .filter(|c| {
            matches!(
                c.role,
                PersistenceColumnRole::Data
                    | PersistenceColumnRole::PrimaryKey
                    | PersistenceColumnRole::ForeignKey { .. }
                    | PersistenceColumnRole::TenantScope
                    | PersistenceColumnRole::SoftDeleteMarker
                    | PersistenceColumnRole::AuditTimestamp { .. }
                    | PersistenceColumnRole::AuditUser { .. }
                    | PersistenceColumnRole::AuditFlag
                    | PersistenceColumnRole::HierarchyParent
            )
        })
        .collect();

    let data_cols: Vec<&PersistenceColumn> = entity
        .columns
        .iter()
        .filter(|c| {
            matches!(
                c.role,
                PersistenceColumnRole::Data
                    | PersistenceColumnRole::ForeignKey { .. }
                    | PersistenceColumnRole::HierarchyParent
            )
        })
        .collect();

    sql.push_str(&format!(
        "-- Cornucopia queries for {} (domain: {})\n\
         -- Generated by codegraph — persistence_provider = \"cornucopia\"\n\n",
        schema_title, domain,
    ));

    // ── list (+ count) ─────────────────────────────────────────────────
    write_list_queries(&mut sql, &table, entity_name, soft_delete_col, &return_cols);

    // ── get by id ──────────────────────────────────────────────────────
    write_get_queries(&mut sql, &table, entity_name, soft_delete_col, &return_cols);

    // ── create ─────────────────────────────────────────────────────────
    write_create_query(&mut sql, &table, entity_name, &data_cols);

    // ── update (COALESCE so missing Option fields keep existing values) ─
    write_update_query(&mut sql, &table, entity_name, &data_cols, soft_delete_col);

    // ── delete ─────────────────────────────────────────────────────────
    write_delete_query(&mut sql, &table, entity_name, soft_delete_col);

    // ── child tables (VO tables) ───────────────────────────────────────
    for child in &entity.child_tables {
        write_child_queries(&mut sql, &entity.schema_name, entity_name, child);
    }

    // ── FTS / embeddings / tree ────────────────────────────────────────
    let entity_cfg = config
        .domains
        .get(domain)
        .and_then(|d| d.get_entity_config(schema_title));
    let search = entity_cfg.map(|ec| &ec.search);
    if let Some(search) = search {
        // Match the SeaORM emitter: FTS is enabled only when fts_columns are
        // resolved (the DDL generator creates search_tsv from those).
        let has_fts = search
            .fts_columns
            .as_ref()
            .map(|cols| !cols.is_empty())
            .unwrap_or(false);
        if has_fts {
            let fts_language = search.fts_language.clone();
            write_search_queries(&mut sql, &table, entity_name, soft_delete_col, &fts_language);
        }
        if !search.embedding_columns.is_empty() {
            // The DDL generator names the vector column `{column}_embedding`
            // from the first configured embedding column.
            if let Some(first) = search.embedding_columns.first() {
                let emb_col = format!("{}_embedding", first);
                write_embedding_queries(&mut sql, &table, entity_name, soft_delete_col, &emb_col);
            }
        }
    }
    let hierarchy_field = entity_cfg.and_then(|ec| ec.hierarchy_field.clone());
    if let Some(hf) = hierarchy_field {
        write_tree_query(&mut sql, &table, entity_name, &hf, &return_cols);
    }

    let _ = is_auditable;
    sql
}

fn col_list(cols: &[&PersistenceColumn]) -> String {
    cols.iter()
        .map(|c| format!("\"{}\"", c.column_name))
        .collect::<Vec<_>>()
        .join(", ")
}

fn nullable_hints(cols: &[&PersistenceColumn]) -> String {
    cols.iter()
        .map(|c| {
            let name = c.field_name.trim_start_matches("r#");
            if c.is_nullable {
                format!("{}?", name)
            } else {
                name.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn write_list_queries(
    sql: &mut String,
    table: &str,
    entity_name: &str,
    soft_delete_col: Option<&str>,
    return_cols: &[&PersistenceColumn],
) {
    let cols = col_list(return_cols);
    let hints = nullable_hints(return_cols);

    for (suffix, include_deleted) in [("", false), ("_including_deleted", true)] {
        if include_deleted && soft_delete_col.is_none() {
            continue;
        }
        let where_clause = if !include_deleted {
            soft_delete_col
                .map(|sd| format!("\n  WHERE \"{sd}\" IS NULL"))
                .unwrap_or_default()
        } else {
            String::new()
        };
        sql.push_str(&format!(
            "--! list_{entity_name}{suffix} (offset, page_size) : ({hints})\n\
             --- List {entity_name} records.\n\
             SELECT {cols}\n\
             FROM {table}{where_clause}\n\
             ORDER BY \"created_at\" DESC\n\
             LIMIT :page_size OFFSET :offset;\n\n",
        ));
        let count_where_clause = if include_deleted {
            String::new()
        } else {
            soft_delete_col
                .map(|sd| format!("\n  WHERE \"{sd}\" IS NULL"))
                .unwrap_or_default()
        };
        sql.push_str(&format!(
            "--! count_{entity_name}{suffix} : (count)\n\
             --- Count of {entity_name} records.\n\
             SELECT COUNT(*) AS \"count\"\n\
             FROM {table}{count_where_clause};\n\n",
        ));
    }
}

fn write_get_queries(
    sql: &mut String,
    table: &str,
    entity_name: &str,
    soft_delete_col: Option<&str>,
    return_cols: &[&PersistenceColumn],
) {
    let cols = col_list(return_cols);
    let hints = nullable_hints(return_cols);

    for (suffix, include_deleted) in [("", false), ("_including_deleted", true)] {
        if include_deleted && soft_delete_col.is_none() {
            continue;
        }
        let mut clauses = vec!["\"id\" = :id".to_string()];
        if !include_deleted {
            if let Some(sd) = soft_delete_col {
                clauses.push(format!("\"{}\" IS NULL", sd));
            }
        }
        sql.push_str(&format!(
            "--! get_{entity_name}{suffix} (id) : ({hints})\n\
             --- Get a single {entity_name} by ID.\n\
             SELECT {cols}\n\
             FROM {table}\n\
             WHERE {};\n\n",
            clauses.join("\n    AND "),
        ));
    }
}

fn write_create_query(
    sql: &mut String,
    table: &str,
    entity_name: &str,
    data_cols: &[&PersistenceColumn],
) {
    let mut insert_cols = Vec::new();
    let mut insert_params = Vec::new();
    let mut param_defs = Vec::new();

    for col in data_cols {
        let role_skip = matches!(
            col.role,
            PersistenceColumnRole::AuditTimestamp { .. }
                | PersistenceColumnRole::AuditUser { .. }
                | PersistenceColumnRole::AuditFlag
                | PersistenceColumnRole::SoftDeleteMarker
                | PersistenceColumnRole::PrimaryKey
                | PersistenceColumnRole::TenantScope
        );
        if role_skip {
            continue;
        }
        insert_cols.push(format!("\"{}\"", col.column_name));
        if let Some(ref cast) = col.pg_cast {
            // Bind as text and cast in SQL so the DTO's string representation works.
            insert_params.push(format!(":{}::text::{}", col.field_name.trim_start_matches("r#"), cast));
        } else {
            insert_params.push(format!(":{}", col.field_name.trim_start_matches("r#")));
        }
        param_defs.push(col.field_name.trim_start_matches("r#").to_string());
    }

    if insert_cols.is_empty() {
        // Entities whose data lives entirely in child tables (or system-managed
        // columns) still need a create query — Postgres fills the defaults.
        sql.push_str(&format!(
            "--! create_{entity_name} : (id)\n\
             --- Create a new {entity_name} (defaults only).\n\
             INSERT INTO {table} DEFAULT VALUES\n\
             RETURNING \"id\";\n\n",
        ));
        return;
    }

    sql.push_str(&format!(
        "--! create_{entity_name} ({}) : (id)\n\
         --- Create a new {entity_name}.\n\
         INSERT INTO {table} ({})\n\
         VALUES ({})\n\
         RETURNING \"id\";\n\n",
        param_defs.join(", "),
        insert_cols.join(", "),
        insert_params.join(", "),
    ));
}

fn write_update_query(
    sql: &mut String,
    table: &str,
    entity_name: &str,
    data_cols: &[&PersistenceColumn],
    soft_delete_col: Option<&str>,
) {
    let updatable: Vec<&PersistenceColumn> = data_cols
        .iter()
        .copied()
        .filter(|c| {
            !matches!(
                c.role,
                PersistenceColumnRole::AuditTimestamp { .. }
                    | PersistenceColumnRole::AuditUser { .. }
                    | PersistenceColumnRole::AuditFlag
                    | PersistenceColumnRole::SoftDeleteMarker
                    | PersistenceColumnRole::PrimaryKey
                    | PersistenceColumnRole::TenantScope
            )
        })
        .collect();

    if updatable.is_empty() {
        // No writable columns — emit a no-op update so the repository API
        // stays uniform (and the audit trigger still fires).
        sql.push_str(&format!(
            "--! update_{entity_name} (id)\n\
             --- No-op update for {entity_name}.\n\
             UPDATE {table}\n\
             SET \"updated_at\" = \"updated_at\"\n\
             WHERE \"id\" = :id;\n\n",
        ));
        return;
    }

    // COALESCE keeps existing values when the update DTO leaves a field unset
    // (update request fields are Option<T>; None binds as NULL).
    let set_clauses = updatable
        .iter()
        .map(|c| {
            if let Some(ref cast) = c.pg_cast {
                format!(
                    "\"{}\" = COALESCE(:{}::text::{}, \"{}\")",
                    c.column_name,
                    c.field_name.trim_start_matches("r#"),
                    cast,
                    c.column_name
                )
            } else {
                format!(
                    "\"{}\" = COALESCE(:{}, \"{}\")",
                    c.column_name,
                    c.field_name.trim_start_matches("r#"),
                    c.column_name
                )
            }
        })
        .collect::<Vec<_>>()
        .join(",\n    ");

    let mut params = vec!["id".to_string()];
    for c in &updatable {
        params.push(c.field_name.trim_start_matches("r#").to_string());
    }

    let mut where_clauses = vec!["\"id\" = :id".to_string()];
    if let Some(sd) = soft_delete_col {
        where_clauses.push(format!("\"{}\" IS NULL", sd));
    }

    sql.push_str(&format!(
        "--! update_{entity_name} ({})\n\
         --- Update an existing {entity_name}.\n\
         UPDATE {table}\n\
         SET {set_clauses}\n\
         WHERE {};\n\n",
        params.join(", "),
        where_clauses.join("\n  AND "),
    ));
}

fn write_delete_query(
    sql: &mut String,
    table: &str,
    entity_name: &str,
    soft_delete_col: Option<&str>,
) {
    let mut where_clauses = vec!["\"id\" = :id".to_string()];
    if let Some(sd) = soft_delete_col {
        where_clauses.push(format!("\"{}\" IS NULL", sd));
    }
    match soft_delete_col {
        Some(sd) => {
            sql.push_str(&format!(
                "--! delete_{entity_name} (id)\n\
                 --- Soft-delete a {entity_name} by setting the deletion marker.\n\
                 UPDATE {table}\n\
                 SET \"{sd}\" = NOW()\n\
                 WHERE {};\n\n",
                where_clauses.join("\n  AND "),
            ));
        }
        None => {
            sql.push_str(&format!(
                "--! delete_{entity_name} (id)\n\
                 --- Hard-delete a {entity_name}.\n\
                 DELETE FROM {table}\n\
                 WHERE {};\n\n",
                where_clauses.join("\n  AND "),
            ));
        }
    }
}

/// Emit list/insert/delete queries for a child (value-object) table.
fn write_child_queries(
    sql: &mut String,
    schema_name: &str,
    entity_name: &str,
    child: &codegraph_core::types::PersistenceChildTable,
) {
    let child_table = format!("\"{}\".\"{}\"", schema_name, child.table_name);
    let fk = &child.parent_fk_column;
    let col_names: Vec<String> = child
        .columns
        .iter()
        .map(|c| format!("\"{}\"", c.column_name))
        .collect();

    if col_names.is_empty() {
        sql.push_str(&format!(
            "--! list_{entity_name}_{child} ({fk}) : (id)\n\
             --- Child rows for {entity_name}.\n\
             SELECT \"id\"\n\
             FROM {table}\n\
             WHERE \"{fk}\" = :{fk};\n\n",
            child = child.table_name,
            table = child_table,
        ));
    } else {
        let hints: Vec<String> = child
            .columns
            .iter()
            .map(|c| {
                let name = c.field_name.trim_start_matches("r#");
                if c.is_nullable {
                    format!("{}?", name)
                } else {
                    name.to_string()
                }
            })
            .collect();
        sql.push_str(&format!(
            "--! list_{entity_name}_{child} ({fk}) : (id, {hints})\n\
             --- Child rows for {entity_name}.\n\
             SELECT \"id\", {cols}\n\
             FROM {table}\n\
             WHERE \"{fk}\" = :{fk};\n\n",
            child = child.table_name,
            hints = hints.join(", "),
            cols = col_names.join(", "),
            table = child_table,
        ));
    }

    // Insert a child row (id generated by the adapter).
    let mut insert_cols = vec!["\"id\"".to_string(), format!("\"{}\"", fk)];
    let mut insert_vals = vec![":id".to_string(), format!(":{}", fk)];
    let mut param_defs = vec!["id".to_string(), fk.clone()];
    for c in &child.columns {
        insert_cols.push(format!("\"{}\"", c.column_name));
        if let Some(ref cast) = c.pg_cast {
            // Bind as text and cast in SQL so the DTO's string representation works.
            insert_vals.push(format!(":{}::text::{}", c.field_name.trim_start_matches("r#"), cast));
        } else {
            insert_vals.push(format!(":{}", c.field_name.trim_start_matches("r#")));
        }
        param_defs.push(c.field_name.trim_start_matches("r#").to_string());
    }
    sql.push_str(&format!(
        "--! insert_{entity_name}_{child} ({})\n\
         --- Insert a child row for {entity_name}.\n\
         INSERT INTO {table} ({})\n\
         VALUES ({});\n\n",
        param_defs.join(", "),
        insert_cols.join(", "),
        insert_vals.join(", "),
        child = child.table_name,
        table = child_table,
    ));

    // Delete child rows by parent FK (used when replacing children on update).
    sql.push_str(&format!(
        "--! delete_{entity_name}_{child} ({fk})\n\
         --- Delete child rows for {entity_name}.\n\
         DELETE FROM {table}\n\
         WHERE \"{fk}\" = :{fk};\n\n",
        child = child.table_name,
        table = child_table,
    ));

    // Nested grandchildren.
    for grandchild in &child.child_tables {
        write_child_queries(sql, schema_name, entity_name, grandchild);
    }
}

fn write_search_queries(
    sql: &mut String,
    table: &str,
    entity_name: &str,
    soft_delete_col: Option<&str>,
    fts_language: &str,
) {
    for (suffix, include_deleted) in [("", false), ("_including_deleted", true)] {
        if include_deleted && soft_delete_col.is_none() {
            continue;
        }
        let extra = if !include_deleted {
            soft_delete_col
                .map(|sd| format!(" AND \"{sd}\" IS NULL"))
                .unwrap_or_default()
        } else {
            String::new()
        };
        sql.push_str(&format!(
            "--! search_{entity_name}{suffix} (q, offset, page_size) : (id)\n\
             --- Full-text search over {entity_name}.\n\
             SELECT \"id\"\n\
             FROM {table}\n\
             WHERE search_tsv @@ websearch_to_tsquery('{fts_language}', :q){extra}\n\
             ORDER BY ts_rank(search_tsv, websearch_to_tsquery('{fts_language}', :q)) DESC\n\
             LIMIT :page_size OFFSET :offset;\n\n",
        ));
        sql.push_str(&format!(
            "--! search_count_{entity_name}{suffix} (q) : (count)\n\
             --- Count of full-text search matches for {entity_name}.\n\
             SELECT COUNT(*) AS \"count\"\n\
             FROM {table}\n\
             WHERE search_tsv @@ websearch_to_tsquery('{fts_language}', :q){extra};\n\n",
        ));
    }
}

fn write_embedding_queries(
    sql: &mut String,
    table: &str,
    entity_name: &str,
    soft_delete_col: Option<&str>,
    emb_col: &str,
) {
    for (suffix, include_deleted) in [("", false), ("_including_deleted", true)] {
        if include_deleted && soft_delete_col.is_none() {
            continue;
        }
        let extra = if !include_deleted {
            soft_delete_col
                .map(|sd| format!(" AND \"{sd}\" IS NULL"))
                .unwrap_or_default()
        } else {
            String::new()
        };
        sql.push_str(&format!(
            "--! semantic_{entity_name}{suffix} (embedding, limit) : (id)\n\
             --- Semantic similarity search over {entity_name}.\n\
             SELECT \"id\"\n\
             FROM {table}\n\
             WHERE \"{emb_col}\" IS NOT NULL{extra}\n\
             ORDER BY \"{emb_col}\" <=> :embedding::vector\n\
             LIMIT :limit;\n\n",
        ));
    }
}

fn write_tree_query(
    sql: &mut String,
    table: &str,
    entity_name: &str,
    hierarchy_field: &str,
    return_cols: &[&PersistenceColumn],
) {
    let cols = col_list(return_cols);
    let prefixed = return_cols
        .iter()
        .map(|c| format!("c.\"{}\"", c.column_name))
        .collect::<Vec<_>>()
        .join(", ");
    let hints = nullable_hints(return_cols);
    sql.push_str(&format!(
        "--! tree_{entity_name} (root_id, max_depth) : ({hints})\n\
         --- Recursive subtree rooted at a {entity_name}.\n\
         WITH RECURSIVE tree AS (\n\
         \x20 SELECT {cols}, 0 AS _tree_depth FROM {table} WHERE \"id\" = :root_id\n\
         \x20 UNION ALL\n\
         \x20 SELECT {prefixed}, t._tree_depth + 1 AS _tree_depth FROM {table} c JOIN tree t ON c.\"{hierarchy_field}\" = t.\"id\"\n\
         \x20 WHERE (:max_depth::int4 IS NULL OR t._tree_depth < :max_depth::int4)\n\
         )\n\
         SELECT {cols} FROM tree ORDER BY _tree_depth, \"created_at\";\n\n",
    ));
}
