//! Query service for Correspondence. Generated by codegraph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::CorrespondenceResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait CorrespondenceQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<CorrespondenceResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<CorrespondenceResponse>, QueryError>;
}
