//! Codelist enum for Analysistypevalues.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Analysistypevalues codelist values.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[allow(clippy::enum_variant_names)]
pub enum Analysistypevalues {

    #[default]
    PerformanceAnalysis,

    ActivityAnalysis,

    RevenueAnalysis,

    CostAnalysis,

    PredictiveAnalysis,

    BehavioralAnalysis,

    ProfitabilityAnalysis,

    CompetitiveAnalysis,

    CohortAnalysis,

    SegmentAnalysis,

    #[serde(rename = "SWOTAnalysis")]
    SwotAnalysis,

    Benchmarking,

    PositioningAnalysis,

    ScenarioAnalysis,

    IntelligenceGathering,

    Profiling,

}

impl std::fmt::Display for Analysistypevalues {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {

            Self::PerformanceAnalysis => write!(f, "PerformanceAnalysis"),

            Self::ActivityAnalysis => write!(f, "ActivityAnalysis"),

            Self::RevenueAnalysis => write!(f, "RevenueAnalysis"),

            Self::CostAnalysis => write!(f, "CostAnalysis"),

            Self::PredictiveAnalysis => write!(f, "PredictiveAnalysis"),

            Self::BehavioralAnalysis => write!(f, "BehavioralAnalysis"),

            Self::ProfitabilityAnalysis => write!(f, "ProfitabilityAnalysis"),

            Self::CompetitiveAnalysis => write!(f, "CompetitiveAnalysis"),

            Self::CohortAnalysis => write!(f, "CohortAnalysis"),

            Self::SegmentAnalysis => write!(f, "SegmentAnalysis"),

            Self::SwotAnalysis => write!(f, "SWOTAnalysis"),

            Self::Benchmarking => write!(f, "Benchmarking"),

            Self::PositioningAnalysis => write!(f, "PositioningAnalysis"),

            Self::ScenarioAnalysis => write!(f, "ScenarioAnalysis"),

            Self::IntelligenceGathering => write!(f, "IntelligenceGathering"),

            Self::Profiling => write!(f, "Profiling"),

        }
    }
}

impl std::str::FromStr for Analysistypevalues {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {

            "PerformanceAnalysis" => Ok(Self::PerformanceAnalysis),

            "ActivityAnalysis" => Ok(Self::ActivityAnalysis),

            "RevenueAnalysis" => Ok(Self::RevenueAnalysis),

            "CostAnalysis" => Ok(Self::CostAnalysis),

            "PredictiveAnalysis" => Ok(Self::PredictiveAnalysis),

            "BehavioralAnalysis" => Ok(Self::BehavioralAnalysis),

            "ProfitabilityAnalysis" => Ok(Self::ProfitabilityAnalysis),

            "CompetitiveAnalysis" => Ok(Self::CompetitiveAnalysis),

            "CohortAnalysis" => Ok(Self::CohortAnalysis),

            "SegmentAnalysis" => Ok(Self::SegmentAnalysis),

            "SWOTAnalysis" => Ok(Self::SwotAnalysis),

            "Benchmarking" => Ok(Self::Benchmarking),

            "PositioningAnalysis" => Ok(Self::PositioningAnalysis),

            "ScenarioAnalysis" => Ok(Self::ScenarioAnalysis),

            "IntelligenceGathering" => Ok(Self::IntelligenceGathering),

            "Profiling" => Ok(Self::Profiling),

            _ => Err(format!("unknown Analysistypevalues value: {}", s)),
        }
    }
}
