//! Codelist enum for Currencytypevalues.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Currencytypevalues codelist values.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[allow(clippy::enum_variant_names)]
pub enum Currencytypevalues {

    #[default]
    BaseCurrency,

    ReportingCurrency,

    SecondaryCurrency,

    TransferCurrency,

    SettlementCurrency,

}

impl std::fmt::Display for Currencytypevalues {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {

            Self::BaseCurrency => write!(f, "BaseCurrency"),

            Self::ReportingCurrency => write!(f, "ReportingCurrency"),

            Self::SecondaryCurrency => write!(f, "SecondaryCurrency"),

            Self::TransferCurrency => write!(f, "TransferCurrency"),

            Self::SettlementCurrency => write!(f, "SettlementCurrency"),

        }
    }
}

impl std::str::FromStr for Currencytypevalues {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {

            "BaseCurrency" => Ok(Self::BaseCurrency),

            "ReportingCurrency" => Ok(Self::ReportingCurrency),

            "SecondaryCurrency" => Ok(Self::SecondaryCurrency),

            "TransferCurrency" => Ok(Self::TransferCurrency),

            "SettlementCurrency" => Ok(Self::SettlementCurrency),

            _ => Err(format!("unknown Currencytypevalues value: {}", s)),
        }
    }
}
