//! Codelist enum for Goaldatetimetypevalues.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Goaldatetimetypevalues codelist values.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[allow(clippy::enum_variant_names)]
pub enum Goaldatetimetypevalues {

    #[default]
    SettingDate,

    PlanningDate,

    StartDate,

    ReviewDate,

    CompletionDate,

}

impl std::fmt::Display for Goaldatetimetypevalues {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {

            Self::SettingDate => write!(f, "SettingDate"),

            Self::PlanningDate => write!(f, "PlanningDate"),

            Self::StartDate => write!(f, "StartDate"),

            Self::ReviewDate => write!(f, "ReviewDate"),

            Self::CompletionDate => write!(f, "CompletionDate"),

        }
    }
}

impl std::str::FromStr for Goaldatetimetypevalues {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {

            "SettingDate" => Ok(Self::SettingDate),

            "PlanningDate" => Ok(Self::PlanningDate),

            "StartDate" => Ok(Self::StartDate),

            "ReviewDate" => Ok(Self::ReviewDate),

            "CompletionDate" => Ok(Self::CompletionDate),

            _ => Err(format!("unknown Goaldatetimetypevalues value: {}", s)),
        }
    }
}
