//! Codelist enum for Partyidentificationtypevalues.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Partyidentificationtypevalues codelist values.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[allow(clippy::enum_variant_names)]
pub enum Partyidentificationtypevalues {

    #[default]
    Taxidentificationnumber,

    Nationalregistrationnumber,

    Registrationauthorityidentification,

    #[serde(rename = "LEI(LegalEntityIdentifier)")]
    LeiLegalEntityIdentifier,

    Alienregistrationnumber,

    Passportnumber,

    Taxexemptidentificationnumber,

    Corporateidentification,

    Driverlicensenumber,

    Foreigninvestmentidentitynumber,

    Socialsecuritynumber,

    Identitycardnumber,

    Concat,

    Nationalregistrationidentificationnumber,

    Taxidentificationnumber,

    Taxidentificationnumber,

    Nationalregistrationnumber,

    Nationalregistrationnumber,

    Registrationauthorityidentification,

    Registrationauthorityidentification,

    #[serde(rename = "LEI(LegalEntityIdentifier)")]
    LeiLegalEntityIdentifier,

    #[serde(rename = "LEI(LegalEntityIdentifier)")]
    LeiLegalEntityIdentifier,

    Alienregistrationnumber,

    Alienregistrationnumber,

    Passportnumber,

    Passportnumber,

    Taxexemptidentificationnumber,

    Taxexemptidentificationnumber,

    Corporateidentification,

    Corporateidentification,

    Driverlicensenumber,

    Driverlicensenumber,

    Foreigninvestmentidentitynumber,

    Foreigninvestmentidentitynumber,

    Socialsecuritynumber,

    Socialsecuritynumber,

    Identitycardnumber,

    Identitycardnumber,

    Concat,

    Concat,

    Nationalregistrationidentificationnumber,

    Nationalregistrationidentificationnumber,

    Taxidentificationnumber,

    Taxidentificationnumber,

    Nationalregistrationnumber,

    Nationalregistrationnumber,

    Registrationauthorityidentification,

    Registrationauthorityidentification,

    #[serde(rename = "LEI(LegalEntityIdentifier)")]
    LeiLegalEntityIdentifier,

    #[serde(rename = "LEI(LegalEntityIdentifier)")]
    LeiLegalEntityIdentifier,

    Alienregistrationnumber,

    Alienregistrationnumber,

    Passportnumber,

    Passportnumber,

    Taxexemptidentificationnumber,

    Taxexemptidentificationnumber,

    Corporateidentification,

    Corporateidentification,

    Driverlicensenumber,

    Driverlicensenumber,

    Foreigninvestmentidentitynumber,

    Foreigninvestmentidentitynumber,

    Socialsecuritynumber,

    Socialsecuritynumber,

    Identitycardnumber,

    Identitycardnumber,

    Concat,

    Concat,

    Nationalregistrationidentificationnumber,

    Nationalregistrationidentificationnumber,

}

impl std::fmt::Display for Partyidentificationtypevalues {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {

            Self::Taxidentificationnumber => write!(f, "Taxidentificationnumber"),

            Self::Nationalregistrationnumber => write!(f, "Nationalregistrationnumber"),

            Self::Registrationauthorityidentification => write!(f, "Registrationauthorityidentification"),

            Self::LeiLegalEntityIdentifier => write!(f, "LEI(LegalEntityIdentifier)"),

            Self::Alienregistrationnumber => write!(f, "Alienregistrationnumber"),

            Self::Passportnumber => write!(f, "Passportnumber"),

            Self::Taxexemptidentificationnumber => write!(f, "Taxexemptidentificationnumber"),

            Self::Corporateidentification => write!(f, "Corporateidentification"),

            Self::Driverlicensenumber => write!(f, "Driverlicensenumber"),

            Self::Foreigninvestmentidentitynumber => write!(f, "Foreigninvestmentidentitynumber"),

            Self::Socialsecuritynumber => write!(f, "Socialsecuritynumber"),

            Self::Identitycardnumber => write!(f, "Identitycardnumber"),

            Self::Concat => write!(f, "Concat"),

            Self::Nationalregistrationidentificationnumber => write!(f, "Nationalregistrationidentificationnumber"),

            Self::Taxidentificationnumber => write!(f, "Taxidentificationnumber"),

            Self::Taxidentificationnumber => write!(f, "Taxidentificationnumber"),

            Self::Nationalregistrationnumber => write!(f, "Nationalregistrationnumber"),

            Self::Nationalregistrationnumber => write!(f, "Nationalregistrationnumber"),

            Self::Registrationauthorityidentification => write!(f, "Registrationauthorityidentification"),

            Self::Registrationauthorityidentification => write!(f, "Registrationauthorityidentification"),

            Self::LeiLegalEntityIdentifier => write!(f, "LEI(LegalEntityIdentifier)"),

            Self::LeiLegalEntityIdentifier => write!(f, "LEI(LegalEntityIdentifier)"),

            Self::Alienregistrationnumber => write!(f, "Alienregistrationnumber"),

            Self::Alienregistrationnumber => write!(f, "Alienregistrationnumber"),

            Self::Passportnumber => write!(f, "Passportnumber"),

            Self::Passportnumber => write!(f, "Passportnumber"),

            Self::Taxexemptidentificationnumber => write!(f, "Taxexemptidentificationnumber"),

            Self::Taxexemptidentificationnumber => write!(f, "Taxexemptidentificationnumber"),

            Self::Corporateidentification => write!(f, "Corporateidentification"),

            Self::Corporateidentification => write!(f, "Corporateidentification"),

            Self::Driverlicensenumber => write!(f, "Driverlicensenumber"),

            Self::Driverlicensenumber => write!(f, "Driverlicensenumber"),

            Self::Foreigninvestmentidentitynumber => write!(f, "Foreigninvestmentidentitynumber"),

            Self::Foreigninvestmentidentitynumber => write!(f, "Foreigninvestmentidentitynumber"),

            Self::Socialsecuritynumber => write!(f, "Socialsecuritynumber"),

            Self::Socialsecuritynumber => write!(f, "Socialsecuritynumber"),

            Self::Identitycardnumber => write!(f, "Identitycardnumber"),

            Self::Identitycardnumber => write!(f, "Identitycardnumber"),

            Self::Concat => write!(f, "Concat"),

            Self::Concat => write!(f, "Concat"),

            Self::Nationalregistrationidentificationnumber => write!(f, "Nationalregistrationidentificationnumber"),

            Self::Nationalregistrationidentificationnumber => write!(f, "Nationalregistrationidentificationnumber"),

            Self::Taxidentificationnumber => write!(f, "Taxidentificationnumber"),

            Self::Taxidentificationnumber => write!(f, "Taxidentificationnumber"),

            Self::Nationalregistrationnumber => write!(f, "Nationalregistrationnumber"),

            Self::Nationalregistrationnumber => write!(f, "Nationalregistrationnumber"),

            Self::Registrationauthorityidentification => write!(f, "Registrationauthorityidentification"),

            Self::Registrationauthorityidentification => write!(f, "Registrationauthorityidentification"),

            Self::LeiLegalEntityIdentifier => write!(f, "LEI(LegalEntityIdentifier)"),

            Self::LeiLegalEntityIdentifier => write!(f, "LEI(LegalEntityIdentifier)"),

            Self::Alienregistrationnumber => write!(f, "Alienregistrationnumber"),

            Self::Alienregistrationnumber => write!(f, "Alienregistrationnumber"),

            Self::Passportnumber => write!(f, "Passportnumber"),

            Self::Passportnumber => write!(f, "Passportnumber"),

            Self::Taxexemptidentificationnumber => write!(f, "Taxexemptidentificationnumber"),

            Self::Taxexemptidentificationnumber => write!(f, "Taxexemptidentificationnumber"),

            Self::Corporateidentification => write!(f, "Corporateidentification"),

            Self::Corporateidentification => write!(f, "Corporateidentification"),

            Self::Driverlicensenumber => write!(f, "Driverlicensenumber"),

            Self::Driverlicensenumber => write!(f, "Driverlicensenumber"),

            Self::Foreigninvestmentidentitynumber => write!(f, "Foreigninvestmentidentitynumber"),

            Self::Foreigninvestmentidentitynumber => write!(f, "Foreigninvestmentidentitynumber"),

            Self::Socialsecuritynumber => write!(f, "Socialsecuritynumber"),

            Self::Socialsecuritynumber => write!(f, "Socialsecuritynumber"),

            Self::Identitycardnumber => write!(f, "Identitycardnumber"),

            Self::Identitycardnumber => write!(f, "Identitycardnumber"),

            Self::Concat => write!(f, "Concat"),

            Self::Concat => write!(f, "Concat"),

            Self::Nationalregistrationidentificationnumber => write!(f, "Nationalregistrationidentificationnumber"),

            Self::Nationalregistrationidentificationnumber => write!(f, "Nationalregistrationidentificationnumber"),

        }
    }
}

impl std::str::FromStr for Partyidentificationtypevalues {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {

            "Taxidentificationnumber" => Ok(Self::Taxidentificationnumber),

            "Nationalregistrationnumber" => Ok(Self::Nationalregistrationnumber),

            "Registrationauthorityidentification" => Ok(Self::Registrationauthorityidentification),

            "LEI(LegalEntityIdentifier)" => Ok(Self::LeiLegalEntityIdentifier),

            "Alienregistrationnumber" => Ok(Self::Alienregistrationnumber),

            "Passportnumber" => Ok(Self::Passportnumber),

            "Taxexemptidentificationnumber" => Ok(Self::Taxexemptidentificationnumber),

            "Corporateidentification" => Ok(Self::Corporateidentification),

            "Driverlicensenumber" => Ok(Self::Driverlicensenumber),

            "Foreigninvestmentidentitynumber" => Ok(Self::Foreigninvestmentidentitynumber),

            "Socialsecuritynumber" => Ok(Self::Socialsecuritynumber),

            "Identitycardnumber" => Ok(Self::Identitycardnumber),

            "Concat" => Ok(Self::Concat),

            "Nationalregistrationidentificationnumber" => Ok(Self::Nationalregistrationidentificationnumber),

            "Taxidentificationnumber" => Ok(Self::Taxidentificationnumber),

            "Taxidentificationnumber" => Ok(Self::Taxidentificationnumber),

            "Nationalregistrationnumber" => Ok(Self::Nationalregistrationnumber),

            "Nationalregistrationnumber" => Ok(Self::Nationalregistrationnumber),

            "Registrationauthorityidentification" => Ok(Self::Registrationauthorityidentification),

            "Registrationauthorityidentification" => Ok(Self::Registrationauthorityidentification),

            "LEI(LegalEntityIdentifier)" => Ok(Self::LeiLegalEntityIdentifier),

            "LEI(LegalEntityIdentifier)" => Ok(Self::LeiLegalEntityIdentifier),

            "Alienregistrationnumber" => Ok(Self::Alienregistrationnumber),

            "Alienregistrationnumber" => Ok(Self::Alienregistrationnumber),

            "Passportnumber" => Ok(Self::Passportnumber),

            "Passportnumber" => Ok(Self::Passportnumber),

            "Taxexemptidentificationnumber" => Ok(Self::Taxexemptidentificationnumber),

            "Taxexemptidentificationnumber" => Ok(Self::Taxexemptidentificationnumber),

            "Corporateidentification" => Ok(Self::Corporateidentification),

            "Corporateidentification" => Ok(Self::Corporateidentification),

            "Driverlicensenumber" => Ok(Self::Driverlicensenumber),

            "Driverlicensenumber" => Ok(Self::Driverlicensenumber),

            "Foreigninvestmentidentitynumber" => Ok(Self::Foreigninvestmentidentitynumber),

            "Foreigninvestmentidentitynumber" => Ok(Self::Foreigninvestmentidentitynumber),

            "Socialsecuritynumber" => Ok(Self::Socialsecuritynumber),

            "Socialsecuritynumber" => Ok(Self::Socialsecuritynumber),

            "Identitycardnumber" => Ok(Self::Identitycardnumber),

            "Identitycardnumber" => Ok(Self::Identitycardnumber),

            "Concat" => Ok(Self::Concat),

            "Concat" => Ok(Self::Concat),

            "Nationalregistrationidentificationnumber" => Ok(Self::Nationalregistrationidentificationnumber),

            "Nationalregistrationidentificationnumber" => Ok(Self::Nationalregistrationidentificationnumber),

            "Taxidentificationnumber" => Ok(Self::Taxidentificationnumber),

            "Taxidentificationnumber" => Ok(Self::Taxidentificationnumber),

            "Nationalregistrationnumber" => Ok(Self::Nationalregistrationnumber),

            "Nationalregistrationnumber" => Ok(Self::Nationalregistrationnumber),

            "Registrationauthorityidentification" => Ok(Self::Registrationauthorityidentification),

            "Registrationauthorityidentification" => Ok(Self::Registrationauthorityidentification),

            "LEI(LegalEntityIdentifier)" => Ok(Self::LeiLegalEntityIdentifier),

            "LEI(LegalEntityIdentifier)" => Ok(Self::LeiLegalEntityIdentifier),

            "Alienregistrationnumber" => Ok(Self::Alienregistrationnumber),

            "Alienregistrationnumber" => Ok(Self::Alienregistrationnumber),

            "Passportnumber" => Ok(Self::Passportnumber),

            "Passportnumber" => Ok(Self::Passportnumber),

            "Taxexemptidentificationnumber" => Ok(Self::Taxexemptidentificationnumber),

            "Taxexemptidentificationnumber" => Ok(Self::Taxexemptidentificationnumber),

            "Corporateidentification" => Ok(Self::Corporateidentification),

            "Corporateidentification" => Ok(Self::Corporateidentification),

            "Driverlicensenumber" => Ok(Self::Driverlicensenumber),

            "Driverlicensenumber" => Ok(Self::Driverlicensenumber),

            "Foreigninvestmentidentitynumber" => Ok(Self::Foreigninvestmentidentitynumber),

            "Foreigninvestmentidentitynumber" => Ok(Self::Foreigninvestmentidentitynumber),

            "Socialsecuritynumber" => Ok(Self::Socialsecuritynumber),

            "Socialsecuritynumber" => Ok(Self::Socialsecuritynumber),

            "Identitycardnumber" => Ok(Self::Identitycardnumber),

            "Identitycardnumber" => Ok(Self::Identitycardnumber),

            "Concat" => Ok(Self::Concat),

            "Concat" => Ok(Self::Concat),

            "Nationalregistrationidentificationnumber" => Ok(Self::Nationalregistrationidentificationnumber),

            "Nationalregistrationidentificationnumber" => Ok(Self::Nationalregistrationidentificationnumber),

            _ => Err(format!("unknown Partyidentificationtypevalues value: {}", s)),
        }
    }
}
