//! Codelist enum for Paymentamountandcurrencytypevalues.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Paymentamountandcurrencytypevalues codelist values.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[allow(clippy::enum_variant_names)]
pub enum Paymentamountandcurrencytypevalues {

    #[default]
    InstructedAmountAndCurrency,

    EquivalentAmountAndCurrency,

    DebtorAccountAmountAndCurrency,

    InterbankSettlementAmountAndCurrency,

    CreditorAccountAmountAndCurrency,

    #[serde(rename = "Net/ReceivedAmountAndCurrency")]
    NetReceivedAmountAndCurrency,

    InstructedAmountAndCurrency,

    InstructedAmountAndCurrency,

    EquivalentAmountAndCurrency,

    EquivalentAmountAndCurrency,

    DebtorAccountAmountAndCurrency,

    DebtorAccountAmountAndCurrency,

    InterbankSettlementAmountAndCurrency,

    InterbankSettlementAmountAndCurrency,

    CreditorAccountAmountAndCurrency,

    CreditorAccountAmountAndCurrency,

    #[serde(rename = "Net/ReceivedAmountAndCurrency")]
    NetReceivedAmountAndCurrency,

    #[serde(rename = "Net/ReceivedAmountAndCurrency")]
    NetReceivedAmountAndCurrency,

    InstructedAmountAndCurrency,

    InstructedAmountAndCurrency,

    EquivalentAmountAndCurrency,

    EquivalentAmountAndCurrency,

    DebtorAccountAmountAndCurrency,

    DebtorAccountAmountAndCurrency,

    InterbankSettlementAmountAndCurrency,

    InterbankSettlementAmountAndCurrency,

    CreditorAccountAmountAndCurrency,

    CreditorAccountAmountAndCurrency,

    #[serde(rename = "Net/ReceivedAmountAndCurrency")]
    NetReceivedAmountAndCurrency,

    #[serde(rename = "Net/ReceivedAmountAndCurrency")]
    NetReceivedAmountAndCurrency,

}

impl std::fmt::Display for Paymentamountandcurrencytypevalues {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {

            Self::InstructedAmountAndCurrency => write!(f, "InstructedAmountAndCurrency"),

            Self::EquivalentAmountAndCurrency => write!(f, "EquivalentAmountAndCurrency"),

            Self::DebtorAccountAmountAndCurrency => write!(f, "DebtorAccountAmountAndCurrency"),

            Self::InterbankSettlementAmountAndCurrency => write!(f, "InterbankSettlementAmountAndCurrency"),

            Self::CreditorAccountAmountAndCurrency => write!(f, "CreditorAccountAmountAndCurrency"),

            Self::NetReceivedAmountAndCurrency => write!(f, "Net/ReceivedAmountAndCurrency"),

            Self::InstructedAmountAndCurrency => write!(f, "InstructedAmountAndCurrency"),

            Self::InstructedAmountAndCurrency => write!(f, "InstructedAmountAndCurrency"),

            Self::EquivalentAmountAndCurrency => write!(f, "EquivalentAmountAndCurrency"),

            Self::EquivalentAmountAndCurrency => write!(f, "EquivalentAmountAndCurrency"),

            Self::DebtorAccountAmountAndCurrency => write!(f, "DebtorAccountAmountAndCurrency"),

            Self::DebtorAccountAmountAndCurrency => write!(f, "DebtorAccountAmountAndCurrency"),

            Self::InterbankSettlementAmountAndCurrency => write!(f, "InterbankSettlementAmountAndCurrency"),

            Self::InterbankSettlementAmountAndCurrency => write!(f, "InterbankSettlementAmountAndCurrency"),

            Self::CreditorAccountAmountAndCurrency => write!(f, "CreditorAccountAmountAndCurrency"),

            Self::CreditorAccountAmountAndCurrency => write!(f, "CreditorAccountAmountAndCurrency"),

            Self::NetReceivedAmountAndCurrency => write!(f, "Net/ReceivedAmountAndCurrency"),

            Self::NetReceivedAmountAndCurrency => write!(f, "Net/ReceivedAmountAndCurrency"),

            Self::InstructedAmountAndCurrency => write!(f, "InstructedAmountAndCurrency"),

            Self::InstructedAmountAndCurrency => write!(f, "InstructedAmountAndCurrency"),

            Self::EquivalentAmountAndCurrency => write!(f, "EquivalentAmountAndCurrency"),

            Self::EquivalentAmountAndCurrency => write!(f, "EquivalentAmountAndCurrency"),

            Self::DebtorAccountAmountAndCurrency => write!(f, "DebtorAccountAmountAndCurrency"),

            Self::DebtorAccountAmountAndCurrency => write!(f, "DebtorAccountAmountAndCurrency"),

            Self::InterbankSettlementAmountAndCurrency => write!(f, "InterbankSettlementAmountAndCurrency"),

            Self::InterbankSettlementAmountAndCurrency => write!(f, "InterbankSettlementAmountAndCurrency"),

            Self::CreditorAccountAmountAndCurrency => write!(f, "CreditorAccountAmountAndCurrency"),

            Self::CreditorAccountAmountAndCurrency => write!(f, "CreditorAccountAmountAndCurrency"),

            Self::NetReceivedAmountAndCurrency => write!(f, "Net/ReceivedAmountAndCurrency"),

            Self::NetReceivedAmountAndCurrency => write!(f, "Net/ReceivedAmountAndCurrency"),

        }
    }
}

impl std::str::FromStr for Paymentamountandcurrencytypevalues {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {

            "InstructedAmountAndCurrency" => Ok(Self::InstructedAmountAndCurrency),

            "EquivalentAmountAndCurrency" => Ok(Self::EquivalentAmountAndCurrency),

            "DebtorAccountAmountAndCurrency" => Ok(Self::DebtorAccountAmountAndCurrency),

            "InterbankSettlementAmountAndCurrency" => Ok(Self::InterbankSettlementAmountAndCurrency),

            "CreditorAccountAmountAndCurrency" => Ok(Self::CreditorAccountAmountAndCurrency),

            "Net/ReceivedAmountAndCurrency" => Ok(Self::NetReceivedAmountAndCurrency),

            "InstructedAmountAndCurrency" => Ok(Self::InstructedAmountAndCurrency),

            "InstructedAmountAndCurrency" => Ok(Self::InstructedAmountAndCurrency),

            "EquivalentAmountAndCurrency" => Ok(Self::EquivalentAmountAndCurrency),

            "EquivalentAmountAndCurrency" => Ok(Self::EquivalentAmountAndCurrency),

            "DebtorAccountAmountAndCurrency" => Ok(Self::DebtorAccountAmountAndCurrency),

            "DebtorAccountAmountAndCurrency" => Ok(Self::DebtorAccountAmountAndCurrency),

            "InterbankSettlementAmountAndCurrency" => Ok(Self::InterbankSettlementAmountAndCurrency),

            "InterbankSettlementAmountAndCurrency" => Ok(Self::InterbankSettlementAmountAndCurrency),

            "CreditorAccountAmountAndCurrency" => Ok(Self::CreditorAccountAmountAndCurrency),

            "CreditorAccountAmountAndCurrency" => Ok(Self::CreditorAccountAmountAndCurrency),

            "Net/ReceivedAmountAndCurrency" => Ok(Self::NetReceivedAmountAndCurrency),

            "Net/ReceivedAmountAndCurrency" => Ok(Self::NetReceivedAmountAndCurrency),

            "InstructedAmountAndCurrency" => Ok(Self::InstructedAmountAndCurrency),

            "InstructedAmountAndCurrency" => Ok(Self::InstructedAmountAndCurrency),

            "EquivalentAmountAndCurrency" => Ok(Self::EquivalentAmountAndCurrency),

            "EquivalentAmountAndCurrency" => Ok(Self::EquivalentAmountAndCurrency),

            "DebtorAccountAmountAndCurrency" => Ok(Self::DebtorAccountAmountAndCurrency),

            "DebtorAccountAmountAndCurrency" => Ok(Self::DebtorAccountAmountAndCurrency),

            "InterbankSettlementAmountAndCurrency" => Ok(Self::InterbankSettlementAmountAndCurrency),

            "InterbankSettlementAmountAndCurrency" => Ok(Self::InterbankSettlementAmountAndCurrency),

            "CreditorAccountAmountAndCurrency" => Ok(Self::CreditorAccountAmountAndCurrency),

            "CreditorAccountAmountAndCurrency" => Ok(Self::CreditorAccountAmountAndCurrency),

            "Net/ReceivedAmountAndCurrency" => Ok(Self::NetReceivedAmountAndCurrency),

            "Net/ReceivedAmountAndCurrency" => Ok(Self::NetReceivedAmountAndCurrency),

            _ => Err(format!("unknown Paymentamountandcurrencytypevalues value: {}", s)),
        }
    }
}
