//! Response DTO for Projectdatetime.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Response body for Projectdatetime.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct ProjectdatetimeResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_date_id: Option<uuid::Uuid>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
