<!-- Generated by codegraph. DO NOT EDIT. -->
<!-- Team settings route — delegates to @crewbase/ui TeamSettings component. -->
<script lang="ts">
	import { TeamSettings } from '@crewbase/ui';
	import { createSupabaseClient } from '$lib/supabase';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	const supabase = createSupabaseClient();
</script>

<TeamSettings
	{supabase}
	organizationId={data.organization?.id}
	organizationName={data.organization?.name ?? ''}
/>
