//! Response DTO for Position.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::CommonPositionPositionStatusCode;
pub use crate::codelist::CountryCodeList;
pub use crate::codelist::LanguageCodeList;
pub use crate::codelist::PositionScheduleTypeCodeList;
pub use crate::codelist::PositionTermTypeCodeList;
pub use crate::codelist::PositionTypeCodeList;
pub use crate::codelist::RemunerationBasisCodeList;

/// Response body for Position.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct PositionResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub career_level_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fill_by_contractor_indicator: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fill_by_student_indicator: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fill_by_volunteer_indicator: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub job_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub permanent_eligible_indicator: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_schedule_type: Option<PositionScheduleTypeCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_status: Option<CommonPositionPositionStatusCode>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_status_date: Option<chrono::NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_term_type: Option<PositionTermTypeCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_type: Option<PositionTypeCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remuneration_basis: Option<RemunerationBasisCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alternate_ids: Option<Vec<IdentifierType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub document_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
    pub interview_format_array: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_end_date: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_public_title: Option<String>,
    pub position_title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub theme_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reports_to_position_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub jurisdiction: Option<PositionJurisdictionResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_category: Option<PositionEntityResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_location: Option<PositionLocationResponse>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct PositionJurisdictionResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    pub country_sub_divisions: Vec<PositionJurisdictionAddressComponentResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct PositionJurisdictionAddressComponentResponse {
    pub r#type: String,
    pub value: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct PositionEntityResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct PositionLocationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub post_office_box: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    pub country_sub_divisions: Vec<PositionLocationAddressComponentResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct PositionLocationAddressComponentResponse {
    pub r#type: String,
    pub value: String,
}
