// Generated by codegraph. DO NOT EDIT.
// Test data fixtures for Name

export interface CreateNameDto {

  familyName?: string;

  formattedName?: string;

  givenName?: string;

}

export class NameFixture {
  static valid(overrides: Partial<CreateNameDto> = {}): CreateNameDto {
    return {







      ...overrides,
    } as CreateNameDto;
  }

  static missingRequired(): Record<string, unknown> {
    // Returns an empty object — missing all required fields, guaranteed 422
    return {};
  }

  static withOptionalFields(overrides: Partial<CreateNameDto>): CreateNameDto {
    return { ...this.valid(), ...overrides };
  }

}
