// Generated by codegraph. DO NOT EDIT.
// Test data fixtures for CurrencyCodeList

export interface CreateCurrencyCodeListDto {

}

export class CurrencyCodeListFixture {
  static valid(overrides: Partial<CreateCurrencyCodeListDto> = {}): CreateCurrencyCodeListDto {
    return {

      ...overrides,
    } as CreateCurrencyCodeListDto;
  }

  static missingRequired(): Record<string, unknown> {
    // Returns an empty object — missing all required fields, guaranteed 422
    return {};
  }

  static withOptionalFields(overrides: Partial<CreateCurrencyCodeListDto>): CreateCurrencyCodeListDto {
    return { ...this.valid(), ...overrides };
  }

}
