//! Query service for Worker. Generated by hr-graph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::WorkerResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait WorkerQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<WorkerResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<WorkerResponse>, QueryError>;
}
