//! Create DTO for Rsvp.
//! Generated by codegraph-review-gate. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::RsvpRsvpStatus;

/// Request body for creating a new Rsvp.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]

pub struct CreateRsvpRequest {
    #[garde(skip)]
    pub status: RsvpRsvpStatus,
    #[garde(skip)]
    pub timestamp: chrono::DateTime<chrono::Utc>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event: Option<CreateRsvpEventBaseRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]

pub struct CreateRsvpEventBaseRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capacity: Option<i64>,
    #[garde(skip)]
    pub title: String,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub birth_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    pub family_name: String,
    #[garde(skip)]
    pub given_name: String,
}
