//! Create DTO for Assessment.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::AgencyRoleCodeList;
pub use crate::codelist::AssessmentTypeCodeList;
pub use crate::codelist::CareerLevelCodeList;
pub use crate::codelist::CommonBinaryObjectEncoding;
pub use crate::codelist::CommonDisabilitySummaryDisabilityLevelCode;
pub use crate::codelist::CountryCodeList;
pub use crate::codelist::GenderCodeList;
pub use crate::codelist::LanguageCodeList;
pub use crate::codelist::ScoreNumericCodeList;
pub use crate::codelist::ServiceAvailabilityCodeList;
pub use crate::codelist::UnitCodeList;

/// Request body for creating a new Assessment.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub catalog: Option<CreateAssessmentCatalogRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub report: Option<CreateAssessmentReportRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_sequence: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alternate_ids: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
    #[garde(skip)]
    #[serde(default)]
    pub packages: Vec<CreateAssessmentCatalogAssessmentPackageRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub descriptions: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ids: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub package_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub package_type_codes: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_group_ids: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_availability_code: Option<ServiceAvailabilityCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub administration: Option<CreateAssessmentCatalogAssessmentPackageAssessmentAdministrationRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub applicability: Option<CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilityRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fulfillment: Option<CreateAssessmentCatalogAssessmentPackageAssessmentFulfillmentRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub party_reporting_ids: Vec<CreateAssessmentCatalogAssessmentPackageIdSetRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentAdministrationRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub descriptions: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proctored_assessment_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduling_required_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub test_duration: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_enforced_indicator: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilityRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub career_level_code: Option<CareerLevelCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub descriptions: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub job_category_codes: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default)]
    pub applicable_regions: Vec<CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilityJurisdictionRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub assessed_competencies: Vec<CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilitySpecifiedCompetencyRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub assessment_type_codes: Vec<CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilityAssessmentTypeCodesRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilityJurisdictionRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[garde(skip)]
    #[serde(default)]
    pub country_sub_divisions: Vec<CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilityJurisdictionAddressComponentRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilityJurisdictionAddressComponentRequest {
    #[garde(skip)]
    pub r#type: String,
    #[garde(skip)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilitySpecifiedCompetencyRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub competency_ids: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proficiency_level: Option<CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilitySpecifiedCompetencyBaseScoreRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilitySpecifiedCompetencyBaseScoreRequest {
    #[garde(skip)]
    #[serde(default)]
    pub scores_numeric: Vec<CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilitySpecifiedCompetencyBaseScoreScoreNumericRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub scores_text: Vec<CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilitySpecifiedCompetencyBaseScoreScoreTextRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilitySpecifiedCompetencyBaseScoreScoreNumericRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub score_code: Option<ScoreNumericCodeList>,
    #[garde(skip)]
    pub value: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilitySpecifiedCompetencyBaseScoreScoreTextRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minimum: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub score_text_code: Option<String>,
    #[garde(skip)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentApplicabilityAssessmentTypeCodesRequest {
    #[garde(skip)]
    pub code: AssessmentTypeCodeList,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentFulfillmentRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub descriptions: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_period: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub score_profile_names: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default)]
    pub report_language_codes: Vec<CreateAssessmentCatalogAssessmentPackageAssessmentFulfillmentReportLanguageCodesRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageAssessmentFulfillmentReportLanguageCodesRequest {
    #[garde(skip)]
    pub code: LanguageCodeList,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentCatalogAssessmentPackageIdSetRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agency_role: Option<AgencyRoleCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identifier_attribute_group: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_sequence: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub results_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alternate_ids: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assessment_results_url: Option<CreateAssessmentReportRedirectUrlRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<CreateAssessmentReportAssessmentSubjectRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportRedirectUrlRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_out: Option<i64>,
    #[garde(skip)]
    pub uri: String,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accomodation_type_codes: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub internal_candidate_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disability_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar_mime_type: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub birth_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ethnicity: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gender: Option<GenderCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub legal_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub military_status: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_legal_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profile_photo_url: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profile_photo_mime_type: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary_language: Option<LanguageCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub birth_place: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub death_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employment_permits_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub father_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub marital_status: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub marital_status_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mother_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nationality: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub passport_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub race: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub religion: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub student_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub student_status: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub student_type: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visa: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub age: Option<i64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub blood_type: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub eye_color: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hair_color: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identifying_marks: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tobacco_user_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default)]
    pub citizenship: Vec<CreateAssessmentReportAssessmentSubjectCitizenshipRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub residence_country: Vec<CreateAssessmentReportAssessmentSubjectResidenceCountryRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub communication: Option<CreateAssessmentReportAssessmentSubjectCommunicationRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<CreateAssessmentReportAssessmentSubjectPersonNameRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub legal_documents: Vec<CreateAssessmentReportAssessmentSubjectLegalDocumentRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disability: Option<CreateAssessmentReportAssessmentSubjectDisabilityRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<CreateAssessmentReportAssessmentSubjectMeasureRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectCitizenshipRequest {
    #[garde(skip)]
    pub code: CountryCodeList,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectResidenceCountryRequest {
    #[garde(skip)]
    pub code: CountryCodeList,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectCommunicationRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<CreateAssessmentReportAssessmentSubjectCommunicationAddressTypeArrayRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<CreateAssessmentReportAssessmentSubjectCommunicationEmailTypeArrayRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<CreateAssessmentReportAssessmentSubjectCommunicationPhoneTypeArrayRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub social: Option<CreateAssessmentReportAssessmentSubjectCommunicationSocialTypeArrayRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub web: Option<CreateAssessmentReportAssessmentSubjectCommunicationWebTypeArrayRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectCommunicationAddressTypeArrayRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo_location: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo_location_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_office_box: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    #[garde(skip)]
    #[serde(default)]
    pub country_sub_divisions: Vec<CreateAssessmentReportAssessmentSubjectCommunicationAddressTypeArrayAddressComponentRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectCommunicationAddressTypeArrayAddressComponentRequest {
    #[garde(skip)]
    pub r#type: String,
    #[garde(skip)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectCommunicationEmailTypeArrayRequest {
    #[garde(skip)]
    pub address: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectCommunicationPhoneTypeArrayRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub access: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub area_dialing_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_dialing_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dial_number: Option<String>,
    #[garde(skip)]
    pub formatted_number: String,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone_extension: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectCommunicationSocialTypeArrayRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    #[garde(skip)]
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectCommunicationWebTypeArrayRequest {
    #[garde(skip)]
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectPersonNameRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub family: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub family_prefix: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub formatted_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub former_family: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub former_family_prefix: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generation_affix_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub given: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub initials: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub legal: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub middle: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preferred: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preferred_salutation_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qualification_affix_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub script: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title_affix_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectLegalDocumentRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_validity_period: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_type: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub issuing_authority: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agency_uri: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheme_agency_id: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheme_id: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheme_link: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheme_version_id: Option<String>,
    #[garde(skip)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectDisabilityRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default)]
    pub summary: Vec<CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accommodation_type_code: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disability_certified_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disability_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disability_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disability_level_code: Option<CommonDisabilitySummaryDisabilityLevelCode>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_date: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percentage: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recovery_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default)]
    pub attachment_references: Vec<CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryAttachmentReferenceRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub attachments: Vec<CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryAttachmentRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryCommentRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disability_type: Option<CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryEntityRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryAttachmentReferenceRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub descriptions: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference: Option<serde_json::Value>,
    #[garde(skip)]
    pub uri: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryAttachmentRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub descriptions: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryAttachmentBinaryObjectRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryAttachmentBinaryObjectRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encoding: Option<CommonBinaryObjectEncoding>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[garde(skip)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryCommentRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub datetime: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    pub note: String,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectDisabilityDisabilitySummaryEntityRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreateAssessmentReportAssessmentSubjectMeasureRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit_code: Option<UnitCodeList>,
    #[garde(skip)]
    pub value: f64,
}
