//! Create DTO for PayrollInstructions.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::ActionCodeList;
pub use crate::codelist::CountryCodeList;
pub use crate::codelist::CurrencyCodeList;
pub use crate::codelist::LanguageCodeList;
pub use crate::codelist::PayRateIntervalCodeList;
pub use crate::codelist::UnitCodeList;

/// Request body for creating a new PayrollInstructions.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePayrollInstructionsRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_instructions_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub person_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alternate_ids: Option<Vec<IdentifierType>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
    #[garde(skip)]
    #[serde(default)]
    pub deduction_instructions: Vec<CreatePayrollInstructionsRemunerationOrDeductionRequest>,
    #[garde(skip)]
    #[serde(default)]
    pub garnishment_instructions: Vec<CreatePayrollInstructionsGarnishmentInstructionRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePayrollInstructionsRemunerationOrDeductionRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validity_period: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_payment_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deployment_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employer_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employer_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employer_percentage: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval_code: Option<PayRateIntervalCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub one_time_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_balance_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_balance_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remaining_balance_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remaining_balance_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_percentage: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_rate: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_rate_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_unit_type: Option<UnitCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_units: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sequence: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_code: Option<ActionCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sub_type_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_transactions: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub type_code: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePayrollInstructionsGarnishmentInstructionRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validity_period: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_service_charge_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_service_charge_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub issuance_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub issuer_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum_service_charge_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub maximum_service_charge_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub partial_garnishment_allowed_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub protected_earnings_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub protected_earnings_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub registration_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_charge_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_charge_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_charge_fee_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actual_payment_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deployment_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employer_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employer_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employer_percentage: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval_code: Option<PayRateIntervalCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub one_time_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_balance_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_balance_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<serde_json::Value>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remaining_balance_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remaining_balance_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_amount: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_amount_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_percentage: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_rate: Option<rust_decimal::Decimal>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_rate_currency: Option<CurrencyCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_unit_type: Option<UnitCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_units: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sequence: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_code: Option<ActionCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sub_type_code: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_transactions: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub type_code: Option<String>,
    #[garde(skip)]
    #[serde(default)]
    pub jurisdiction_regions: Vec<CreatePayrollInstructionsGarnishmentInstructionJurisdictionRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePayrollInstructionsGarnishmentInstructionJurisdictionRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[garde(skip)]
    #[serde(default)]
    pub country_sub_divisions: Vec<CreatePayrollInstructionsGarnishmentInstructionJurisdictionAddressComponentRequest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct CreatePayrollInstructionsGarnishmentInstructionJurisdictionAddressComponentRequest {
    #[garde(skip)]
    pub r#type: String,
    #[garde(skip)]
    pub value: String,
}
