//! Query service for PayrollInstructions. Generated by hr-graph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::PayrollInstructionsResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait PayrollInstructionsQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<PayrollInstructionsResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<PayrollInstructionsResponse>, QueryError>;
}
