//! Update DTO for Account.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Accounttypevalues;
use super::dto_create::CreateAccountAccountbalanceRequest;
use super::dto_create::CreateAccountAccountcurrencyRequest;
use super::dto_create::CreateAccountAccountdatetimeRequest;
use super::dto_create::CreateAccountAccountidentificationRequest;
use super::dto_create::CreateAccountAccountstatusRequest;

/// Request body for updating an existing Account.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct UpdateAccountRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_name_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_purpose: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_type: Option<Accounttypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_date_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_identification: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_period_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_type: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_balance: Option<CreateAccountAccountbalanceRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_currency: Option<CreateAccountAccountcurrencyRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_date: Option<CreateAccountAccountdatetimeRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_identification: Option<CreateAccountAccountidentificationRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_status: Option<CreateAccountAccountstatusRequest>,
}
