//! Update DTO for Dependent.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::FamilyRelationshipCodeList;
use super::dto_create::CreateDependentPersonReferenceRequest;
use super::dto_create::CreateDependentPersonReferenceCommunicationRequest;
use super::dto_create::CreateDependentPersonReferenceCommunicationAddressTypeArrayRequest;
use super::dto_create::CreateDependentPersonReferenceCommunicationAddressTypeArrayAddressComponentRequest;
use super::dto_create::CreateDependentPersonReferenceCommunicationEmailTypeArrayRequest;
use super::dto_create::CreateDependentPersonReferenceCommunicationPhoneTypeArrayRequest;
use super::dto_create::CreateDependentPersonReferenceCommunicationSocialTypeArrayRequest;
use super::dto_create::CreateDependentPersonReferenceCommunicationWebTypeArrayRequest;
use super::dto_create::CreateDependentPersonReferencePersonNameRequest;
use super::dto_create::CreateDependentSubscriberPersonRequest;
use super::dto_create::CreateDependentSubscriberPersonCitizenshipRequest;
use super::dto_create::CreateDependentSubscriberPersonResidenceCountryRequest;
use super::dto_create::CreateDependentSubscriberPersonCommunicationRequest;
use super::dto_create::CreateDependentSubscriberPersonCommunicationAddressTypeArrayRequest;
use super::dto_create::CreateDependentSubscriberPersonCommunicationAddressTypeArrayAddressComponentRequest;
use super::dto_create::CreateDependentSubscriberPersonCommunicationEmailTypeArrayRequest;
use super::dto_create::CreateDependentSubscriberPersonCommunicationPhoneTypeArrayRequest;
use super::dto_create::CreateDependentSubscriberPersonCommunicationSocialTypeArrayRequest;
use super::dto_create::CreateDependentSubscriberPersonCommunicationWebTypeArrayRequest;
use super::dto_create::CreateDependentSubscriberPersonPersonNameRequest;
use super::dto_create::CreateDependentSubscriberPersonDisabilityRequest;
use super::dto_create::CreateDependentSubscriberPersonDisabilityDisabilitySummaryRequest;
use super::dto_create::CreateDependentSubscriberPersonDisabilityDisabilitySummaryAttachmentReferenceRequest;
use super::dto_create::CreateDependentSubscriberPersonDisabilityDisabilitySummaryAttachmentRequest;
use super::dto_create::CreateDependentSubscriberPersonDisabilityDisabilitySummaryAttachmentBinaryObjectRequest;
use super::dto_create::CreateDependentSubscriberPersonDisabilityDisabilitySummaryCommentRequest;
use super::dto_create::CreateDependentSubscriberPersonDisabilityDisabilitySummaryEntityRequest;
use super::dto_create::CreateDependentSubscriberPersonMeasureRequest;
use super::dto_create::CreateDependentSubscriberPersonLegalDocumentRequest;
use super::dto_create::CreateDependentSpecifiedPersonRequest;
use super::dto_create::CreateDependentSpecifiedPersonCommunicationRequest;
use super::dto_create::CreateDependentSpecifiedPersonCommunicationAddressTypeArrayRequest;
use super::dto_create::CreateDependentSpecifiedPersonCommunicationAddressTypeArrayAddressComponentRequest;
use super::dto_create::CreateDependentSpecifiedPersonCommunicationEmailTypeArrayRequest;
use super::dto_create::CreateDependentSpecifiedPersonCommunicationPhoneTypeArrayRequest;
use super::dto_create::CreateDependentSpecifiedPersonCommunicationSocialTypeArrayRequest;
use super::dto_create::CreateDependentSpecifiedPersonCommunicationWebTypeArrayRequest;
use super::dto_create::CreateDependentSpecifiedPersonPersonNameRequest;

/// Request body for updating an existing Dependent.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct UpdateDependentRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub education_organization_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub full_time_student_indicator: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub relationship: Option<FamilyRelationshipCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custodial_parent: Option<CreateDependentPersonReferenceRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub person: Option<CreateDependentSubscriberPersonRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub responsible: Option<CreateDependentSpecifiedPersonRequest>,
}
