//! Domain events for EffectiveDate.
//! Generated by codegraph. DO NOT EDIT.

use chrono::{DateTime, Utc};
use serde::Serialize;
use uuid::Uuid;

/// Event payload carrying metadata for EffectiveDate domain events.
#[derive(Debug, Clone, Serialize)]
#[allow(dead_code)]
pub struct EffectiveDateEventPayload {
    pub id: Uuid,
    pub correlation_id: Uuid,
    pub occurred_at: DateTime<Utc>,
    pub platform_organization_id: Uuid,
}

#[derive(Debug, Clone, Serialize)]
#[allow(dead_code)]
pub enum EffectiveDateEvent {


    Created(Box<EffectiveDateEventPayload>),





    Updated {
        payload: Box<EffectiveDateEventPayload>,
        changed_fields: Vec<String>,
    },



    Deleted(Box<EffectiveDateEventPayload>),







}
