//! Query service for FinancialFacility. Generated by codegraph. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::FinancialFacilityResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait FinancialFacilityQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<FinancialFacilityResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<FinancialFacilityResponse>, QueryError>;
}
