//! Response DTO for Organisationname.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Organisationnametypevalues;

/// Response body for Organisationname.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct OrganisationnameResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name_type: Option<Organisationnametypevalues>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
