//! Response DTO for WorkerCompensation.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::CurrencyCodeList;
pub use crate::codelist::LanguageCodeList;
pub use crate::codelist::PayTypeCodeList;
pub use crate::codelist::TimeOffTypeCodeList;
pub use crate::codelist::USBenefitTypeCodeList;
pub use crate::codelist::VoluntaryBenefitTypeCodeList;

/// Response body for WorkerCompensation.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reporting_time_period: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_compensation_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_compensation_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_direct_compensation_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_direct_compensation_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_indirect_compensation_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_indirect_compensation_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_worker_withholding_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_worker_withholding_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alternate_ids: Option<Vec<IdentifierType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub document_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direct_compensation_amount: Option<WorkerCompensationDirectCompensationResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub indirect_compensation_amount: Option<WorkerCompensationIndirectCompensationResponse>,
    pub taxable_compensation_amount: Vec<WorkerCompensationTaxableCompensationResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worker_withholding_amount: Option<WorkerCompensationWorkerWithholdingResponse>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationDirectCompensationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub salary_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub salary_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_holiday_paid_time_off_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_holiday_paid_time_off_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_hourly_wage_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_hourly_wage_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_other_compensation_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_other_compensation_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_paid_timeoff_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_paid_timeoff_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_premium_hourly_wage_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_premium_hourly_wage_amount_currency: Option<CurrencyCodeList>,
    pub other_compensation_amount: Vec<WorkerCompensationDirectCompensationWorkedCompensationAmountResponse>,
    pub paid_time_off_amount: Vec<WorkerCompensationDirectCompensationTimeOffCompensationAmountResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationDirectCompensationWorkedCompensationAmountResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worked_pay_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worked_pay_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub worked_pay_type_code: Option<PayTypeCodeList>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationDirectCompensationTimeOffCompensationAmountResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_off_pay_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_off_pay_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_off_pay_type: Option<TimeOffTypeCodeList>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationIndirectCompensationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_non_voluntary_benefit_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_non_voluntary_benefit_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_voluntary_benefit_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_voluntary_benefit_amount_currency: Option<CurrencyCodeList>,
    pub non_voluntary_benefit_amount: Vec<WorkerCompensationIndirectCompensationNonVoluntaryBenefitAmountResponse>,
    pub voluntary_benefit_amount: Vec<WorkerCompensationIndirectCompensationVoluntaryBenefitAmountResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationIndirectCompensationNonVoluntaryBenefitAmountResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub type_code: Option<USBenefitTypeCodeList>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationIndirectCompensationVoluntaryBenefitAmountResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub type_code: Option<VoluntaryBenefitTypeCodeList>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationTaxableCompensationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationWorkerWithholdingResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_insurance_premiums_withholding_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_insurance_premiums_withholding_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_other_withholding_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_other_withholding_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_retirement_withholding_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_retirement_withholding_amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_tax_withholding_amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_tax_withholding_amount_currency: Option<CurrencyCodeList>,
    pub insurance_premiums_withholding_amount: Vec<WorkerCompensationWorkerWithholdingWithholdingAmountResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct WorkerCompensationWorkerWithholdingWithholdingAmountResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<rust_decimal::Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<CurrencyCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub type_code: Option<String>,
}
