use crate::generate::ProjectConfig;
use std::path::{Path, PathBuf};

use async_trait::async_trait;
use codegraph_config::DomainConfig;
use codegraph_core::traits::GraphQuerier;

use crate::error::Result;
use crate::generate::render_template_with_project;
use crate::generate::traits::{EntityGenerator, GeneratedFile};
use super::{TsEntityContext, TsFieldDef};

pub struct TsEntityGenerator {
    output_dir: PathBuf,
}

impl TsEntityGenerator {
    pub fn new(output_dir: &Path) -> Self {
        Self {
            output_dir: output_dir.to_path_buf(),
        }
    }
}

fn ts_type_for_field(rust_type: &str, is_optional: bool) -> String {
    let base = match rust_type {
        t if t.contains("String") => "string",
        t if t.contains("Uuid") => "string",
        t if t.contains("i32") || t.contains("i64") || t.contains("Decimal") => "number",
        t if t.contains("bool") => "boolean",
        t if t.contains("NaiveDate") || t.contains("DateTime") || t.contains("Date") => "string",
        t if t.contains("Vec<") || t.contains("Option<Vec<") => "any[]",
        t if t.contains("serde_json::Value") || t.contains("Json") => "any",
        _ => "string",
    };
    if is_optional {
        format!("{} | null", base)
    } else {
        base.to_string()
    }
}

fn example_for_field(name: &str, rust_type: &str) -> String {
    match name {
        "email" => "\"test@example.com\"".to_string(),
        "firstName" | "first_name" | "preferredName" | "preferred_name" => "\"Test\"".to_string(),
        "lastName" | "last_name" | "legalName" | "legal_name" => "\"Person\"".to_string(),
        "name" | "title" | "displayName" | "display_name" => "\"Test Entry\"".to_string(),
        "phone" | "phoneNumber" | "mobile" => "\"+64 4 123 4567\"".to_string(),
        "website" => "\"https://example.com\"".to_string(),
        "description" | "notes" => "\"Generated by E2E test\"".to_string(),
        "address" | "location" => "\"123 Test Street\"".to_string(),
        "city" => "\"Wellington\"".to_string(),
        "region" => "\"wellington\"".to_string(),
        "postalCode" | "postal_code" => "\"6011\"".to_string(),
        "country" => "\"NZ\"".to_string(),
        "dateOfBirth" | "date_of_birth" | "startDate" | "endDate" | "date" => {
            "\"2025-01-15\"".to_string()
        }
        "time" | "startTime" | "endTime" => "\"14:00\"".to_string(),
        "capacity" | "maxAttendees" | "max_attendees" => "50".to_string(),
        "did" => "\"did:web:test.community.os\"".to_string(),
        "atUri" | "at_uri" => "\"at://did:web:test.community.os/test\"".to_string(),
        "pronouns" => "\"they_them\"".to_string(),
        "locale" => "\"en_NZ\"".to_string(),
        "accessibilityPreferences" | "accessibility_preferences" => "[\"screen_reader\"]".to_string(),
        "communityInterests" | "community_interests" => "[\"advocacy\"]".to_string(),
        "skills" => "[\"communication\"]".to_string(),
        "volunteerInterests" | "volunteer_interests" => "[\"event_support\"]".to_string(),
        "supportNeeds" | "support_needs" => "[\"mobility\"]".to_string(),
        "consentFlags" | "consent_flags" => "[\"newsletter\"]".to_string(),
        "contactMethods" | "contact_methods" => "[]".to_string(),
        "dataClassification" | "data_classification" => "\"internal\"".to_string(),
        "documentId" | "document_id" | "alternateIds" | "alternate_ids" => "\"test-doc-001\"".to_string(),
        _ => {
            if rust_type.contains("String") {
                "\"test\"".to_string()
            } else if rust_type.contains("Uuid") {
                "\"00000000-0000-0000-0000-000000000000\"".to_string()
            } else if rust_type.contains("i32") || rust_type.contains("i64") || rust_type.contains("Decimal") {
                "42".to_string()
            } else if rust_type.contains("bool") {
                "true".to_string()
            } else if rust_type.contains("Vec<") {
                "[]".to_string()
            } else {
                "\"test\"".to_string()
            }
        }
    }
}

#[async_trait]
impl EntityGenerator for TsEntityGenerator {
    fn name(&self) -> &str {
        "playwright_ts_entity"
    }

    async fn generate(
        &self,
        db: &dyn GraphQuerier,
        schema_title: &str,
        domain: &str,
        config: &DomainConfig,
        tera: &tera::Tera,
        project: &ProjectConfig,
    ) -> Result<Vec<GeneratedFile>> {
        let schema = db
            .get_schema_in_domain(schema_title, domain)
            .await?
            .ok_or_else(|| crate::error::Error::SchemaNotFound(schema_title.into()))?;

        let module_name = schema.pg_table_name.clone();
        if module_name.is_empty() {
            return Ok(Vec::new());
        }

        let entity_name = schema.rust_type_name.clone();
        let path_segment = schema.api_path_segment.clone();

        let nsid = if project.atproto_authority.is_empty() {
            format!("community.os.{}.{}", domain, module_name)
        } else {
            format!("{}.{}.{}", project.atproto_authority, domain, module_name)
        };

        let entity_cfg = config
            .domains
            .get(domain)
            .and_then(|d| d.get_entity_config(&entity_name));

        let operations = entity_cfg
            .and_then(|ec| ec.operations.clone())
            .unwrap_or_else(|| config.defaults.operations.clone());

        let properties = db.get_properties_in_domain(schema_title, domain).await?;

        let mut seen_fields = std::collections::HashSet::new();
        let mut create_fields: Vec<TsFieldDef> = Vec::new();
        for prop in &properties {
            if prop.name == "id"
                || prop.name == "created_at"
                || prop.name == "updated_at"
                || prop.name == "deleted_at"
                || prop.name == "platform_organization_id"
                || prop.name == "is_demo_data"
            {
                continue;
            }
            if !seen_fields.insert(prop.name.clone()) {
                continue; // skip duplicate fields from schema inheritance
            }
            let is_optional = !prop.is_required;
            let rust_type = &prop.rust_field_type;
            create_fields.push(TsFieldDef {
                name: prop.name.clone(),
                label: prop.name.clone(),
                ts_type: ts_type_for_field(rust_type, is_optional),
                required: !is_optional,
                example_value: example_for_field(&prop.name, rust_type),
            });
        }

        let ctx = TsEntityContext {
            entity_name: entity_name.clone(),
            module_name: module_name.clone(),
            domain: domain.to_string(),
            path_segment: path_segment.clone(),
            nsid,
            has_create: operations.contains(&"create".to_string()),
            has_read: operations.contains(&"read".to_string()),
            has_update: operations.contains(&"update".to_string()),
            has_delete: operations.contains(&"delete".to_string()),
            has_list: operations.contains(&"read".to_string()),
            create_fields,
            schema_name: schema.pg_table_name.clone(),
        };

        let e2e_dir = self.output_dir.join("e2e-tests");
        let spec_dir = e2e_dir.join("specs").join(domain);
        let fixture_dir = e2e_dir.join("fixtures").join(domain);
        let api_dir = e2e_dir.join("api").join(domain);

        Ok(vec![
            GeneratedFile {
                path: spec_dir.join(format!("{}.spec.ts", module_name)),
                content: render_template_with_project(
                    tera,
                    "playwright/ts_spec.tera",
                    &ctx,
                    project,
                )?,
            },
            GeneratedFile {
                path: fixture_dir.join(format!("{}.ts", module_name)),
                content: render_template_with_project(
                    tera,
                    "playwright/ts_fixture.tera",
                    &ctx,
                    project,
                )?,
            },
            GeneratedFile {
                path: api_dir.join(format!("{}.ts", module_name)),
                content: render_template_with_project(
                    tera,
                    "playwright/ts_api_client.tera",
                    &ctx,
                    project,
                )?,
            },
        ])
    }
}
