//! Update DTO for JobPosting.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::LanguageCodeList;
use super::dto_create::CreateJobPostingAnnotatedDefinedTermRequest;
use super::dto_create::CreateJobPostingAnnotatedDefinedTermScaleAnnotationRequest;
use super::dto_create::CreateJobPostingAnnotatedDefinedTermScaleAnnotationAssessmentProfileRequest;
use super::dto_create::CreateJobPostingAnnotatedDefinedTermDefinedTermSetRequest;
use super::dto_create::CreateJobPostingCredentialRequest;
use super::dto_create::CreateJobPostingCredentialAnnotatedDefinedTermRequest;
use super::dto_create::CreateJobPostingCredentialAnnotatedDefinedTermScaleAnnotationRequest;
use super::dto_create::CreateJobPostingCredentialAnnotatedDefinedTermScaleAnnotationAssessmentProfileRequest;
use super::dto_create::CreateJobPostingCredentialAnnotatedDefinedTermDefinedTermSetRequest;
use super::dto_create::CreateJobPostingCredentialLocalizationInclusionRequest;
use super::dto_create::CreateJobPostingCredentialJDXOrganizationRequest;
use super::dto_create::CreateJobPostingCredentialJDXOrganizationAddressRequest;
use super::dto_create::CreateJobPostingCredentialJDXOrganizationAddressAddressComponentRequest;
use super::dto_create::CreateJobPostingCredentialJDXOrganizationAddressTypeArrayRequest;
use super::dto_create::CreateJobPostingCredentialJDXOrganizationPlaceRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceAnnotatedDefinedTermRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceAnnotatedDefinedTermScaleAnnotationRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceAnnotatedDefinedTermScaleAnnotationAssessmentProfileRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceAnnotatedDefinedTermDefinedTermSetRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceLocalizationInclusionRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceJDXOrganizationRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceJDXOrganizationAddressRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceJDXOrganizationAddressAddressComponentRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceJDXOrganizationAddressTypeArrayRequest;
use super::dto_create::CreateJobPostingQualifyingExperienceJDXOrganizationPlaceRequest;
use super::dto_create::CreateJobPostingMonetaryAmountRequest;
use super::dto_create::CreateJobPostingMonetaryAmountAnnotatedDefinedTermRequest;
use super::dto_create::CreateJobPostingMonetaryAmountAnnotatedDefinedTermScaleAnnotationRequest;
use super::dto_create::CreateJobPostingMonetaryAmountAnnotatedDefinedTermScaleAnnotationAssessmentProfileRequest;
use super::dto_create::CreateJobPostingMonetaryAmountAnnotatedDefinedTermDefinedTermSetRequest;
use super::dto_create::CreateJobPostingJDXOrganizationRequest;
use super::dto_create::CreateJobPostingJDXOrganizationAddressRequest;
use super::dto_create::CreateJobPostingJDXOrganizationAddressAddressComponentRequest;
use super::dto_create::CreateJobPostingJDXOrganizationAddressTypeArrayRequest;
use super::dto_create::CreateJobPostingJDXOrganizationAnnotatedDefinedTermRequest;
use super::dto_create::CreateJobPostingJDXOrganizationAnnotatedDefinedTermScaleAnnotationRequest;
use super::dto_create::CreateJobPostingJDXOrganizationAnnotatedDefinedTermScaleAnnotationAssessmentProfileRequest;
use super::dto_create::CreateJobPostingJDXOrganizationAnnotatedDefinedTermDefinedTermSetRequest;
use super::dto_create::CreateJobPostingJDXOrganizationPlaceRequest;
use super::dto_create::CreateJobPostingMonetaryAmountDistributionRequest;
use super::dto_create::CreateJobPostingLocalizationInclusionRequest;
use super::dto_create::CreateJobPostingPlaceRequest;
use super::dto_create::CreateJobPostingPlaceAddressRequest;
use super::dto_create::CreateJobPostingPlaceAddressAddressComponentRequest;
use super::dto_create::CreateJobPostingAssessmentProfileRequest;
use super::dto_create::CreateJobPostingAssessmentProfileAnnotatedDefinedTermRequest;
use super::dto_create::CreateJobPostingAssessmentProfileAnnotatedDefinedTermScaleAnnotationRequest;
use super::dto_create::CreateJobPostingAssessmentProfileAnnotatedDefinedTermDefinedTermSetRequest;
use super::dto_create::CreateJobPostingConditionRequest;
use super::dto_create::CreateJobPostingConditionCredentialRequest;
use super::dto_create::CreateJobPostingConditionCredentialAnnotatedDefinedTermRequest;
use super::dto_create::CreateJobPostingConditionCredentialAnnotatedDefinedTermScaleAnnotationRequest;
use super::dto_create::CreateJobPostingConditionCredentialAnnotatedDefinedTermScaleAnnotationAssessmentProfileRequest;
use super::dto_create::CreateJobPostingConditionCredentialAnnotatedDefinedTermDefinedTermSetRequest;
use super::dto_create::CreateJobPostingConditionCredentialLocalizationInclusionRequest;
use super::dto_create::CreateJobPostingConditionCredentialJDXOrganizationRequest;
use super::dto_create::CreateJobPostingConditionCredentialJDXOrganizationAddressRequest;
use super::dto_create::CreateJobPostingConditionCredentialJDXOrganizationAddressAddressComponentRequest;
use super::dto_create::CreateJobPostingConditionCredentialJDXOrganizationAddressTypeArrayRequest;
use super::dto_create::CreateJobPostingConditionCredentialJDXOrganizationPlaceRequest;
use super::dto_create::CreateJobPostingConditionQualifyingExperienceRequest;

/// Request body for updating an existing JobPosting.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct UpdateJobPostingRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub applicant_location_requirements: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub applicant_location_requirements_name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date_created: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date_modified: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date_posted: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disclaimers: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employer_overview: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub formatted_descriptions: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<Vec<IdentifierType>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub incentive_compensation: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub industries: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub job_benefits: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub job_immediate_start: Option<bool>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub job_location_types: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub job_start_date: Option<chrono::NaiveDate>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub physical_requirements: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position_id: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posting_id: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posting_instructions_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qualification_summary: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reporting_relationships: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub security_clearance_requirements: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shift_schedules: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub special_commitments: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_job_openings: Option<f64>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub travel_requirements: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_through: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub work_hours: Option<Vec<String>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alternate_ids: Option<Vec<IdentifierType>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document_id: Option<IdentifierType>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub abilities: Option<Vec<CreateJobPostingAnnotatedDefinedTermRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alternative_credentials: Option<Vec<CreateJobPostingCredentialRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alternative_education: Option<Vec<CreateJobPostingQualifyingExperienceRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_salaries: Option<Vec<CreateJobPostingMonetaryAmountRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employment_unit: Option<CreateJobPostingJDXOrganizationRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_salaries: Option<Vec<CreateJobPostingMonetaryAmountDistributionRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub in_language: Option<CreateJobPostingLocalizationInclusionRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub job_location: Option<CreateJobPostingPlaceRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required_assessments: Option<Vec<CreateJobPostingAssessmentProfileRequest>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required_conditions: Option<Vec<CreateJobPostingConditionRequest>>,
}
