//! Response DTO for Productidentification.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Productidentificationtypevalues;

/// Response body for Productidentification.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct ProductidentificationResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_identification: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_identification_type: Option<Productidentificationtypevalues>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
