// Generated by codegraph — DO NOT EDIT.
// Page Object Model for PayRun.

use playwright::api::Page;
use anyhow::Result;
use std::collections::HashMap;
use serde_json::Value;

pub struct PayRunPage<'a> {
    pub page: &'a Page,
}

impl<'a> PayRunPage<'a> {
    pub fn new(page: &'a Page) -> Self {
        Self { page }
    }

    fn base_url() -> String {
        std::env::var("PW_BASE_URL").unwrap_or_else(|_| "http://localhost:5173".to_string())
    }

    // ── Navigation ───────────────────────────────────────────────────────────

    pub async fn goto_list(&self) -> Result<()> {
        self.page.goto_builder(&format!("{}/compensation/pay-run", Self::base_url())).goto().await?;
        Ok(())
    }


    pub async fn goto_create(&self) -> Result<()> {
        self.page.goto_builder(&format!("{}/compensation/pay-run/new", Self::base_url())).goto().await?;
        Ok(())
    }



    pub async fn goto_detail(&self, id: &str) -> Result<()> {
        self.page
            .goto_builder(&format!("{}/compensation/pay-run/{id}", Self::base_url()))
            .goto()
            .await?;
        Ok(())
    }


    // ── Field interactions (Component Object Model) ──────────────────────────



    pub async fn fill_pay_run_id(&self, value: &str) -> Result<()> {
        self.page.fill_builder("#pay_run_id", value).fill().await?;
        Ok(())
    }




    pub async fn fill_run_date(&self, value: &str) -> Result<()> {
        self.page.fill_builder("#run_date", value).fill().await?;
        Ok(())
    }




    pub async fn fill_total_amount(&self, value: &str) -> Result<()> {
        self.page.fill_builder("#total_amount", value).fill().await?;
        Ok(())
    }




    pub async fn select_total_amount_currency(&self, value: &str) -> Result<()> {
        self.page
            .select_option_builder("#total_amount_currency")
            .add_value(value.to_string())
            .select_option()
            .await?;
        Ok(())
    }




    // ── Actions ──────────────────────────────────────────────────────────────


    pub async fn submit(&self) -> Result<()> {
        self.page
            .click_builder("[data-testid=\"pay_run-submit-btn\"]")
            .click()
            .await?;
        Ok(())
    }



    pub async fn delete(&self) -> Result<()> {
        self.page
            .click_builder("[data-testid=\"pay_run-delete-btn\"]")
            .click()
            .await?;
        self.page
            .click_builder("[data-testid=\"confirm-dialog-confirm\"]")
            .click()
            .await?;
        Ok(())
    }





    // ── Convenience: create via form, return ID ──────────────────────────────

    /// Navigate to the create page, fill each field from `data`, submit,
    /// and extract the entity ID from the post-redirect URL.
    pub async fn create(&self, data: &HashMap<&str, Value>) -> Result<String> {
        self.goto_create().await?;


        if let Some(v) = data.get("pay_run_id").and_then(|v| v.as_str()) {
            self.fill_pay_run_id(v).await.ok();
        }



        if let Some(v) = data.get("run_date").and_then(|v| v.as_str()) {
            self.fill_run_date(v).await.ok();
        }



        if let Some(v) = data.get("total_amount").and_then(|v| v.as_str()) {
            self.fill_total_amount(v).await.ok();
        }



        if let Some(v) = data.get("total_amount_currency").and_then(|v| v.as_str()) {
            self.select_total_amount_currency(v).await.ok();
        }


        self.submit().await?;
        let url: String = self.page.url()?;
        let id = url
            .split('/')
            .last()
            .unwrap_or("")
            .to_string();
        Ok(id)
    }

}
