//! Response DTO for SynchronousOrder.
//! Generated by hr-graph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use codegraph_type_contracts::IdentifierType;
pub use crate::codelist::CountryCodeList;
pub use crate::codelist::LanguageCodeList;

/// Response body for SynchronousOrder.
#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderResponse {
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_interview_order_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_position_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interview_format_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interview_order_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language_code: Option<LanguageCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position_title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub self_schedule_indicator: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alternate_ids: Option<Vec<IdentifierType>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub document_id: Option<IdentifierType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
    pub candidates: Vec<SynchronousOrderCandidateContactResponse>,
    pub comments: Vec<SynchronousOrderCommentResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interview_address: Option<SynchronousOrderInterviewAddressResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub question: Option<SynchronousOrderPositionQuestionsResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recruiter: Option<SynchronousOrderRecruiterContactResponse>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderCandidateContactResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preferred_language: Option<LanguageCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub candidate_contact: Option<SynchronousOrderCandidateContactCommunicationResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderCandidateContactCommunicationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<SynchronousOrderCandidateContactCommunicationAddressTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<SynchronousOrderCandidateContactCommunicationEmailTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<SynchronousOrderCandidateContactCommunicationPhoneTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub social: Option<SynchronousOrderCandidateContactCommunicationSocialTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub web: Option<SynchronousOrderCandidateContactCommunicationWebTypeArrayResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderCandidateContactCommunicationAddressTypeArrayResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub post_office_box: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    pub country_sub_divisions: Vec<SynchronousOrderCandidateContactCommunicationAddressTypeArrayAddressComponentResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderCandidateContactCommunicationAddressTypeArrayAddressComponentResponse {
    pub r#type: String,
    pub value: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderCandidateContactCommunicationEmailTypeArrayResponse {
    pub address: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderCandidateContactCommunicationPhoneTypeArrayResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub access: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub area_dialing_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_dialing_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dial_number: Option<String>,
    pub formatted_number: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone_extension: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderCandidateContactCommunicationSocialTypeArrayResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    pub url: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderCandidateContactCommunicationWebTypeArrayResponse {
    pub url: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderCommentResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub datetime: Option<chrono::DateTime<chrono::Utc>>,
    pub note: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderInterviewAddressResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comments: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub post_office_box: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    pub country_sub_divisions: Vec<SynchronousOrderInterviewAddressAddressComponentResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderInterviewAddressAddressComponentResponse {
    pub r#type: String,
    pub value: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderPositionQuestionsResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_rerecord_count: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interview_format_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub comments: Vec<SynchronousOrderPositionQuestionsCommentResponse>,
    pub questions: Vec<SynchronousOrderPositionQuestionsQuestionResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderPositionQuestionsCommentResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub datetime: Option<chrono::DateTime<chrono::Utc>>,
    pub note: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<LanguageCodeList>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderPositionQuestionsQuestionResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_response_length: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_response_time_seconds: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub question_context: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub question_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rerecord_count: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_prep_time_seconds: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub review_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_url: Option<SynchronousOrderPositionQuestionsQuestionWebResponse>,
    pub ranking_choice: Vec<SynchronousOrderPositionQuestionsQuestionChoiceResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderPositionQuestionsQuestionWebResponse {
    pub url: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderPositionQuestionsQuestionChoiceResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderRecruiterContactResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recruiter_contact: Option<SynchronousOrderRecruiterContactCommunicationResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderRecruiterContactCommunicationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<SynchronousOrderRecruiterContactCommunicationAddressTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<SynchronousOrderRecruiterContactCommunicationEmailTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<SynchronousOrderRecruiterContactCommunicationPhoneTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub social: Option<SynchronousOrderRecruiterContactCommunicationSocialTypeArrayResponse>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub web: Option<SynchronousOrderRecruiterContactCommunicationWebTypeArrayResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderRecruiterContactCommunicationAddressTypeArrayResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCodeList>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_location_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub post_office_box: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    pub country_sub_divisions: Vec<SynchronousOrderRecruiterContactCommunicationAddressTypeArrayAddressComponentResponse>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderRecruiterContactCommunicationAddressTypeArrayAddressComponentResponse {
    pub r#type: String,
    pub value: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderRecruiterContactCommunicationEmailTypeArrayResponse {
    pub address: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderRecruiterContactCommunicationPhoneTypeArrayResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub access: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub area_dialing_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_dialing_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dial_number: Option<String>,
    pub formatted_number: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone_extension: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderRecruiterContactCommunicationSocialTypeArrayResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    pub url: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, ToSchema)]
pub struct SynchronousOrderRecruiterContactCommunicationWebTypeArrayResponse {
    pub url: String,
}
