//! Update DTO for VoiceChannelOperatingSession.
//! Generated by codegraph. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
pub use crate::codelist::Reporttypevalues;
use super::dto_create::CreateVoiceChannelOperatingSessionCustomerContactRequest;
use super::dto_create::CreateVoiceChannelOperatingSessionProductionIssueRequest;
use super::dto_create::CreateVoiceChannelOperatingSessionReportRequest;

/// Request body for updating an existing VoiceChannelOperatingSession.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]
pub struct UpdateVoiceChannelOperatingSessionRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub advanced_voice_services_operations_service_menu: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub employee_business_unit_reference_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub production_issue_description: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub production_issue_diagnosis: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub production_issue_resolution_task_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub production_issue_status_id: Option<uuid::Uuid>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub production_issue_type: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub v_channel_service_session_report_type: Option<Reporttypevalues>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub v_channel_service_session_statistics: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub voice_channel_operating_session_id: Option<String>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub customer_contact_record_reference: Option<CreateVoiceChannelOperatingSessionCustomerContactRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub v_channel_production_issue_record: Option<CreateVoiceChannelOperatingSessionProductionIssueRequest>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub v_channel_service_session_report: Option<CreateVoiceChannelOperatingSessionReportRequest>,
}
