//! Create DTO for ProcessHistoryItem.
//! Generated by codegraph-review-gate. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Request body for creating a new ProcessHistoryItem.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, garde::Validate)]

pub struct CreateProcessHistoryItemRequest {
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_date: Option<chrono::DateTime<chrono::Utc>>,
    #[garde(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub descriptions: Option<Vec<String>>,
}
