//! Query service for ProcessHistoryItem. Generated by codegraph-review-gate. DO NOT EDIT.

use async_trait::async_trait;
use uuid::Uuid;

use super::dto_response::ProcessHistoryItemResponse;
use crate::query::{ListParams, PagedResult, QueryError};

#[async_trait]
pub trait ProcessHistoryItemQueryService: Send + Sync {
    async fn find_by_id(&self, id: Uuid) -> Result<Option<ProcessHistoryItemResponse>, QueryError>;
    async fn list(&self, params: ListParams) -> Result<PagedResult<ProcessHistoryItemResponse>, QueryError>;
}
