//! API-key scope enforcement for generated domain routes.
//! Generated by codegraph. DO NOT EDIT.
//!
//! Mirrors the hand-written platform guard (`cosmos_extensions::http::platform`)
//! exactly, so every generated `/api/v1/{domain}/{entity}/*` route enforces the
//! API key's scopes, not just the hand-written platform handlers.
//!
//! Vocabulary: `{domain}.{entity}.read|write` (GET/HEAD -> read, else write),
//! `{domain}.*` (all operations in one domain), `"*"` and `"admin"` (everything).
//! Non-API-key callers (JWT / magic-link / test-mode) always pass. A failed
//! scope lookup (missing row / DB error) is treated as "no scopes" — only
//! wildcard scopes can then satisfy the check. A denied scope yields HTTP 403
//! `INSUFFICIENT_SCOPE` with the same body shape as the platform guard.


use axum::http::{Method, StatusCode};
use sea_orm::{ConnectionTrait, DatabaseBackend, DatabaseConnection, Statement};
use uuid::Uuid;

use crate::error::AppError;
use crate::middleware::{AuthInfo, AuthMode};

/// Enforce that the API key backing this request holds `{domain}.{entity}.{op}`
/// where `op` is derived from the HTTP method (GET/HEAD -> read, else write).
/// Non-API-key callers always pass.
pub async fn require_scope(
    db: &DatabaseConnection,
    auth: &AuthInfo,
    domain: &str,
    entity: &str,
    method: &Method,
) -> Result<(), AppError> {
    if !matches!(auth.auth_mode, AuthMode::ApiKey { .. }) {
        return Ok(());
    }

    let scopes = fetch_scopes(db, auth.api_key_id).await;
    let operation = match method.as_str() {
        "GET" | "HEAD" => "read",
        _ => "write",
    };
    if has_scope(&scopes, domain, entity, operation) {
        return Ok(());
    }

    let required = format!("{domain}.{entity}.{operation}");
    Err(AppError {
        status: StatusCode::FORBIDDEN,
        code: "INSUFFICIENT_SCOPE",
        message: format!("API key lacks scope {required}"),
        details: None,
        correlation_id: None,
    })
}

/// Fetch the API key's scopes by key id. A missing row or DB error is treated
/// as "no scopes".
async fn fetch_scopes(db: &DatabaseConnection, api_key_id: Uuid) -> Vec<String> {
    let row = db
        .query_one(Statement::from_sql_and_values(
            DatabaseBackend::Postgres,
            "SELECT scopes FROM api_keys_private.api_keys WHERE id = $1",
            vec![api_key_id.into()],
        ))
        .await;
    match row {
        Ok(Some(row)) => {
            let value: Result<serde_json::Value, _> = row.try_get_by_index(0);
            match value {
                Ok(v) => v
                    .as_array()
                    .map(|items| {
                        items
                            .iter()
                            .filter_map(|item| item.as_str().map(String::from))
                            .collect()
                    })
                    .unwrap_or_default(),
                Err(_) => Vec::new(),
            }
        }
        _ => Vec::new(),
    }
}

/// Scope matcher shared with the platform guard: exact match, `{domain}.*`
/// domain wildcard, or the global `"*"` / `"admin"` wildcards.
pub fn has_scope(scopes: &[String], domain: &str, entity: &str, operation: &str) -> bool {
    let domain_wildcard = format!("{domain}.*");
    let required = format!("{domain}.{entity}.{operation}");
    scopes.iter().any(|scope| {
        scope == "*" || scope == "admin" || scope == &domain_wildcard || scope == &required
    })
}

/// Route-level middleware for generated entity routes. Reads the caller's
/// `AuthInfo` and the `DatabaseConnection` (injected into request extensions by
/// `server.rs` — route-level layers cannot access router state) and enforces
/// `{domain}.{entity}.{read|write}` for API-key callers. Unknown callers pass
/// through untouched; a missing DB extension denies closed (never bypasses).
pub async fn require_scope_for_request(
    request: axum::extract::Request,
    next: axum::middleware::Next,
    domain: &str,
    entity: &str,
) -> axum::response::Response {
    use axum::response::IntoResponse;

    let auth = match request.extensions().get::<AuthInfo>() {
        Some(auth) => auth.clone(),
        // No verified caller — nothing to scope-check (auth middleware denies
        // unauthenticated requests before we ever run).
        None => return next.run(request).await,
    };
    let db = match request.extensions().get::<DatabaseConnection>() {
        Some(db) => db.clone(),
        None => {
            tracing::error!(
                "DatabaseConnection extension missing; denying scoped request"
            );
            return AppError::internal("Scope enforcement unavailable").into_response();
        }
    };
    match require_scope(&db, &auth, domain, entity, request.method()).await {
        Ok(()) => next.run(request).await,
        Err(e) => e.into_response(),
    }
}

#[cfg(test)]
mod tests {
    use super::has_scope;

    fn scopes(items: &[&str]) -> Vec<String> {
        items.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn scope_matcher_exact_match() {
        assert!(has_scope(&scopes(&["events.public_event.read"]), "events", "public_event", "read"));
        assert!(!has_scope(&scopes(&["events.public_event.read"]), "events", "public_event", "write"));
        assert!(!has_scope(&scopes(&["events.public_event.read"]), "crm", "person_record", "read"));
    }

    #[test]
    fn scope_matcher_domain_wildcard() {
        assert!(has_scope(&scopes(&["events.*"]), "events", "public_event", "write"));
        assert!(has_scope(&scopes(&["events.*"]), "events", "public_event", "read"));
        assert!(!has_scope(&scopes(&["events.*"]), "crm", "person_record", "read"));
    }

    #[test]
    fn scope_matcher_global_wildcards() {
        assert!(has_scope(&scopes(&["*"]), "events", "public_event", "write"));
        assert!(has_scope(&scopes(&["admin"]), "events", "public_event", "write"));
        assert!(has_scope(&scopes(&["admin"]), "any", "thing", "read"));
    }

    #[test]
    fn scope_matcher_multiple_scopes() {
        assert!(has_scope(
            &scopes(&["crm.*", "events.public_event.read"]),
            "events",
            "public_event",
            "read"
        ));
        assert!(!has_scope(
            &scopes(&["crm.*", "events.public_event.read"]),
            "events",
            "public_event",
            "write"
        ));
    }

    #[test]
    fn scope_matcher_empty_scopes_deny() {
        assert!(!has_scope(&scopes(&[]), "events", "public_event", "read"));
        assert!(!has_scope(&scopes(&[]), "events", "public_event", "write"));
    }
}


